### ISSUE TITLE
UI Redesign

### ISSUE THREAD

**Issue by qarmin** [qarmin/czkawka#1]
For now Czkawka aims to be almost 100% clone of Fslint.
FSlint UI is almost 10 years old, so could be changed and improved.

Fslint UI 2.4.7
![Zrzut ekranu z 2020-09-22 19-39-57](https://user-images.githubusercontent.com/41945903/93918251-5a060400-fd0c-11ea-8cb8-e8f6473354a5.png)

Czkawka GUI Gtk
![Zrzut ekranu z 2020-12-24 15-20-05](https://user-images.githubusercontent.com/41945903/103093744-870fce80-45fb-11eb-9b02-caab7e9e37da.png)

**Comment by jannuary** [comment]
A quick prototype:
![Czawka](https://user-images.githubusercontent.com/27908024/102686564-222f2f80-421b-11eb-9dd9-f3e6d8355348.png)

**Comment by Jakeukalane** [comment]
**Comment**: I like a lot the fslint-gui interface. Any change should be a discernible improvement. Change for the sake of changing is not always good.

**Comment by jannuary** [comment]
Iterating a bit on the design:
<img width="3423" alt="Czkawka png" src="https://user-images.githubusercontent.com/27908024/103435707-24df4b00-4c45-11eb-8589-442286d4b089.png">
Also, are you available to contact over IM, so we could maybe have a more high-bandwidth discussion on the design vision.

**Comment by qarmin** [comment]
Currently, the biggest unknown to me is that I don't know what tools I will have in GTK4 (I am basing mainly on Glade, because creating an interface from the level of the code is really not cool).
From what I've read, many of the elements, i.e. GtkMenu has been removed and creating code and functions will look different.
As for the appearance of current concept, in my opinion it looks very good, the biggest problem I see here is that it is more advanced than the current version of Czkawka (I didn't learned more advanced functions in GTK).

So far I'm waiting for Glade with support for GTK 4 and before releasing it I'm not likely to start creating a new program, but I still have a few thoughts for now:
- These folders on the left side look quite strange with the names themselves
- I do not think it would be a good idea to mix several modes in one view, because, for example, selecting the largest size items works in similar images but not in duplicate files.
- How are the records currently being made in the middle? Is it some kind of grid or box with a selection button on the left, a file name in the middle and a size on the right?
- Shortened path of elements at the middle should automatically expand and shrink when the window is expanded or shrunk, but I don't think that I ever seeing such a feature in GTK.

**Comment by DragonSWDev** [comment]
I think Czkawka shouldn't use libadwaita. Libadwaita is specifically used to make applications for GNOME desktop that would look weird in other desktops. As universal application not limited to GNOME staying with pure GTK4 is probably better idea for other desktops.

**Comment by aleksandrmelnikov** [comment]
Cross-platform UI is a bear, no arguing there.

I do ask that whichever platform is chosen, please do consider screen resolution.
I have a 2K resolution laptop and the czkawka app is nearly illegible without the Windows Magnifier app.

**Comment by qarmin** [comment]
New gui is based on Slint, which is less flexible than GTK, but have new, similar to czkawka ui because it was quite good in term of usability for me.
