### ISSUE TITLE
[BUG] Delete and sort not working in "similar videos"

### ISSUE THREAD

**Issue by SMylk** [qarmin/czkawka#1009]
Windows 64, czkawka 6.0.
After searching for similar videos, selecting some  and trying to delete them nothing happens.
Delete seems to work in other searches.
Also using any kind of sort function in similar videos view closes the application.

**Comment by dilietol** [comment]
Same here. Similar Video mode crashes when I attempt to delete one file.
This is the error in the log:
thread 'main' panicked at 'assertion failed: model.get::<bool>(&iter, column_header)', czkawka_gui/src/help_functions.rs:558:13
Docker Platform, czkawka 6.0.0

**Comment by zooch893** [comment]
Same here, works fine on v5.1.0 I suggest using that till it's fixed.

**Comment by benjcmin** [comment]
Mayb this fits here aswell. Also selecting e.g. all but oldest selects all entries. There seems to be no way to choose select all execpt one. And only relevant for similar video, this works for files and photos but not for videos.

**Comment by rursache** [comment]
same issue here, delete does not work in v6.1 on windows :/
```sh
thread 'main' panicked at 'assertion failed: model.get::<bool>(&iter, column_header)', czkawka_gui/src/help_functions.rs:558:13
```

**Comment by magickarle** [comment]
same:
[app         ] thread 'main' panicked at 'assertion failed: model.get::<bool>(&curr_iter, column_header)', czkawka_gui/src/connect_things/connect_popovers_sort.rs:17:9

**Comment by dorelExpertu** [comment]
Same issue on Windows 11 22H2. Delete doesn't do anything in Similar Videos mode (app does not crash in my PC). Also "move" option in Similar Video mode crashes the app when you select the destination folder.
