### ISSUE TITLE
Similar images not working with .heic files.

### ISSUE THREAD

**Issue by vanchaxy** [qarmin/czkawka#1039]
I have two copies of a lot of .heic files. One is original files and another one is files compressed by google photos. They have the same resolution just one of them is compressed. I tried many combinations of resize algorithm / hash size / hast type but can't manage it to work. Here are example images:
[example dublicates.zip](https://github.com/qarmin/czkawka/files/12362284/example.dublicates.zip)

**Comment by qarmin** [comment]
`IMG_3256.HEIC` is not really heif file - `file` command shows this info
```
IMG_3256.HEIC: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=11, manufacturer=Apple, model=iPhone 13 Pro, orientation=upper-right, xresolution=166, yresolution=174, resolutionunit=2, software=16.6, datetime=2023:08:14 10:31:18, hostcomputer=iPhone 13 Pro, GPS-Data], baseline, precision 8, 4032x3024, components 3
```
with second I see it as similar image but I run app on Ubuntu, but looks that you are using Windows, which not contains heif(mingw64 fedora problem) library that allows to decode such images 

![Screenshot from 2023-10-07 19-54-09](https://github.com/qarmin/czkawka/assets/41945903/e06a8b7d-3a24-4f16-85e8-95bfb69eac8c)

**Comment by vanchaxy** [comment]
Thanks for the response. That's interesting as it's the same file before and after uploading/exporting to google photos. 

I'm using this docker image to run czkawka: https://hub.docker.com/r/jlesage/czkawka

**Comment by dpantel** [comment]
Having the same problem on linux with v6.1.0. No matter how I change the settings, it will only find similar JPEG files, but ignore exactly the same HEIC files.

**Comment by qarmin** [comment]
Docker version use libheif so it should work fine out of box - https://github.com/jlesage/docker-czkawka/blob/69c42fb77de6eecb53d4545ad9799aca62a74572/Dockerfile#L44

There is special version of gui/core with support of libheif, so it should work fine(I already use it) - https://github.com/qarmin/czkawka/releases/download/6.1.0/linux_czkawka_gui_heif
libheif is additional required dependency

**Comment by Batwam** [comment]
I am currently using the snap version 6.1.0 and also experiencing this issue. I just checked the "special version of gui/core with support of libheif" with `libheif1' installed and it is still not able to detect HEIC/JPG duplicates. Is there a way to troubleshoot what might be happening?

**Comment by jazzdd86** [comment]
same for me, tried the example duplicates zip and duplicated the files to the same folder  as @qarmin. I opened the heif version on an ubuntu VM with libheif-dev installed. No duplicates were found.

**Comment by StevenMassaro** [comment]
This is still an issue with the latest release: 7.0.0

**Comment by StevenMassaro** [comment]
I believe this is related to the orientation of the photos being compared. However, my rust knowledge is pretty limited, so I haven't been able to (and likely won't be able to) fix this.
