### ISSUE TITLE
Dublicate file finder compares files to files in trash bin

### ISSUE THREAD

**Issue by 012442** [qarmin/czkawka#1042]
Hi there, 
When doing a dublicate search for a whole drive, the files in the trash bin are also found to be dublicates.
This is not good, because in that way you risk that the system is flagging a file to be a dublicate to a file that is already in the trash bin, thus deleting both files! Another user has very accurately described this behaviour in this post (related to Dupeguru - but it seems to be an issue with czkawka): https://github.com/arsenetar/dupeguru/issues/690

This is the Windows GUI version. 

Example attached. 
![2023-08-17 22_34_13-Czkawka (Hiccup)](https://github.com/qarmin/czkawka/assets/142541342/59031930-c7c8-46c8-b967-35b6ac6ea1e7)

Also, when selecting to manually add an exclude directory and pasting a directory path, the program crashes and closes.

**Comment by neoOpus** [comment]
you have to excluse the trashbin folder use the 3rd tab for that

**Comment by 012442** [comment]
Thanks for the reply. 
Like this (see screenshot)?

I tried to exclude the recycle bin through the second tap (excluded directories), but it is not possible to select it through the dialog box. 

But in all cases, I think that it should have been excluded by default. There is a very big risk that in the current way, files are accidentially deleted because they are matched to files that are already in the recycle bin.

**Comment by neoOpus** [comment]
Yes but here my config file


[czkawka_gui_config_4.txt](https://github.com/qarmin/czkawka/files/12386896/czkawka_gui_config_4.txt)
