### ISSUE TITLE
Install in Fedora 33

### ISSUE THREAD

**Issue by fedora-linux** [qarmin/czkawka#105]
I am having trouble installing czkawka in Fedora 33.
I did dnf install cargo and it installed ok. I than downloaded your file linux_czkawka_gui and went to command to install it but got an error

root@localhost Downloads]# cargo install linux_czkawka_gui
    Updating crates.io index
error: could not find `linux_czkawka_gui` in registry `https://github.com/rust-lang/crates.io-index` with version `*`
[root@localhost Downloads]# 

Any help to install will be tremendously appreciated.

I am familiar with using dnf and RPM but tried using cargo after installing cargo but it looks like it fails.

Your program looks like what I am after as FSlint was the program I used to use before it stopped working in Fedora 33 as I now find out due to gtk2 support. 
Any help would be great.

**Comment by qarmin** [comment]
Installation with cargo should look that(I tested it in docker and it works fine)
```
sudo yum install cargo gtk3-devel glib2-devel
cargo install czkawka_gui
```
You can "install" it manually by downloading file `linux_czkawka_gui` and putting it to `/usr/bin`
```
wget https://github.com/qarmin/czkawka/releases/download/1.4.0/linux_czkawka_gui
sudo mv linux_czkawka_gui /usr/bin/czkawka_gui
```

**Comment by fedora-linux** [comment]
Hi Rafał
Thank you very much for the quick response. I still struggled a bit to get Czkawka_gui started but finally worked it out.
Problem was I was expecting the application to appear in the Gnome start menu after installation like other applications but after more experiments I worked out that Czkawka_gui must be started using the Terminal using the cargo run command in the directory that has the toml file in it. Once I worked this out application started up without any problems.
When I compare Czkawka to FSlint it is just as easy to use and has many better features than FSlint.
This application is excellent. 



Kind Regards 


Arek
 

    On Friday, November 13, 2020, 8:44:03 PM GMT+11, Rafał Mikrut <notifications@github.com> wrote:  
 
 


Installation with cargo should look that(I tested it in docker and it works fine)
sudo yum install cargo gtk3-devel glib2-devel
cargo install czkawka_gui

You can "install" it manually by downloading file linux_czkawka_gui and putting it to /usr/bin
wget https://github.com/qarmin/czkawka/releases/download/1.4.0/linux_czkawka_gui
sudo mv linux_czkawka_gui /usr/bin/czkawka_gui
