### ISSUE TITLE
Unable to delete within similar videos screen

### ISSUE THREAD

**Issue by deadbeatdandylyon** [qarmin/czkawka#1063]
When I scan for "Similar Videos" 

And it finds a comparison, when I put a check mark in one of the videos to delete and press delete nothing happens.

Not sure what to do about this? or if this is a known issue? 

Thank you for the help in advanced.

**Comment by mariolos** [comment]
The same issue for me.

**Comment by qarmin** [comment]
Duplicate of https://github.com/qarmin/czkawka/issues/1009 - fixed already in master branch, new version will be available soon
