### ISSUE TITLE
Enhance "Broken Files" Detection for JAR Files in Czkawka

### ISSUE THREAD

**Issue by fbruand** [qarmin/czkawka#1067]
**Description:**
I have been relying on Czkawka version 6.0.0 (Flatpak) to assist in sorting and managing recovered data from a failed hard drive. While Czkawka has proven to be a valuable tool in various aspects of data cleanup, I have encountered a specific challenge when dealing with potentially corrupted JAR (Java Archive) files during the data sorting process. 

**Issue:**
Czkawka currently does not seem to have the capability to detect potentially corrupted JAR files when using the "Broken Files" filter. However, other archive management tools like Ark (KDE's file archiver), PeaZIP, 7-ZIP, and JD-GUI recognize these JAR files as corrupted and cannot open them. This creates difficulties in efficiently managing and sorting recovered data, as some JAR files may be inaccessible.

**Request:**
Consider enhancing Czkawka's "Broken Files" detection functionality to include the ability to identify potentially corrupted JAR files.

Thank you for your attention to this issue, as improving Czkawka's handling of potentially corrupt JAR files would increase its usefulness for sorting files after recovering data from failed storage devices.

**Comment by qarmin** [comment]
Jar files are just renamed zip files with specific file structure.
In https://github.com/qarmin/czkawka/pull/1070 I enabled checking if jar files are valid zip files.

**Comment by fbruand** [comment]
Hi,

Is there a date for a new release? Since there is no flatpak version directly linked to the git repository, for example in the flatpak beta repository, I cannot use the latest commits with flatpak.

I have been looking forward to trying out the new JAR file detection functionality, and I hope it will be available in a new flatpak release soon.

Thank you for your work on Czkawka!

**Comment by qarmin** [comment]
Czkawka flatpak version is only provided in stable version and next version should be available in next week.

Latest builds for tests can be downloaded from CI - https://github.com/qarmin/czkawka/actions/workflows/linux_gui.yml
