### ISSUE TITLE
czkawka not finding dupes in trivial example on Mac OS

### ISSUE THREAD

**Issue by alexhunsley** [qarmin/czkawka#1084]
**Desktop**
 - Czkawka version: 6.0.0 gui
 - OS version: Mac OS 13.5.2
 - hardware: MacBook Pro 2021 (apple silicon)
 - compile and run method: as per instructions, having previously done `brew install rustup`

**Bug Description**

To reproduce:

on terminal, `cd` somewhere suitable and run this script to create a few dupe files:

```
#!/bin/bash

rm -rf czkawka_test_files_ah

TEST_DIR=czkawka_test_files_ah

mkdir -p ${TEST_DIR}/ref_dir

cd ${TEST_DIR}

printf "FILE 1\nhello world\n" > ref_dir/file1.txt
printf "FILE 2\ncats\ndogs\n" > ref_dir/file2.txt
printf "FILE 3" > ref_dir/file3.txt

cp -a ref_dir other_dir

mkdir other_dir/empty_dir
```

Then run the czkawka UI. Add just one directory: `czkawka_test_files_ah`, select duplicate file search. No duplicates are found when you search, regardless of Hash (for all hash kinds), Name, Size, Name+Size. I tried with cache enabled and cached disabled (and ensured any cache files were deleted).

I confirmed that those files really are duplicates, as expected, by using jdupes:

```
❯ jdupes -rMS .
Scanning: 8 files, 4 items (in 1 specified)
19 bytes each:
./czkawka_test_files_ah/other_dir/file1.txt
./czkawka_test_files_ah/ref_dir/file1.txt

6 bytes each:
./czkawka_test_files_ah/other_dir/file3.txt
./czkawka_test_files_ah/ref_dir/file3.txt

17 bytes each:
./czkawka_test_files_ah/other_dir/file2.txt
./czkawka_test_files_ah/ref_dir/file2.txt


3 duplicate files (in 3 sets), occupying 42 bytes
```

**Comment by qarmin** [comment]
Are you sure that you properly set minimum file size?

```
czkawka_cli dup -d /home/rafal/test/czkawka_test_files_ah/
```
not found any files, but 
```
czkawka_cli dup -d /home/rafal/test/czkawka_test_files_ah/ -m 1
```
found this
```
Found 6 duplicated files in 3 groups with same content which took 42 B:
Size - 19 B (19) - 2 files 
/home/rafal/test/czkawka_test_files_ah/ref_dir/file1.txt
/home/rafal/test/czkawka_test_files_ah/other_dir/file1.txt
----

Size - 17 B (17) - 2 files 
/home/rafal/test/czkawka_test_files_ah/ref_dir/file2.txt
/home/rafal/test/czkawka_test_files_ah/other_dir/file2.txt
----

Size - 6 B (6) - 2 files 
/home/rafal/test/czkawka_test_files_ah/ref_dir/file3.txt
/home/rafal/test/czkawka_test_files_ah/other_dir/file3.txt
----

-------------------------------MESSAGES--------------------------------
Loaded from cache ⁨0⁩ entries
Saved to file ⁨6⁩ cache entries
Loaded from cache ⁨2583⁩ entries
Saved to file ⁨2583⁩ cache entries
---------------------------END OF MESSAGES-----------------------------

```

In https://github.com/qarmin/czkawka/pull/1083 I removed limitation that forced to use only absolute directories(this was caused by gui needs) - this also can be problem here.

**Comment by alexhunsley** [comment]
Ah thanks, I didn't know about that minimum file size settings, will try it!

**Comment by alexhunsley** [comment]
Yup that was the issue, closing
