### ISSUE TITLE
Reference folders do not work in version 6.1.0

### ISSUE THREAD

**Issue by vtuba** [qarmin/czkawka#1092]
**Desktop (please complete the following information):**

- Czkawka version: 6.1.0
- OS version: Windows 10
- Terminal output[optional]:

**Bug Description**
The reference folder option is selected but it does not work

**Comment by qarmin** [comment]
Cannot reproduce problem

![Screenshot from 2023-10-15 11-11-49](https://github.com/qarmin/czkawka/assets/41945903/1acbaf51-d7b0-47eb-a120-11cd273dc395)
![Screenshot from 2023-10-15 11-12-09](https://github.com/qarmin/czkawka/assets/41945903/854c892f-de2d-4764-8504-1d86df7c2564)
![Screenshot from 2023-10-15 11-12-23](https://github.com/qarmin/czkawka/assets/41945903/2ebcebc5-4c22-4090-901d-0accfeddb064)

**Comment by qarmin** [comment]
Looks that problem happens only on windows

**Comment by qarmin** [comment]
Binaries are updated in 6.1.0 tag without releasing new version
