### ISSUE TITLE
Windows 10 mapped SMB network drives not included in scans in 6.1.0

### ISSUE THREAD

**Issue by IsaiahHopf** [qarmin/czkawka#1094]
**Desktop:**

- Czkawka version
6.1.0 Windows GUI
- OS version:
Windows 10

Since upgrading from 6.0.0 to 6.1.0 this morning, folders on mapped SMB network drives in Windows are being dropped by the new optimization code.  If they are the only folders selected to search, this leads to a misleading error

`Directories: All directories to search overlaps with excluded directories`

[This error is printed when all folders have been optimized out, whether or not they overlap with excluded directories](https://github.com/qarmin/czkawka/blob/59ff9f3e3c8ebda294b2a80a8dd9b79c9cd07f28/czkawka_core/src/common_directory.rs#L272).  I don't know which step of the optimization code is dropping the folders, but I'm only seeing this behavior for folders located on SMB network shares that I've mapped to drives in Windows 10.

...

**Comment by Biepa** [comment]
Can confirm this. Only have a share and not excluded paths.
Windows 11 here.

**Comment by qarmin** [comment]
I replaced windows binaries in 6.1.0 release page.
Releasing new version is quite long process, so I avoid it if possible - and here it was possible, because problem only happened on Windows

**Comment by Biepa** [comment]
Oh nice. Thank you very much for doing so 👍

**Comment by LAfricain** [comment]
On Ubuntu 22.04 with czkawka 6.1.0 from the ppa, smb directories don't work:
```
############### MESSAGES(2) ###############
Properly loaded 0 cache entries.
Properly saved to file 0 cache entries.
############### ERREUR(1) ###############
Répertoires : Tous les répertoires pour rechercher des chevauchements avec des répertoires exclus
 ```

**Comment by LAfricain** [comment]
Hi,
>he resource needs to be mounted first to be able to use it.

The resource is mounted on the client.

**Comment by angeloribas01** [comment]
Hi folks,

The same error happened to me while trying to scan an external HDD with Ext4 file system. My OS is Fedora 41. 
```
############### ERRORS(1) ###############
Directories: All directories to search overlaps with excluded directorie
```s
