### ISSUE TITLE
6.1.0 can't load preview of webp image - Windows 10

### ISSUE THREAD

**Issue by onmyouji** [qarmin/czkawka#1095]
**Desktop (please complete the following information):**

- Czkawka version: 6.1.0
- OS version: Windows 10

**Bug Description**
Preview image doesn't load for webp image type. It gives an error: 
Failed to open image example.webp, reason Couldn’t recognize the image file format for file “example.webp”

**Comment by qarmin** [comment]
This worked in 5.1.0 because used image-rs image loading instead gdk-pixbuf.

I tried to use https://packages.msys2.org/package/mingw-w64-x86_64-webp-pixbuf-loader?repo=mingw64 and manually put there webp loader, but shows instead error
```
Failed to open image ⁨C:\users\vboxuser\desktop\e563993b91a5c430e96e58ae5adbe4dd.webp⁩, reason ⁨Unable to load image-loading module: C:\Users\vboxuser\Desktop\czkawka-windows-8460f29c3a729c9c1bb05c58a2c4a94759a53f30-non_heif\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-webp.dll: 'C:\Users\vboxuser\Desktop\czkawka-windows-8460f29c3a729c9c1bb05c58a2c4a94759a53f30-non_heif\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-webp.dll': Nie można odnaleźć określonego modułu.⁩
```

**Comment by conradsrc** [comment]
Also seeing this in 6.1.0 on Win11 64 Pro. I have the "WebP Extensions" installed from the Windows Store but there's just zero preview for any WebP files.

**Comment by qarmin** [comment]
App uses native gtk libraries for loading previews, so installing other apps will not fix this problem.
Krokiet - new frontent - uses rust native image loader and all tested files should show proper preview

**Comment by conradsrc** [comment]
I see, is Krokiet compile-it-yourself-only at the moment? Looks like the built releases are only the GTK version so I compiled the Krokiet version and I assume it's still very WIP.

That said, I do like the default styling of this Slint toolkit, and it fixes both this WebP issue as well as the DPI scaling issue on Windows (on the GTK version, I needed the gtk.css tweak to scale things up to a usable size), and it seems very performant. I might just keep using this version since the Image Dupe search seems to be working and that was the main thing I was using it for.

Best of luck porting everything over, I'd help if I had the time or Rust knowledge!

**Comment by softlypink** [comment]
Sorry for the noob question, but is Krokiet currently only meant to be tested by people who know how to compile? 'Cause I'm completely clueless about that, and the read-me didn't help. 😖

Thank you for your work in creating Czkawka, it's really nice.

**Comment by conradsrc** [comment]
> Sorry for the noob question, but is Krokiet currently only meant to be tested by people who know how to compile? 'Cause I'm completely clueless about that, and the read-me didn't help. 😖
> 
> Thank you for your work in creating Czkawka, it's really nice.

@softlypink I believe that's the case since it's still missing a bunch of functionality from the current release version. Someone correct me if compiled binaries for Krokiet are being hosted anywhere.

**Comment by qarmin** [comment]
Binaries for mac/linux/windows are build each time new commit is added to repo, and can be downloaded from - https://github.com/qarmin/czkawka/actions 

For now app only have 3 modes, missing a lot of features like selecting items and might be a little unstable

**Comment by vincerubinetti** [comment]
Anyone have a workaround for this? Would downgrading to an earlier version help? Any way to patch the install (without recompiling the whole thing) to get this working?
