### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by qarmin** [qarmin/czkawka#110]
Current icon is really strange, because this is my first ever created icon.

Icon should describe project

![s](https://raw.githubusercontent.com/qarmin/czkawka/master/icon.png)

**Comment by jannuary** [comment]
Potential icon metaphors:
- Cleaning - e.g. a broom cleaning up a hard drive
- Removal - e.g. a document getting shredded
- Duplicates - e.g. a file list with duplicates highlighted, stack of documents with a duplicate on its side

Let me know if you'd want to go with any of those.

**Comment by jannuary** [comment]
Low-quality paper sketch to illustrate:
![](https://i.imgur.com/XKIGzpE.jpg)

**Comment by qarmin** [comment]
Thanks, the proposals look really interesting.

I asked my colleagues what they think about it and probably the last one fits best.
However, in its current form it looks too much the file copying icon, so it would be good to add something like a X on one document or some image.


I used to think about something similar:

![AAA](https://user-images.githubusercontent.com/41945903/102336587-aa9a9f80-3f91-11eb-9991-68f82960bfeb.png)

It shows documents, music files and images (Hiccup detects duplicates for each of these types separately), but in such an icon the music file would look weird and you people wouldn't see that this program removes duplicates/files.

**Comment by jannuary** [comment]
> I asked my colleagues what they think about it and probably the last one fits best.
However, in its current form it looks too much the file copying icon, so it would be good to add something like a X on one document or some image.

I suppose the "duplicate" document could be shredded, will try to return with an icon prototype later.

**Comment by jannuary** [comment]
How's this?
![image](https://user-images.githubusercontent.com/27908024/102349952-b8bedf00-3fd6-11eb-805f-d55f167f1e5a.png)

**Comment by qarmin** [comment]
Awesome!

This icon reminds me of other Gnome icons style .

**Comment by jannuary** [comment]
@qarmin Is there anything you'd change, or is it fine to go ahead with the MR?

**Comment by qarmin** [comment]
It's fine as it is.
Remember about adding license of icon to README.md(in License field) and also in LICENSE file
