### ISSUE TITLE
delete button on GUI doesnt delete ticked files

### ISSUE THREAD

**Issue by blackfrank74** [qarmin/czkawka#1105]
### Discussed in https://github.com/qarmin/czkawka/discussions/1104

<div type='discussions-op-text'>

<sup>Originally posted by **blackfrank74** October 23, 2023</sup>
Ubuntu 22.04, app v6.0.0

I run a search for similar videos.
List of possible similarities appear.
I review and tick a file I want to delete.

![image](https://github.com/qarmin/czkawka/assets/34759786/fe413e13-2ac8-4114-b1a9-d97f43e822fc)

Step 1:
I click the delete button on the bottom righ(ish) part of the GUI.
Nothing happens.
I run a file search in the OS, I can see the 2 files being found

Troubleshooting I've tried -
1. I've exited and restarted the app - did not fix the issue
2. I've removed  and reinstalled  - did not fix the issue
3. Ive rebooted  - did not fix the issue

Any ideas?</div>

**Comment by qarmin** [comment]
This is fixed in version 6.1.0

**Comment by caj411** [comment]
I have the exact same issue and I am using version 6.1.0, so it may not be completely fixed.
I am using the Flatpak version, in Manjaro 23.04, Gnome v44.5.
My delete button is grey out and never activates when I select a file for deletion and of course it will not delete files.
Should I open a new issue?

**Comment by qarmin** [comment]
Yes,
In new bug report, please provide console output when running app via `flatpak run --env=RUST_LOG=debug com.github.qarmin.czkawk`
