### ISSUE TITLE
Document delete methods for CLI

### ISSUE THREAD

**Issue by TheQL** [qarmin/czkawka#111]
As a Mac user I only have the CLI version. I am struggling with the --delete-method parameter and was unable to find it documented. 

>     -D, --delete-method <delete-method>                     Delete method (AEN, AEO, ON, OO) [default: NONE]

explains nothing, at least not to me.

Might be a good idea to improve on that, either via "-h" or in the README.md

**Comment by qarmin** [comment]
When you type e.g. `czkawka_cli dup -h` you will get this info 
`-h, --help             Prints help information (--help will give more information)`

So `czkawka_cli dup --help` prints this 
```
    -D, --delete-method <delete-method>                     
            Methods to delete the files.
            AEN - All files except the newest,
            AEO - All files except the oldest,
            ON - Only 1 file, the newest,
            OO - Only 1 file, the oldest
            NONE - not delete files [default: NONE]
```

**Comment by TheQL** [comment]
Thanks, sorry, I overlooked that part and always only used -h. D'oh!
