### ISSUE TITLE
Czkawka fails to launch inside a path that contains 'bin'

### ISSUE THREAD

**Issue by soxhi8** [qarmin/czkawka#1133]
Apparently the failure to start happens when the application's folder resides in a path which contains a folder named 'bin'. The same crash happens with the previous release too. Weird...

_Originally posted by @varverd in https://github.com/qarmin/czkawka/issues/330#issuecomment-839030566_
            
This issue still exists with version 6.1.

**Comment by qarmin** [comment]
That is why that issue is still not closed

**Comment by soxhi8** [comment]
> That is why that issue is still not closed

Since you referenced GTK versions in the issue and had several different versions in releases since, I was not sure if it is the same issue at the core or two separate ones.
Thank you for clarifying.
