### ISSUE TITLE
Doesn't launch

### ISSUE THREAD

**Issue by drguildo** [qarmin/czkawka#1138]
**Desktop (please complete the following information):**

- Czkawka version: 6.1.0 gui
- OS version: Windows 10 Pro 22H2 19045.3693
- Terminal output[optional]: NONE!

**Bug Description**

The GUI version of czkawka doesn't launch. If I double-click the EXE, nothing happens. If I run it from the command-line, there is no output.

**Comment by qarmin** [comment]
Can you try to open this version from console? - https://github.com/qarmin/czkawka/releases/download/6.1.0/windows_czkawka_gui_console.zip 

Maybe will catch panic

**Comment by drguildo** [comment]
The CLI version doesn't panic and prints out the usage info.

**Comment by qarmin** [comment]
CLI is created with almost 100% of rust code, so it would be strange to see crash there.
GTK on windows is buggy, so the most probably this is the cause of crashes.

**Comment by drguildo** [comment]
Is there anything more I can do to narrow down the cause? I looked at the Windows build instructions, but was put off by them. 😉

**Comment by drguildo** [comment]
I had it working not too long ago, but I'm on a fresh Windows 10 install now. I tried running a 5.* version, and that didn't work either. Could it be that there's some DLL that's required that I don't have?

**Comment by qarmin** [comment]
The windows version uses a special docker image under Linux to build app, and I have not been able to create build instructions natively for windows.

Rather, the only option to collect logs is to just run the application compiled with debug options from the link I provided earlier

The application should have all the dll files in the included directory - I also had the problem before that the application was working and suddenly stopped on windows(restoring Windows image to previous date fixed problem).

Krokiet(new frontend) should not have similar problems on any OS(this type of problems force me to abandon GTK) - probably should be available in next version.

**Comment by drguildo** [comment]
If the new GUI is imminent, I guess there's no point pursuing this. Thanks for your help.

**Comment by drguildo** [comment]
I dunno if this information is useful, but in my case it seems to be related to where the application directory is located.

## windows_czkawka_gui_gtk_46.zip

 - If I run it from a subdirectory of my Windows Downloads directory, it works
 - If I run it from to a subdirectory of my C:\bin directory, it doesn't work

## windows_czkawka_gui_gtk_410.zip

 - Doesn't seem to work no matter where it's located

I guess this information isn't that useful as you seem to have come to the same conclusion as me i.e. that GTK sucks and is beyond redemption.
