### ISSUE TITLE
In Similar Videos: If a drive isn't found for one of the folder paths being scanned and a scan is started, no results are found and the cache is cleared

### ISSUE THREAD

**Issue by inger147** [qarmin/czkawka#1147]
**Desktop (please complete the following information):**

- Czkawka version: 5.1.0
- OS version: Windows 10

**Bug Description**

In Similar Videos: If a drive isn't found for one of the folder paths being scanned (e.g. if an external drive has been unplugged) and a scan is started, no results are found and the cache is cleared.  In this case it would be better to display a message that the drive isn't found and the scan is aborted, so the cache wouldn't be wiped out. (bug in 5.1.0; not sure if fixed in 6.0.0)

**Comment by qarmin** [comment]
It is expected, you can disable deleting outdated results from cache in settings

![Screenshot from 2023-11-22 22-23-14](https://github.com/qarmin/czkawka/assets/41945903/70076d7a-4aed-4655-bc87-8fabb25d762e)
