### ISSUE TITLE
Czkawka automatically closes itself when attempting to manually add a path

### ISSUE THREAD

**Issue by fi-de** [qarmin/czkawka#1165]
**Bug Description**

Hello, and thank you to everyone who has contributed to this open-source project. Unfortunately, I am encountering the same issue. When attempting to manually add a path and paste it, Czkawka automatically closes itself. This issue has been previously addressed here https://github.com/qarmin/czkawka/issues/967 , but regrettably, it remains open. Could you please look into this matter or provide an update on its resolution?

Additionally, for a future update, it would be beneficial to have the option to right-click on the path and select "all in this folder."

Thank you once again.

**System**

- Czkawka version: <!-6.1.0 cli/gui ->
- OS version: <!-Windows 11->

**Comment by qarmin** [comment]
Duplicate of https://github.com/qarmin/czkawka/issues/1044

This issue will not be fixed, because this is probably gtk bug.
New gui(still WIP) should work better on windows
