### ISSUE TITLE
Crash to desktop (Sort Filename/Foldername & directory set as reference-folder)

### ISSUE THREAD

**Issue by Tanrim80** [qarmin/czkawka#1194]
**Bug Description**

When a folder is set as reference-folder, sorting by filename or folder leads to a crash to desktop.

**Steps to reproduce:**

Set a folder to search as reference-folder and sort results by filename/foldername.

**System**

- Czkawka version: 6.1.0 gui 
- Windows 10

**Comment by lduczmal** [comment]
I have the same issue. 
On windows 10 and I tested Czkawka versions: 6.1.0 gui and 7.0.0 (gui gtk_46)

**Comment by qarmin** [comment]
Duplicate of https://github.com/qarmin/czkawka/issues/1116
