### ISSUE TITLE
Portable version doesn't start if located in a folder called "bin"

### ISSUE THREAD

**Issue by TomKranenburg** [qarmin/czkawka#1203]
**Bug Description**

**Steps to reproduce:**
Place the "Czkawka Portable" folder into a folder called "bin" on a windows system. You can no longer start it.

**System**

- Czkawka version: 6.1.0 gui
- OS version: Windows 10

**Comment by qarmin** [comment]
Duplicate of https://github.com/qarmin/czkawka/issues/330
