### ISSUE TITLE
Saving and loading "presets"

### ISSUE THREAD

**Issue by flansuse** [qarmin/czkawka#1207]
An excellent feature for this application would be the ability to save and load "presets".

This becomes more necessary when you are scanning for duplicates in **different sets of locations.**

Currently, you need to remove all paths, then re-add the new paths that you wish to scan. After you're done, you have to undo everything and re-add the previous paths if you want to do a different scan...

There's too much back-and-forth.

Instead it should look like this:
Load Preset -> "My Photo Downloads"
Load Preset -> "Family Albums"
Load Preset -> "Misc Downloads"
Load Preset -> "External Drive Documents"

(Just as a few examples.)

**Comment by qarmin** [comment]
This is already implemented in new gui.

There are 10 presets, that can be freely modified.

**Comment by flansuse** [comment]
Where in the GUI?

I cannot find this anywhere in version 6.1.0.

**Comment by qarmin** [comment]
New gui is not yet released, but is available for tests - e.g. here - https://github.com/qarmin/czkawka/actions/runs/7812583520

![image](https://github.com/qarmin/czkawka/assets/41945903/fe6823ce-609c-48d4-802a-22006e740bad)

**Comment by flansuse** [comment]
My feature requests are SO GOOD that they get implemented even before I request them! :laughing: 

It's a nice feature, glad it'll be in the next version's GUI. :smile:

**Comment by qarmin** [comment]
Krokiet is already released

**Comment by qarmin** [comment]
The gtk gui is in maintenance mode and only bugs that are critical and those that are not exclusive to this mode will be fixed(of course I am writing about myself, if someone wants to take care of this, that would be great - but it might be difficult)
