### ISSUE TITLE
`qarmin.czkawka.cli` is GUI app in WinGet repo

### ISSUE THREAD

**Issue by youk** [qarmin/czkawka#1219]
**Bug Description**
`qarmin.czkawka.cli` assumes CLI and it was like that up to 7.0.0. Since the version 7.0.0 it installs `windows_krokiet.exe` which is GUI app. Why? Is this confusion by design?

**Steps to reproduce:**
`winget upgrade -e --id qarmin.czkawka.cli`

**System**

- Czkawka/Krokiet version: 7.0.0
- OS version: Windows 10
- Installation method: `winget`

**Comment by qarmin** [comment]
This issue should be created in https://github.com/microsoft/winget-pkgs - I do not package applications under winget

This is problematic PR-  https://github.com/microsoft/winget-pkgs/pull/140053
