### ISSUE TITLE
"Presets" does not work correctly

### ISSUE THREAD

**Issue by flansuse** [qarmin/czkawka#1225]
**Summary**
"Added directories" are not saved when switching between presets

**STEPS TO REPRODUCE**
1. Select *Preset 1*
2. Add a few directories under "Included Directories"
3. Click "Save"  (it will flash the message "Saved preset 1")
4. Choose *another* preset
5. Now select *Preset 1* again
6. **The added directories are gone!**

**System**
- Krokiet version: 7.0.0
- Arch Linux
- Installation method:  Launching precompiled binary `linux_krokiet_libraw_heif`

**Comment by qarmin** [comment]
Eh...
I fixed it multiple times but looks that still I messed with some properties,

To fix this, just click "Load" an this will load proper preset.
Changing presets looks that is off by one - when you save preset 2, you can see that changes are visible on preset 1 after moving, but clicking load will fix them
