### ISSUE TITLE
M1 MAC - could not compile - build failed  (Unrecognized option: 'diagnostic-width')

### ISSUE THREAD

**Issue by jrdwiz** [qarmin/czkawka#1245]
**Bug Description**

Error when trying to compile on M1 MAC.

error: Unrecognized option: 'diagnostic-width'
error: could not compile `jpeg-decoder` (lib)
warning: build failed, waiting for other jobs to finish...

```
❯ cd ~/projects/czkawka
❯ git pull
Already up to date.
❯ cargo run --release --bin czkawka_gui
info: syncing channel updates for 'stable-aarch64-apple-darwin'
info: latest update on 2024-02-08, rust version 1.76.0 (07dca489a 2024-02-04)
info: downloading component 'rust-src'
info: installing component 'rust-src'
info: syncing channel updates for 'stable-aarch64-apple-darwin'
info: latest update on 2024-02-08, rust version 1.76.0 (07dca489a 2024-02-04)
info: component 'rust-src' is up to date
   Compiling jpeg-decoder v0.3.1
   Compiling proc-macro-error v1.0.4
   Compiling intl-memoizer v0.5.1
   Compiling objc_id v0.1.1
   Compiling hashbrown v0.13.2
   Compiling fluent-langneg v0.13.0
   Compiling intl_pluralrules v7.0.2
   Compiling blake3 v1.5.0
error: Unrecognized option: 'diagnostic-width'

error: could not compile `jpeg-decoder` (lib)
warning: build failed, waiting for other jobs to finish...
```

**System**

Czkawka version 7.0.0 GUI
OS version: MacOS Sonoma 14.3.1 ARM (23D60)
Installation method: GitHub Clone

**Comment by qarmin** [comment]
This not looks like czkawka bug, but non-official rustc/rustup.
I see similar issues:
- https://github.com/d1onys1us/stn/issues/143 
- https://github.com/xacrimon/dashmap/issues/268

Looks that someone even fixed problem - https://github.com/rust-lang/rust/issues/118385#issuecomment-1897381569

**Comment by jrdwiz** [comment]
Resolved.

Thank you. I needed to uninstall Rust, previously installed with MacPorts.
