### ISSUE TITLE
The program crashes when processing photos with incomplete filenames (e.g., ".jpeg", ".png", and likely others, untested).

### ISSUE THREAD

**Issue by LtCzr** [qarmin/czkawka#1246]
**Bug Description**
The program crashes when processing photos with incomplete filenames (e.g., ".jpeg", ".png", and likely others, untested).

**Steps to reproduce:**

1. Create a folder and place an image
2. remove the name but keep the photo type. (e.g Photo.png -> .png)
3. Run Czkawka similar images at any similarity, I chose 10.
4. Program should stop hashing at halfway and freeze.
5. Any attempt to close or stop the program will cause it to crash and turn off. 

<details>
While attempting to analyze a sizable folder, the process consistently froze at approximately the halfway point. After trial and error, I identified a file labeled ".jpeg" as the culprit. Upon further experimentation, I observed that renaming other files with incomplete labels like ".png" also replicated the crash.

</details>
```

![image - 2024-03-11T034113 291 (1)](https://github.com/qarmin/czkawka/assets/155133088/39d95d6d-e022-43f0-a0fa-c80ca9e4edf2)
![image - 2024-03-11T034115 797 (1)](https://github.com/qarmin/czkawka/assets/155133088/ae229a55-58e2-4b01-a0ba-e03bb1969062)


**System**

- Czkawka/Krokiet version: <!--  e.g. 7.0.0 cli/gui -->
- OS version: Windows 10 
- Installation method: <github zip file-->

<!-- If you use flatpak, please include the result of `flatpak info com.github.qarmin.czkawka`. -->

**Comment by qarmin** [comment]
Crash is fixed with master branch, latest binaries can be downloaded here - https://github.com/qarmin/czkawka/actions/runs/8241346135
The only problem now is that files without name are not visible in results

**Comment by hardysim** [comment]
There's no new release including this fix yet and the artifacts of the linked build are expired. Can you provide the downloads again?
