### ISSUE TITLE
krokiet compiles very long on Windows

### ISSUE THREAD

**Issue by ognevny** [qarmin/czkawka#1248]
compile-time comparisons for czkawka_gui and krokiet (https://github.com/msys2/MINGW-packages/actions/runs/8315051451/job/22752949507?pr=20369)
`Finished release [optimized] target(s) in 5m 20s` (for cli) + `Finished release [optimized] target(s) in 2m 13s`
vs.
`Finished release [optimized] target(s) in 23m 18s`
`rustc -vV`:
rustc 1.76.0 (07dca489a 2024-02-04) (Rev1, Built by MSYS2 project)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-pc-windows-gnu
release: 1.76.0
LLVM version: 17.0.6

**Comment by qarmin** [comment]
This is expected, because rust have problems with optimizing specific slint structures - https://github.com/rust-lang/rust/issues/121354

There is also workaround, but requires rust nightly - https://github.com/qarmin/czkawka/tree/master/krokiet#compilation

**Comment by ognevny** [comment]
thanks for information!

**Comment by qarmin** [comment]
Looks that slint changed generated format and now it compiles quite fast with slint 1.8
