### ISSUE TITLE
Hash Size = 40 on Krokiet v7.0.0 (Windows)

### ISSUE THREAD

**Issue by hirenshah** [qarmin/czkawka#1254]
I just ran Krokiet to test Similar Images, and noticed that the default Hash Size value shows as 40 even though that number doesn't exist in the drop down:

![image](https://github.com/qarmin/czkawka/assets/418112/52d6e436-f4dd-4452-9c54-6a56d209ed2f)

![image](https://github.com/qarmin/czkawka/assets/418112/85988c61-8fc4-4350-b3bd-3b75e97572e1)

**System**

- Krokiet version: 7.0.0 gui
- OS version:  Windows 11
- Installation method: github binaries

**Comment by qarmin** [comment]
Fixed in master
