### ISSUE TITLE
Warning when compiling czkawka_core: struct `Hamming` is never constructed

### ISSUE THREAD

**Issue by juozaspo** [qarmin/czkawka#1282]
**Bug Description**
A warning about uninitialized struct is shown when compiling `czkawka_core` as a dependency to `czkawka_cli` or `czkawka_gui` with `--release` command line parameter.
```
warning: struct `Hamming` is never constructed
  --> czkawka_core/src/similar_videos.rs:60:8
   |
60 | struct Hamming;
   |        ^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default
...
warning: `czkawka_core` (lib) generated 1 warning
```

**Steps to reproduce:**
Build `czkawka_gui` or `czkawka_cli` on Linux with one of command line commands listed: `cargo build --bin czkawka_gui --release`, `cargo build --bin czkawka_cli --release` and wait until `czkawka_core (lib)` is about to be built.

**System**

- **Czkawka/Krokiet version:** latest master (7.0.0, 2a32a52aa882f6ff52ba4d3e24a666dc2a86cf9b)
- **OS version:** Ubuntu 22.04 LTS 64 bit, rust 1.78.0
- **Installation method:**  git

**Comment by swswsws583** [comment]
I had this error too. Czkawka version: 7.0.0. I'm on macOS 14.6.

**Comment by boberx** [comment]
+

**Comment by samugarciax** [comment]
same error now

**Comment by qarmin** [comment]
Fixed via https://github.com/qarmin/czkawka/pull/1354
