### ISSUE TITLE
Czkawka seems to ignore small files

### ISSUE THREAD

**Issue by mem89de** [qarmin/czkawka#1289]
**Bug Description**
When finding duplicates, czkawka seems to ignore small files. I encountered this problem several times while deduplicating my files

**Steps to reproduce:**
I'm working on windows. To reproduce this, I created a text file and filled it with (up to) 16x1000 Characters/Bytes of content. I duplicated the file in the same folder and let czkawka do its magic. But the file where not listed as duplicates.

This problem occurs independently from method (size, hash...), hash algorithm or (pre) cache activation.

When trying bigger files (16x1024 bytes) the deduplicating works.

**Comment by Rafaguli** [comment]
Have you tried to change the minimum file size in the 'Items configuration' tab? By default, the smallest size for duplicates is 16384 bytes (16KB), but you can reduce it.

**Comment by mem89de** [comment]
> Have you tried to change the minimum file size in the 'Items configuration' tab? By default, the smallest size for duplicates is 16384 bytes (16KB), but you can reduce it.

Yes this is it. Thank you!

I was looking for some setting like that but couldn't find it. The 'items configuration' tab you mentioned was hard to see on my monitor.

**Comment by derekmueller** [comment]
Yes thank you, that was my problem.
