### ISSUE TITLE
[Feature request] Open file location/containing folder from the GUI

### ISSUE THREAD

**Issue by AndroYD84** [qarmin/czkawka#1293]
**Feature Description**
Currently, the GUI lacks a direct option to access the file location/containing folder or copy the file path to clipboard from the results, this would eliminate the need to manually open the OS file explorer and navigate to said path when further investigation is required (ie. checking if something is safe to delete), improving the overall usability.
Thank you for your kind attention to this matter.

**Comment by Topspap** [comment]
• I'm sure you can open the file location by Double Right Click. 
However it will not highlight the file for you which is sad, specially if you have hundreds of photos in same folder.

• Copy file path!! I don't think there is a way currently, as far as i know.

**Comment by AndroYD84** [comment]
> • I'm sure you can open the file location by Double Right Click.

It's actually mentioned here, I feel stupid for not seeing it. https://github.com/qarmin/czkawka/blob/master/instructions/Instruction.md#openingmanipulating-files
Although not very intuitive, no software behaves like that in my experience, it's usually a drop down menu, a clickable folder icon, a url like link, etc.

> • Copy file path!! I don't think there is a way currently, as far as i know.

This would be really useful, especially for referencing a regex rule, a small icon with the "copy" icon (similar to ⎘)

**Comment by rickycc** [comment]
with a mac trackpad, double right-click is not feasible.
