### ISSUE TITLE
czkawka, where is the exe file?

### ISSUE THREAD

**Issue by Moizevitch** [qarmin/czkawka#1294]
Hello! I even like GitHub programs. The problem is that I can't install them. I can't find the .exe file, so how do I use them? Could you kindly help me with this, please?

NOTE: I'm super lost here, I'm not used to using this forum. So I got the Label wrong, sorry!!

**Comment by ProactiveServices** [comment]
On the project page https://github.com/qarmin/czkawka there's a "Releases" pane on the right-hand summary area. Click on the "7.0.0 Latest" icon to take you to https://github.com/qarmin/czkawka/releases/tag/7.0.0 .

Scroll down through the release notes for this version to the "Assets" section. This is sometimes "collapsed" on Github release pages, which might be where you're stuck. Click on "Assets" to expand the list of files. You're probably looking for the "windows_czkawka_gui_gtk_410.zip" file that is at https://github.com/qarmin/czkawka/releases/download/7.0.0/windows_czkawka_gui_gtk_410.zip

**Comment by Moizevitch** [comment]
Thank you very much for your attention and patience in helping me.
I managed to get the program to run. Thanks!

However, I'm afraid I'm not having much luck.
It turns out that I have two videos that are different in size and name.
And the Czkawka program cannot identify them as copies.
Is this supposed to be the case, or is there a flaw there?

Once again, thank you for the help.

Em sáb., 8 de jun. de 2024 às 11:10, Adam Piggott ***@***.***>
escreveu:

**Comment by ProactiveServices** [comment]
You're welcome. It's customary to create a new bug report for a different problem, so I recommend you close this issue, and try searching the existing issues for the video search bug.

**Comment by Moizevitch** [comment]
Thanks once again!

Ok, I shall follow your advice.

Thank you.

Em seg., 10 de jun. de 2024 às 04:46, Adam Piggott ***@***.***>
escreveu:
