### ISSUE TITLE
Add tool to find similar music

### ISSUE THREAD

**Issue by qarmin** [qarmin/czkawka#132]
It would be great if Czkawka will have tool to find similar music.

It should find some sort of remixes.

**Comment by ercas** [comment]
adding to this - would be interesting to see if this could be done via the use of [AcoustIDs](https://acoustid.org/chromaprint), which is what [MusicBrainz Picard](https://picard.musicbrainz.org/) uses to match untagged music to the MusicBrainz database

**Comment by zethra** [comment]
This should be pretty easy to implement using fpcalc. I could take a crack at implementing it.

**Comment by qarmin** [comment]
For now I don't see possible Rust crate which could be used to do this
Looks that chromaprint bindings - https://crates.io/crates/chromaprint-rs needs to be compiled with ffmpeg(I don't want to use such heavy dependency, Rust only crate is preferred)

Looks that Symphonia can do it, but such feature needs to be implemented as new crate - https://github.com/pdeljanov/Symphonia/issues/50

**Comment by zethra** [comment]
This easiest way to do this would be to invoke fpcal instead of using a library. But I understand if you don't want to do it that way.

**Comment by drewlustro** [comment]
Quite interesting... could be down to help with this, although I have no production experience with rust.

**Comment by udf** [comment]
I had a look at implementing this using AcoustID fingerprints, and there's two issues that I found

1. fpcalc hangs on some m4a files (and some mp3s in my experience): [there is a (unmerged) pull request that fixes this](https://github.com/acoustid/chromaprint/pull/114)
2. The [fingerprint comparison code](https://github.com/acoustid/acoustid-server/blob/024069601aa32995cb363747a8c94c27d5d4a5e8/acoustid/data/fingerprint.py#L19) that the AcoustID server uses is implemented as a postgreql extension, which can be found here: https://github.com/acoustid/pg_acoustid/blob/102f3c870c6157704694c2ddbad3ae8ab2c7de91/acoustid_compare.c#L122 (this will need to be ported to Rust as Chromaprint doesn't export any comparison functions).
  However, the repo has no license. [Chromaprint (and fpcalc) is LGPL](https://github.com/acoustid/chromaprint/blob/master/LICENSE.md), but [the AcoustID server is MIT](https://acoustid.org/server). So it's not clear what license the comparison code is under.

**Comment by flyxyz123** [comment]
I have absolutely no knowledge about acoustic fingerprinting. But today I just found some `.afpk` files from <https://archive.org/download/audionautix-mirror> <https://archive.org/details/audionautix-mirror/>. After some search leads me to [audfprint](https://github.com/dpwe/audfprint). Which reminds me of czkawka and wonder if it has acoustic fingerprinting feature. So here I am. I also learned today there's a thing called [International Standard Recording Code](https://en.wikipedia.org/wiki/International_Standard_Recording_Code) because of <https://incompetech.com/music/royalty-free/isrc_to_name.php>. Hope these links might be a little bit useful.

**Comment by flyxyz123** [comment]
<https://github.com/dpwe/audfprint> maybe useful

**Comment by darksv** [comment]
Hello! I'm working on a pure Rust port of chromaprint https://github.com/darksv/rusty-chromaprint
There are a few things that are not implemented yet like compressing and decompressing of the fingerprints, but it should be in a somewhat usable state right now.

**Comment by qarmin** [comment]
Looks that rusty-fingerprint is the best available option: 
- small build dependencies(symphonia already was used by broken file finder)
- no runtime dependencies
- 100% rust code
- quite fast
- works(I had problems when trying to use the above tools like chromaprint)

so except maybe some performance improvements during comparing fingerprints in Czkawka and/or library side, I don't think that this application needs anything else from this library
