### ISSUE TITLE
czkawka_cli 7.0.0 failed to detect big files. Regression from czkawka 6.1.0

### ISSUE THREAD

**Issue by FredPont** [qarmin/czkawka#1331]
**czkawka_cli big, version 7.0.0 failed to detect any files**

**Steps to reproduce:**
- Download  https://github.com/qarmin/czkawka/releases/download/7.0.0/linux_czkawka_cli
- make it executable using chmod + x linux_czkawka_cli
-  run the command linux_czkawka_cli big -d /directory
-  Not found any files.

![czkawka_2024-08-23 10-39-34](https://github.com/user-attachments/assets/d42b9ea3-9ec8-4550-9ef4-ae16875d3711)

The sreenshot demonstrates that the issue is related to version 7.0.0, because czkawka 6.1.0 succeed

**Terminal output** (optional):
```
czkawka_cli big -d /directory

Results of searching ["/directory"] with excluded directories [] and excluded items []
Not found any files.
Collecting files: 3 ▪▪▪▪▪ 

```

**System**

- Czkawka-CLI version: 7.0.0
- OS version:  Ubuntu 22.04
- Installation method: github binaries

**Comment by qarmin** [comment]
Fixed by #1354, similar problem was in gui which showed all items, but not allowed to remove files
