### ISSUE TITLE
error[E0282]: type annotations needed for 'Box<_>'

### ISSUE THREAD

**Issue by thejacobsons** [qarmin/czkawka#1335]
**Bug Description**
error[E0282]: type annotations needed for 'Box<_>'

**Steps to reproduce:**
I expected to see a successful compilation after running cargo build --release from the krokiet directory. What I saw is below in 'Terminal output'. I also have the same problem with czkawka.

**Terminal output**:
![krokiet_error](https://github.com/user-attachments/assets/9c29d10d-12ca-4fc2-8e7e-93df097e763c)

<details>
<summary>Debug log</summary>

I am unsure which log is needed here.

</details>

**System**
- Czkawka/Krokiet version: 7.0.0 gui
- OS version: Mac 14.6.1 Intel
- Installation method: github binaries

**Comment by qarmin** [comment]
Fixed by #1354
