### ISSUE TITLE
libgtk-4 requirement for Linux GUI doesn't exist

### ISSUE THREAD

**Issue by fire-eggs** [qarmin/czkawka#1340]
**Bug Description**
The requirements for the Linux GUI state to install `libgtk-4`. No such package exists. The following worked for me:

`sudo apt install libgtk-4-bin`

**Steps to reproduce:**

**Terminal output** (optional):
```
kevin@BRIX2:~/proj/booru$ sudo apt install libgtk-4 libheif libraw ffmpeg -y
[sudo] password for kevin:      
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libgtk-4
E: Unable to locate package libheif
E: Unable to locate package libraw
```
**System**

- Czkawka/Krokiet version: 7.0.0 gui
- OS version: Linux Mint 21.3
- Installation method: github binaries

**Comment by qarmin** [comment]
Updated instruction with correct package names
