### ISSUE TITLE
error: could not compile `time` (lib) due to 1 previous error

### ISSUE THREAD

**Issue by becauseim** [qarmin/czkawka#1345]
macOS 15.0 (24A335)
Hi! I’m trying to compile the application from GitHub for the first time. Before that I always downloaded .dmg images. 

I have executed all the commands from README.md in turn and i've got an error at the last step.
[Terminal Saved Output.txt](https://github.com/user-attachments/files/17028407/Terminal.Saved.Output.txt) What did i do wrong?

![Screenshot 2024-09-17 at 15 16 15](https://github.com/user-attachments/assets/2cd79383-3149-4cd4-914e-c842d2e1877b)

**Comment by RayOfLight1** [comment]
This could be solved if this project would require time-0.3.36 instead of time-0.3.34 according to: https://github.com/time-rs/time/issues/693

**Comment by RayOfLight1** [comment]
@qarmin Please replace "0.3.34" from https://github.com/qarmin/czkawka/blob/2a32a52aa882f6ff52ba4d3e24a666dc2a86cf9b/Cargo.lock#L5571

with "0.3.36" and this bug should get solved ;)
