### ISSUE TITLE
Snap package doesn't have .desktop file

### ISSUE THREAD

**Issue by pizzadude** [qarmin/czkawka#135]
Snap package doesn't have a .desktop file, so the user will have to create one themselves in order to launch from the menu or launch from the terminal.

**Comment by iGadget** [comment]
Besides missing a .desktop file, it's also missing an app icon. @qarmin I'm sure you're aware of this, but just to be certain - here's a link describing how it should work with Snap: https://snapcraft.io/docs/desktop-menu-icon-support

**Comment by qarmin** [comment]
File was added  a while ago
