### ISSUE TITLE
Make this project releases page less confusing

### ISSUE THREAD

**Issue by stderr-to-devnull** [qarmin/czkawka#1379]
1. What is the difference between:
  a. [windows_czkawka_gui_410.zip](https://github.com/qarmin/czkawka/releases/download/8.0.0/windows_czkawka_gui_410.zip)
  b. [windows_czkawka_gui_46.zip](https://github.com/qarmin/czkawka/releases/download/8.0.0/windows_czkawka_gui_46.zip)
  c. [windows_czkawka_gui_46_console.zip](https://github.com/qarmin/czkawka/releases/download/8.0.0/windows_czkawka_gui_46_console.zip)

2. What is the difference between:
  a. [windows_krokiet_gui_linversion.exe](https://github.com/qarmin/czkawka/releases/download/8.0.0/windows_krokiet_gui_linversion.exe)
  b. [windows_krokiet_gui_linversion_console.exe](https://github.com/qarmin/czkawka/releases/download/8.0.0/windows_krokiet_gui_linversion_console.exe)
  c. [windows_krokiet_gui_winversion.exe](https://github.com/qarmin/czkawka/releases/download/8.0.0/windows_krokiet_gui_winversion.exe)

3. Why don't you explain the above anywhere?
4. How do you expect people to know and understand which version to download?

**Comment by qarmin** [comment]
![image](https://github.com/user-attachments/assets/d4c48be6-97ba-440b-bc7d-0d075184964b)

**Comment by stderr-to-devnull** [comment]
The problem is that you put that legend after posting changelogs of all versions and a VirusTotal report, making it very hard to see. It might make sense to you but not to others, as evidenced by the several questions asked by people on the web, being confused as I was.

A more sensible approach would be to put the legend at the very top and actually change the heading to something that makes more sense like `differences between releases`. The best approach would be to split all versions into groups with separate headings, like you did with the changelog and then have a descriptive paragraph for each group, describing the particularities.

Furthermore, the legend lacks explanation on several points. Example: why do you keep providing two GTK GUI versions? Are there (dis)advantages of using one over the other? Visual/performance differences?
