### ISSUE TITLE
Deadlock Crash

### ISSUE THREAD

**Issue by expphoto** [qarmin/czkawka#1390]
Running on OSX Sonoma via CMD and getting Deadlock Error 11, it never completes.

**Comment by qarmin** [comment]
Without more information like:
- version
- app used
- logs from command line
- maybe screenshots(I never seen such error before)
- installation method - self compiled/from brew etc.

 I cannot help

**Comment by expphoto** [comment]
Oops. Sorry. Does this help?

![deadlock](https://github.com/user-attachments/assets/ef8450a6-e8db-4b1c-8733-0496be36d6a4)

Compiled from Brew for M1

Command I ran: cargo run --release --bin czkawka_cli dup --directories /Users/recoveryaccount --excluded-directories /Users/recoveryaccount/Library,/Users/recoveryaccount/Applications

Version 8.0.0 is what shows when I run the man page.

**Comment by expphoto** [comment]
Any update? :)

**Comment by qarmin** [comment]
Such an error usually indicates a problem with the program (https://developer.apple.com/documentation/system/errno/deadlock), but in my opinion, this might be an issue with the system or its configuration, as you are the first person to ever report it.

It looks like this may be a problem with OneDrive—there are even potential fixes mentioned in some threads.

https://www.reddit.com/r/Arqbackup/comments/t9eggc/solution_to_resource_deadlock_avoided_error/
https://discussions.apple.com/thread/253628750?sortBy=rank

**Comment by qarmin** [comment]
Problem happens in this function 

https://github.com/qarmin/czkawka/blob/1c99adb43468871e3b9a7eb7bb394859ddb542bb/czkawka_core/src/duplicate.rs#L1284-L1307

0 locks or similar things are used here - so 99% chance that this is not problem of this app

**Comment by expphoto** [comment]
Thank you. Was wondering if this was on the comp end.
