### ISSUE TITLE
How to Install Czkawka

### ISSUE THREAD

**Issue by gokco7** [qarmin/czkawka#1397]
I'm not a Github user and I couldn't figure out how to install it. One I download didn't have .exe file and the another 2 I downloaded for Windows had .exe files but both didn't run when I clicked on them. Can anybody help?

**Comment by PhoenixIV** [comment]
Hi @gokco7 ,

I am glad you tried multiple ways.

I am writing to you as a new user myself. The ease of download is indeed not as simple as it could be. Multiple packages for the same platform, file names that have to be looked up in a table. This could be improved.

What worked for me was going with the  `windows_czkawka_gui_46.zip` package. Extract the contents to a folder and then start `czkawka_gui.exe`.

Feel free to run a virus check on the folder beforehand. It cannot guarantee safety, of course, but it is good to be aware.

I could not explain to you why the "410" version did not work in my case.

**Comment by gokco7** [comment]
Hey, 
Sincerely thank you for your kind response and help, I really appreciate your effort. I tried "windows_czkawka_gui_46.zip" and it worked for me too.
