### ISSUE TITLE
Fails to detect duplicate 

### ISSUE THREAD

**Issue by t8ja** [qarmin/czkawka#1398]
**Steps to reproduce:**
An example https://ibb.co/ZzLbGn2  of a file that doesn't get detected. 
I believe it happened with other extensions also, but images appear to be most affected 

- Czkawka/Krokiet version: 8.0.0 gui 
-  OS version: Arch 
- Installation method:  aur

**Comment by qarmin** [comment]
16 KB is default minimal size for duplicates - you need to change that value

**Comment by t8ja** [comment]
> 16 KB is default minimal size for duplicates - you need to change that value

Damn, I should've saved more examples. Not sure if all were this small. 
I'll test this and report back.
