### ISSUE TITLE
Support for light theme

### ISSUE THREAD

**Issue by qarmin** [qarmin/czkawka#14]
For now Czkawka only support dark theme.
Now it looks bad with white theme:
![Zrzut ekranu z 2020-09-29 23-04-33](https://user-images.githubusercontent.com/41945903/94616345-411bc680-02a9-11eb-90a4-e7a66a3e9f09.png)

**Comment by qarmin** [comment]
In f05bce615ac73ca5fced3081f84cd1600e77b324 removed all occurrences of dark text of dark background.
Only ListStore with "headers"(in duplicate tab) must use two different colors, so I decided to use dark colors with white text
For now it looks that, but still I think that this should be fixed in more elegant way.
![Zrzut ekranu z 2020-10-01 16-04-35](https://user-images.githubusercontent.com/41945903/94819966-332c8980-0400-11eb-96a9-7f58da184dc4.png)

**Comment by qarmin** [comment]
Sadly for now Czkawka supports only Yaru-dark theme
I don't have time to fight with GTK limitations (cannot get theme colors from code or set header row(with a little different color) in list store)
I would really appreciate any help in fixing this issues.

**Comment by Gravityzwell** [comment]
Can there be an option, in the GUI or the config, light_theme=1 and reverse the above. In the list, white background, black text. 
Even better, have some option to specify list background and foreground colors, but I'd take the first option gladly.
I would have done this for myself but I can't get it to compile on Windows.

**Comment by Gravityzwell** [comment]
To follow up: I was able to compile for Windows using Msys2. I had to intall several dependencies (in Msys2). Then change the header, text, and background colors for the grid. Looks very nice! Thanks for the great work.

**Comment by qarmin** [comment]
Krokiet already support white theme
