### ISSUE TITLE
Windows Long Path Support

### ISSUE THREAD

**Issue by phhowe17** [qarmin/czkawka#147]
I have a lot of very deep directories for my book collection. My first scan returned "Unable to check hash of file" errors for paths like these. The longest here is 278 characters.

E:\calibre (work in progress)\export\_g\Gerrold, David & Carey, Diane & Moore, Ronald D. & E'chevarria, Rene & Behr, Ira S_\Star Trek_ Deep Space Nine Book 22_ Trials And Tribble-ations - Gerrold, David & Carey, Diane & Moore, Ronald D. & E'chevarria, Rene & Behr, Ira S_.epub

E:\calibre (work in progress)\export\_s\Smith, Dean Wesley & Ordover, John J. & Blocsin, Elisa & Kassin, Elisa J. & Johnson, Jim\Star Trek_ Strange New Worlds VII (Star Trek_ Strange New Worlds ) - Smithn J. & Block, Paula M. & Kassin, Elisa & Kassin, Elisa J. & Johnson, Jim.mobi

E:\calibre (work in progress)\export\_m\Martin, George R. R. & Harper, Leanne C. & Shiner, Lewinodgrass, Melinda M. & Simons, Walton & Miller, John J_\Jokers Wild - Martin, George R. R. & Harper, Leanne C. & Shinrd & Snodgrass, Melinda M. & Simons, Walton & Miller, John J_.mobi

**Comment by qarmin** [comment]
Can you check if it works in Czkawka 2.2.0?
I'm almost sure that this issue was caused not by long path, but using comma in name and should be fixed now

**Comment by phhowe17** [comment]
I believe this is resolved. Thanks.
