### ISSUE TITLE
Maybe finding movie duplicates?

### ISSUE THREAD

**Issue by qarmin** [qarmin/czkawka#148]

**Comment by frosty939** [comment]
by 'movie duplicates' do you mean video files with similar content, but maybe a different resolution or with some content cut out or something? i'd love to see that sort of thing added.

dialing in recognition would probably be pretty difficult.. like if two files are the exact same video, but one has a watermark or something. would still be an amazing feature, even if it didn't catch everything

**Comment by qarmin** [comment]
Already exists an app to find duplicated movies(different resolution, colours or watermarks) - https://github.com/0x90d/videoduplicatefinder - but it is written i.n C# and also is dependant on FFmpeg library

From comments from - https://www.reddit.com/r/DataHoarder/comments/de0m4x/video_duplicate_finder_2_find_duplicate_videos/ it just take a picture after x minutes and compare it with others screenshoots.

**Comment by frosty939** [comment]
oh snap, i had actually been picturing something very similar to what was done in https://github.com/0x90d/videoduplicatefinder 

i still think it'd be a cool thing to include in this app, having a single app for all your duplicate file needs would be really nice. but i can see how it might not feel worth it when something else is already doing it lol

oh! and thank you for all your great work :D

**Comment by qarmin** [comment]
Looks that https://github.com/Farmadupe/vid_dup_finder_lib may be good enough, so I will see if this is possible to integrate this to build system
