### ISSUE TITLE
Install for Debian 10 is incorrect

### ISSUE THREAD

**Issue by SimplicityGuy** [qarmin/czkawka#151]
For Debian 10 (buster), the installation instructions are incorrect. Your instructions state:
```
sudo apt install cargo libgtk-dev
```

However, this should be:
```
sudo apt install cargo libgtkd-3-dev
```

**Comment by SimplicityGuy** [comment]
Seems like the better option for Debian 10 is to have the audience install rust from `https://www.rust-lang.org/tools/install` which yields:
```
d9d8ad8b32e6:/# cargo --version
cargo 1.48.0 (65cbdd2dc 2020-10-14)
d9d8ad8b32e6:/# rustc --version
rustc 1.48.0 (7eac88abb 2020-11-16)
```
However, in order to install czkawka, the user also needs to install `curl`, `build-essential`, `librust-glib-sys-dev`, `librust-cairo-sys-rs-dev`, `librust-pango-sys-dev`, `librust-atk-sys-dev`, `librust-gdk-pixbuf-sys-dev`, `librust-gdk-sys-dev`.

**Comment by qarmin** [comment]
I installed Debian 10 on virtual machine and added steps to install  rust(with rustup) and curl(I don't know why debian doesn't provide such a basic tool by default)
I doesn't need to have `librust-glib-sys-dev librust-cairo-sys-rs-dev librust-pango-sys-dev librust-atk-sys-dev librust-gdk-pixbuf-sys-dev librust-gdk-sys-dev` to compile and install Czkawka.
Updated instruction - https://github.com/qarmin/czkawka#debianubuntu
