### ISSUE TITLE
Support UNC paths

### ISSUE THREAD

**Issue by JohnDelisle** [qarmin/czkawka#152]
Your Windows app uses its own dialog-box for specifying sources, and does not permit us to enter a UNC path like \\server\share\directory

**Comment by qarmin** [comment]
As workaround you can try to save configuration, and manually modify `C:\Users\Alice\AppData\Roaming\Qarmin\Czkawka\config\czkawka_gui_config.txt`

I'm working on ability to manually specific new directories by writing it to special dialog

**Comment by JohnDelisle** [comment]
cool stuff.  thanks!
