### ISSUE TITLE
Activate Github Sponsors

### ISSUE THREAD

**Issue by thibaultmol** [qarmin/czkawka#156]
https://github.com/sponsors

(doesn't have to be github sponsors, can be 3rd party donation systems like Patreon, Librepay etc. 
But don't see a reason not to enable the actual github sponsors system)
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

**Comment by qarmin** [comment]
Already done
