### ISSUE TITLE
Being able to delete files with SUPR button, not only with the mouse

### ISSUE THREAD

**Issue by Jakeukalane** [qarmin/czkawka#163]
This function will allow to speed up the deletion process.

**Comment by qarmin** [comment]
What is exactly SUPR button?
It means super key or else?

I merged today support for deleting files with Delete key - https://github.com/qarmin/czkawka/pull/159 and I think that this is the best button for this job.

**Comment by Jakeukalane** [comment]
Oh, I didn't know the name was different in English sorry. Yes, the delete button.
