### ISSUE TITLE
Hash window GUI fix

### ISSUE THREAD

**Issue by goodboi69** [qarmin/czkawka#172]
Issue 1: There are no commas for the numbering format.
Issue 2: "image" should say "file"/"files".

![Untitled-1](https://user-images.githubusercontent.com/43517545/103414516-490b3100-4b4c-11eb-896c-5144c66348c4.jpg)

**Comment by qarmin** [comment]
This text depends on translations and can be changed on crowdin(looks that it was changed in meantime).
