### ISSUE TITLE
Change checkboxes

### ISSUE THREAD

**Issue by goodboi69** [qarmin/czkawka#174]
The checkbox system is not very good looking. Please consider changing them to normal checkboxes.

![GIF 12-31-2020 3-15-14 PM](https://user-images.githubusercontent.com/43517545/103424665-90f57c80-4b7b-11eb-8753-ee8ca3a9b45e.gif)

**Comment by qarmin** [comment]
The problem is with current Windows theme, we can fill issue with current theme or just change theme to other(must be M)

**Comment by qarmin** [comment]
This is already fixed
