### ISSUE TITLE
Minimize scan window

### ISSUE THREAD

**Issue by goodboi69** [qarmin/czkawka#177]
Please add a Minimize button to the scanning window. It's annoying that I cannot do that.

![Untitled-1](https://user-images.githubusercontent.com/43517545/103426425-84772100-4b87-11eb-816e-e56366f54594.jpg)

**Comment by siodor** [comment]
FYI, on Linux (KDE Desktop) the scan window does have all the buttons
![grafik](https://user-images.githubusercontent.com/38102740/104126509-3fa87280-535d-11eb-82e0-f47fe3bcb8b5.png)

**Comment by goodboi69** [comment]
I am on 2.1.0 on Win10 and they aren't there.
