### ISSUE TITLE
extra confirmation when trying to delete all copies of a file

### ISSUE THREAD

**Issue by onemoz** [qarmin/czkawka#182]
Currently, we can use the `show confirm dialog when deleting` : each time we will try to delete a file, this will prompt for a confirmation box. 

Having a second option would be great to have a confirm dialog only in the case we select *all* the copies of a specific file, to avoid deleting all of them in case they all match a `select custom`.

**Comment by endolith** [comment]
Or better yet, allow us to just ignore those match groups and delete the rest:

![](https://user-images.githubusercontent.com/58611/109211581-6a6b5080-777c-11eb-9cd6-9ca3584b6943.png)

Or push a button to unselect all groups which have all files unselected, while keeping the rest selected.

Then we don't have to manually remove each group that has all files selected.
