### ISSUE TITLE
Pressing the “Delete” button doesn't trigger a warning

### ISSUE THREAD

**Issue by alexislefebvre** [qarmin/czkawka#187]
Thanks for this great software!

I'm using the “Similar Images” with the 2.1.0 version, on Linux

If I use the “Delete” button in the app, there is a dialog:

> ![image](https://user-images.githubusercontent.com/2071331/104110280-8606be80-52d6-11eb-85b0-9f1aa86c1dc1.png)

But If I use the `Delete` key of my keyboard, there is no dialog.

Could we have the same warning in both cases?

**Comment by dandv** [comment]
I've also run into this, and was surprised to see nothing happen after I pressed the <kbd>Delete</kbd> key.

If it's intentional that pressing <kbd>Delete</kbd> should not prompt for confirmation, then it could display a confirmation message, like "File xxx has been deleted".
