### ISSUE TITLE
Use external cli argument parser

### ISSUE THREAD

**Issue by qarmin** [qarmin/czkawka#2]
For now arguments are parsed manually, but some people find hard to read my code, so maybe better idea is to use some lightweight argument parser.

Some of possible libraries:
- https://crates.io/crates/gumdrop
- https://crates.io/crates/structopt

**Comment by MeirKlemp** [comment]
I would like to work on it.
Can I be assigned to it?

**Comment by sseering** [comment]
While doing this one should also change 

`--v / --version` to `-v / --version`

and 

`--h / --help` to `-h / --help`.

The double dashes are kinda a bug/misfeature that is the result of the current implementation of the argv parser.

**Comment by qarmin** [comment]
Fixed by #37
