### ISSUE TITLE
Better way to mark a CellRenderer as disabled

### ISSUE THREAD

**Issue by leinardi** [qarmin/czkawka#231]
Hi, I found your app looking on how to disable a line/row/cell on a TreeStore and ending up on this discussion:
https://discourse.gnome.org/t/how-to-disable-row-and-change-it-color-in-treeview-liststore/4303

I saw that you were suggested to change the colors of the cell, which might seem a good idea, until you try the app on a theme different than the one where it was developed.

For example, you made the app look good on a Dark theme, but the colors you pick do not fit that well a Light theme:
![Schermata da 2021-01-27 15-11-44](https://user-images.githubusercontent.com/273338/106002944-fae93f00-60b1-11eb-84fa-92cc6f4bc287.png)

I just want to suggest that, instead of changing the color of the cells, you can simply mark them as non [sensitive](https://developer.gnome.org/gtk3/stable/GtkCellRenderer.html#GtkCellRenderer--sensitive). They will look disabled (check the Val column):

![image](https://user-images.githubusercontent.com/273338/106003205-44398e80-60b2-11eb-8b2a-0aacc5aafa30.png)

This approach should work fine on any theme, no matter if Light or Dark.

**Comment by qarmin** [comment]
Difference between sensitive and non sensitive fields are too subtle to clearly see where is header and where are data.
I think that the best solution is to get current theme colour(I'm not sure if it is possible) and set it for data fields and later add e.g. #333333 to it to get darker headers.

This won't work well when changing theme in fly, but still should look better than now.

**Comment by leinardi** [comment]
Yeah, I have the same issue. I if you find a way to reliably get colors from the user theme, ping me :)
