### ISSUE TITLE
Add notion of reference directory

### ISSUE THREAD

**Issue by nirvdrum** [qarmin/czkawka#232]
I'm trying to clear out space on an SD card that had photos and videos on it. Over the years I've imported data from it, but the importing tool didn't clear things off after the import. So, I've ended up with duplicates on subsequent imports. It's great that those are found, too, since I ultimately would like to get rid of all the duplicates, but it makes it hard to clear off the SD card when the results are mixed in with duplicates found for file not on the SD card.

It would be helpful if I could annotate one directory as a reference or source directory and have duplicates only reported if they're also present in the filesystem tree rooted at the referenced directory.

**Comment by ca-boh** [comment]
Yep. Czkawka is incresibly good. Adding reference folders - duplicates inside those reference folders remain "unselected" and duplicates in any other folders are "selected" - will make Czkawka duplicate selection really useful. Currently, selecting the "correct" duplicate to delete is really limited. 

(Note: this reference folder functionality exists in software like dupeGuru.)

**Comment by endolith** [comment]
This is different from https://github.com/qarmin/czkawka/issues/233 ?

**Comment by nirvdrum** [comment]
Yes. This issue is about saying if you're searching multiple sources, only report duplicates if they are found in the referenced source. As @ca-boh noted, dupeGuru has similar functionality. #233 is about once those results are detected, allow me to show the duplicate list for only one of the sources.

I don't know if this helps, but say I'm searching for duplicates in X, Y, and Z. Currently, this project reports all duplicates in (X, Y), (X, Z), and (Y, Z) (and by extension (X, Y, Z)). The notion of a reference source would allow you to say only report duplicates if they appear in reference X, reducing the above list to (X, Y) and (X, Z).

Issue #233 would then allow you filter the list of results so you can only see the duplicates from X, Y, or Z. Given how easy it is to delete files from the application, such a filter would help prevent you from deleting files from the wrong source.
