### ISSUE TITLE
Binaries for 2.3.2?

### ISSUE THREAD

**Issue by alexislefebvre** [qarmin/czkawka#235]
Could you please publish binaries for [2.3.2](https://github.com/qarmin/czkawka/releases/tag/2.3.2)?

I would like to try the image selection with keyboard.

**Comment by qarmin** [comment]
Binaries for each commit should be available here(at the top should contains every single patch) - https://github.com/qarmin/czkawka/actions?query=branch%3Amaster
You need only to choose your os and download artifacts from build 
![Screenshot from 2021-01-31 12-29-38](https://user-images.githubusercontent.com/41945903/106382485-36d91880-63c0-11eb-9950-bfa4ed67391c.png)

**Comment by alexislefebvre** [comment]
Thanks! They are here for Linux: https://github.com/qarmin/czkawka/actions/runs/523273062#artifacts
