### ISSUE TITLE
How do you add the update to the Windows GUI folder?

### ISSUE THREAD

**Issue by goodboi69** [qarmin/czkawka#238]
How do you add the updates to the folder with for the Windows GUI? I've read the README but I don't understand. Please help.

**Comment by alexislefebvre** [comment]
Are you trying to update the app? 

1. Go on the Windows Actions page: https://github.com/qarmin/czkawka/actions?query=workflow%3A%22%F0%9F%8F%81+Windows%22
2. Click on the first workflow
3. Click on the number under “Artifacts”
4. Download the last version

The last one is here: https://github.com/qarmin/czkawka/actions/runs/525670761#artifacts

**Comment by goodboi69** [comment]
That doesn't work. It fails in Firefox and I get a 404 in Chrome.

**Comment by qarmin** [comment]
For now there is no method to automatically update package.
The easiest method is to "update" app to latest version is download the latest available version(official or from github artifacts), unpack it and just use it(config shouldn't change too much when updating Czkawka to newer version).

I think that the best idea would be put Czkawka into Chocolatey, so it will behave on Windows exactly as Snap or Flatpak on Linux with really easy updating.
