### ISSUE TITLE
Similar images: identical images are shown with “Very High” similarity

### ISSUE THREAD

**Issue by alexislefebvre** [qarmin/czkawka#244]
When I copy and paste an image then scan with czkawka, the two images are recognized as similar with “Very High” similarity.

I think it should be “Identical” or something like that in this case.

**Comment by alexislefebvre** [comment]
Actually it's simpler to use the “Duplicate files” in this case. Feel free to close the issue.

**Comment by qarmin** [comment]
Indeed, duplicate files finder is simpler and a lot of faster method to find same(bit to bit) images.
Of course it is possible to add additional step with hashing to similar image finder but it would make an already too long search longer
