### ISSUE TITLE
czkawka_cli needs libasound.so.2

### ISSUE THREAD

**Issue by Sbgodin** [qarmin/czkawka#247]
Hi all!

I compiled Czkawka without problem. Both graphical and command line version work on my computer.
I copied czkawka_cli on a Synology appliance. It said:
```
$ ./czkawka_cli
./czkawka_cli: error while loading shared libraries: libasound.so.2: cannot open shared object file: No such file or directory

```
Maybe there should not be any dependence to a library related to sound? Indeed I intended to copy `czkawka_cli` as a standalone executable.

git revision : ea474c2af09630af25eb374051e6a0fa3acce72f

**Comment by qarmin** [comment]
Upstream issue about ability to disable playing audio feature - https://github.com/RustAudio/rodio/issues/349
