### ISSUE TITLE
Temporary files/folder enhancements 

### ISSUE THREAD

**Issue by qarmin** [qarmin/czkawka#25]
For now temporary files finder finds only files which ends with some extensions
https://github.com/qarmin/czkawka/blob/d3652c1e8629abfafc42a7f104eb0c63aeca194a/czkawka_core/src/temporary.rs#L195

- [ ] - Add more temporary files to check
- [ ] - Add support for removing folders like `~/home/cache` available from GUI

**Comment by qarmin** [comment]
This tool is supposed to do only basic remove of temporary files,
Bleachbit is recommended for advanced searching

**Comment by amano-takahisa** [comment]
I respect your decision, but that feature is very attractive to me😃
