### ISSUE TITLE
How do I add a language translation?

### ISSUE THREAD

**Issue by LJason77** [qarmin/czkawka#251]
I have now translated the item translatable="yes" in the czkawka.glade file into Chinese.
How should I merge the translations into the upstream repository?

**Comment by qarmin** [comment]
For now Czkawka support only English language.
In future I want to add support for po files with will allow to translate specific texts, but for now I don't know how to add this feature into build system. 

This is example in Fractal how it is handle there - https://gitlab.gnome.org/GNOME/fractal/-/blob/master/fractal-gtk/po/pl.po

**Comment by LJason77** [comment]
Ok, the translation file is here https://github.com/LJason77/czkawka/commit/319abb9e3011b4e29b6aac55e54345a5d13021d6.
They can be merged into the repository when needed.

**Comment by err931** [comment]
[How to bind a text domain to a local folder for gettext under GTK3](https://stackoverflow.com/questions/10094335/how-to-bind-a-text-domain-to-a-local-folder-for-gettext-under-gtk3)

The above post is about supporting multiple languages in Python, but you can use [gettext-rs](https://crates.io/crates/gettext-rs), to do the same thing.
There is also a struct called [TextDomain](https://docs.rs/gettext-rs/0.6.0/gettextrs/struct.TextDomain.html).

I hope this will help.

**Comment by LAfricain** [comment]
If you add the support for translation I will do it for French.

**Comment by qarmin** [comment]
Finally I managed how to use translations in Rust and GTK, so I think that in ~1 week I will be able merge translation support to Czkawka.

**Comment by qarmin** [comment]
Translation support is merged.
Base strings from English are available in `i18n/en` folder.
So if anyone want to create translation, then adding translated `i18n/en` to any other language would be enough, because I can write rest logic in app to be able to choose newly created translation.
