### ISSUE TITLE
Add button to clear cache

### ISSUE THREAD

**Issue by qarmin** [qarmin/czkawka#257]

**Comment by FelixKainz** [comment]
How can someone do this manually?
And why would one want to?

**Comment by qarmin** [comment]
Cache files are available here
```
Linux - /home/username/.cache/czkawka
Mac - /Users/Username/Library/Caches/pl.Qarmin.Czkawka
Windows - C:\Users\Username\AppData\Local\Qarmin\Czkawka\cache
```

They can be removed when:
- In cache there is available hundred of thousands of records, but someone just want to scan e.g. 20 files. Czkawka needs to load cache, check which files are already cached and at the end merge all results and save it to cache. This may take more time that scanning for files. Czkawka automatically remove files from cache when they don't exists, so this is quite rarely.(This can also be resolved by disabling cache which I implemented here - https://github.com/qarmin/czkawka/commit/17f97bd958da5fbbc7aaf4010ec719710a52c24e)
- Czkawka updated and changed a little how hashes are computed, so records of same file may be different across different versions and  can produce wrong results.(This never happens in past, but may in future)

You can also backup cache, to not get lost data about images on external disk(when disk will be unplugged, running Czkawka will purge entries about non existent files).

**Comment by FelixKainz** [comment]
I see, thanks for the explanation!

**Comment by qarmin** [comment]
Buttons to clear cache from outdated results are implemented.
Also buttons to open folders with cache to be able to delete or modify them manually, also exists.
