### ISSUE TITLE
Czkawka GUI - Windows Title Buttons went missing after v2.4.0

### ISSUE THREAD

**Issue by siodor** [qarmin/czkawka#289]
With release v2.3.0 the window title buttons are all present, with v2.4.0 and v3.0.0 they went missing.

v2.3.0
![grafik](https://user-images.githubusercontent.com/38102740/111020750-65d3a880-83c8-11eb-95e1-bf21865ac0ff.png)

v2.4.0
![grafik](https://user-images.githubusercontent.com/38102740/111020760-7a17a580-83c8-11eb-9dce-be6cde8f3756.png)

v3.0.0
![grafik](https://user-images.githubusercontent.com/38102740/111020775-8dc30c00-83c8-11eb-8798-1492cd810524.png)

When I click in the approximate area where the close, maximize, minimize buttons should be the action still gets executed but for example the "stay always on top" and "stay always on bottom" buttons are missing too and there's no action for those.

Interestingly the options dialogue still has all his buttons
![grafik](https://user-images.githubusercontent.com/38102740/111020828-d5499800-83c8-11eb-8b86-e85eab033c25.png)

**Comment by siodor** [comment]
My OS information
![grafik](https://user-images.githubusercontent.com/38102740/111020963-a7188800-83c9-11eb-8516-54cc5057d38f.png)

**Comment by qarmin** [comment]
I checked several times Czkawka with KDE Plasma on Ubuntu and looks that buttons are visible all the time
