### ISSUE TITLE
Similar images search - missing support for HEIC/HEIF

### ISSUE THREAD

**Issue by nikielmcn** [qarmin/czkawka#305]
As many modern phone cameras gain ability to save taken photos to HEIC/HEIF format, and sometimes during sharing or importing, phones convert whis files to JPG, user can finish with the same duplicated photo - one JPG, and original in HEIF/HEIC file.

In current release version (3.0.0 - windows) Czkawka does not take HEIF/HEIC files to sililar images comparisions.

in attachment sample JPG and HEIC files
[HEIC-JPG.zip](https://github.com/qarmin/czkawka/files/6227488/HEIC-JPG.zip)

**Comment by qarmin** [comment]
Czkawka depends on Image-rs features.
https://github.com/image-rs/image/issues/1375 is issue to track this support.
