### ISSUE TITLE
Can compile and install for first time, but can't compile during update

### ISSUE THREAD

**Issue by Alsan** [qarmin/czkawka#310]
Please see the screenshot for error message.

![Screenshot_2021-04-06-57_2142x919](https://user-images.githubusercontent.com/217947/113723368-df3e8c80-9723-11eb-8f72-a55295c1116b.png)

**Comment by alexislefebvre** [comment]
Please put the error message in plain text, it's easier to read and search in the future.

**Comment by qarmin** [comment]
For me looks that something corrupted Czkawka thirdparty libraries(managed directly by cargo)

Try to remove `/home/user.cargo/registry`(this clear cache of packages downloaded by cargo) 
and `target` folder inside Czkawka directory(not needed if using `cargo install czkawka` or `cargo install --git https://github/czkawka etc.`)

**Comment by Alsan** [comment]
I'll try it layter today, thanks.

**Comment by qarmin** [comment]
Closing since this looks at the local build problem,
Probably also upgrading Rust should help, because this would purge all compiler cache
