### ISSUE TITLE
File selection by original directory

### ISSUE THREAD

**Issue by frisno-b** [qarmin/czkawka#313]
The ability to mark all duplicates that have a candidate in /this/* directory
leaving all other duplicates unmarked.

When I start removing duplicates I always start by removing files that I already store in a sorted, more permanent places, like /music /pictures etc.

The ability to define these directories as containing _original versions_ would swiftly get the bulk out of the way leaving only duplicates that are all elsewhere to deal with.

**Comment by alexislefebvre** [comment]
It looks close to this idea: #232

**Comment by frisno-b** [comment]
Yes almost. That seems to be about the finding, I need it as a filter.

With all duplicates found/reported and the ability to select/mark based on their presence in any/all predefined directories makes it easier to just carry on after the bulk is removed this way.

The ability to define more than one directory would be nice.

Writing this now I can se the need to point to an "origin directory" on the fly and maybe that will please more users rather than defining them beforehand

This could also help in defining the originals in the creation of links.

**Comment by scrapix** [comment]
Agree, this is a crucial feature for cleaning up large libraries of anything

**Comment by cyberlionx** [comment]
Perhaps a way to implement this would be 'inverse selections'. That is, for any group of duplicates for which at least one item has been selected, reverse the selected/unselected status of the items in that group.

This would differ from the current 'reverse selection' function by not selecting any objects in any groups in which no items are already selected.

Then we could custom select by path (a function already present) the path we want to keep and then inverse the selections, leaving the path to keep unselected and all other objects in those groups selected while any other groups (which would have not had anything selected during the custom select) would still have nothing selected.

This is how I expected 'inverse selection' to work in the first place, tbh.

**Comment by cyberlionx** [comment]
In the interim, the only I've found is a rather tedious workflow:
1) ensure recycle bin/trash is enabled on your system and does not contain anything from the path-to-keep

2) ensure 'move deleted files to trash' is selected in the options

3) use any of the existing means of selection and remove duplicates

4) go to your recycle bin/trash and restore anything deleted from your path-to-keep

5) go back to czkawka and perform another scan. Any duplicate groups should  have only 2 entries, your path-to-keep and whatever other copy was kept earlier

5) use custom select -> path to select the items in your path-to-keep

6) select - > inverse selections (now the copies not in path-to-keep are selected and the copies in path-to-keep are not

7) remove selections

You've now removed all duplicates NOT in path-to-keep (as well as all copies but one of any other duplicates, even if the remaining file is not in path-too-keep. Hope that's not a problem for some reason) while keeping (or rather restoring) any copies in path-to-keep
