### ISSUE TITLE
Czkawka 3.0.0 AppImage stuck : no list of duplicates (99% Progress) and no Stop possible

### ISSUE THREAD

**Issue by bluesangel** [qarmin/czkawka#315]
Hi. 
I guess I'm maybe facing some Czkawka limits as I looked for duplicates in 2 big external drives / 263922 files. 
Czkawka Progress Window is stuck / no change for 8 hours.
![cz stuck](https://user-images.githubusercontent.com/5963711/114432666-3b405f80-9bc1-11eb-9acb-7dc5dc579210.png)

**Comment by qarmin** [comment]
260000 files isn't too big number for Czkawka(I used a lot of more)
I don't see even 1 place when it could happens.

Can you open again Czkawka but this time via command line? - maybe there will be written backtrace 
It is possible that one of threads crashed and app still waits for it.

**Comment by bluesangel** [comment]
Thanks for your quick feedback - and this great program. I did start it through the terminal so here are the details :
```
 ./linux_czkawka_gui.AppImage 
/usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Full }', czkawka_core/src/duplicate.rs:492:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Any', czkawka_core/src/duplicate.rs:608:39
Erreur du bus (core dumped)

```

Forgot to mention I'm using Ubuntu 20.04 x64/ 5.8 kernel

**Comment by qarmin** [comment]
I know why it happens(message queue with info about scanned files is full)
but I don't know exactly why it happens(This is probably CPU fault that doesn't clear queue)

Easy Fix - Increasing 20 with e.g. 400:
https://github.com/qarmin/czkawka/blob/13add1cbedafba43b24a0816bf20bca36b38cfbb/czkawka_gui/src/main.rs#L91-L100

A little harder fix - change bounded queue to unbounded(sky is the limit) - I want to implement this but not sure if this will be simple enough.

**Comment by qarmin** [comment]
Can you check if binaries from - https://github.com/qarmin/czkawka/actions/runs/743784177 - fixes bug?(scroll at the bottom of page to see artifacts)

**Comment by bluesangel** [comment]
I tried to reproduce the issue with no success. 
It seems the issue is related to memory exhaustion / Chrome taking most memory : 
`[lun. avril 12 19:09:14 2021] Out of memory: Killed process 1511230 (chrome) total-vm:39240468kB, anon-rss:10132kB, file-rss:0kB, shmem-rss:872kB, UID:1000 pgtables:1056kB oom_score_adj:300
[lun. avril 12 19:09:16 2021] Out of memory: Killed process 1506168 (chrome) total-vm:881824kB, anon-rss:11132kB, file-rss:0kB, shmem-rss:40616kB, UID:1000 pgtables:920kB oom_score_adj:200
[lun. avril 12 19:09:17 2021] Out of memory: Killed process 1506170 (chrome) total-vm:1367852kB, anon-rss:28104kB, file-rss:0kB, shmem-rss:184kB, UID:1000 pgtables:908kB oom_score_adj:200
`
