### ISSUE TITLE
Please at least optionally disable deleting all copies that match custom criterion

### ISSUE THREAD

**Issue by gessel** [qarmin/czkawka#317]
I noticed that a hash check had correctly identified many identical files in multiple directory hierarchies, in this case created by several corrupt media recovery efforts at different times.

In one case, the only copies of a particular file had both come from different recovery efforts and had been stored in different directory hierarchies including the string "probably duplicate" - they were unusual as most had a reference file in a less dubious location and so using the custom search string */probably duplicate/* generally sorted lint from wheat. 

Except in this case, all extant copies were labeled as lint for deletion.  As Czkawka is most useful for bulk operations, this could easily result in undesirable and unexpected (and perhaps unnoticed) loss - that one image that the NFT just sold for $1M.  It seems almost essential in a tool like this that deleting all found copies found be explicitly disallowed even if all meet the selection criterion. It seems highly unlikely that the user intent is to delete all copies and highly likely that a selection criterion collision can arise in unwanted path-based over-selection.

The current behavior is:
[https://brt.llc/insecure/Czkawka-all-copies-selected.png](url)

Czkawka 3.0.0 on Ubuntu 20.04

**Comment by endolith** [comment]
I thought this would not allow deleting all copies of a file, like FSLint, etc. but it does it with no warning at all!  I'm glad I only used it on things I didn't really care about first

**Comment by allentiak** [comment]
@endolith @qarmin Does this apply to the latest release? (as of 2021.08.29, 3.2.0)

**Comment by MrTango** [comment]
As far as i can say, it does not apply to the current 4.0.0, it looks pretty much the same as fslint. You have to choose the files to be deleted, you will get a warning and you can move them in trash instead of deleting them.

**Comment by bonderado** [comment]
As of version 5.0.2, there is a checkbox in the custom selection window, that prevents selecting all files in a group. I think it is on by default, so it looks like this can be closed.

**Comment by gessel** [comment]
Just built and verified 5.0.2 - "Don't select all records in group" is checked by default.  Awesome!  Thanks.

**Comment by cjbarth** [comment]
@gessel , if that satisfies your request, why not close this issue?

**Comment by gessel** [comment]
oops, sorry.
