### ISSUE TITLE
Doesn't launch file explorer!

### ISSUE THREAD

**Issue by mbnoimi** [qarmin/czkawka#318]
As you know double click suppose to launch the default file explorer. But in XFCE desktop it launches Bluetooth chooser instead (as shown in the following screencast)!

https://user-images.githubusercontent.com/284547/115149979-1d667500-a06f-11eb-849d-638c44b238ae.mp4

* Linux Mint 20.1 XFCE
* Czkawka 3.0.0
* XFCE 4.14
* Thunar 1.8.14

**Comment by qarmin** [comment]
Can you check what will do command `xdg-open /`?
By default it should open file browser in `/` location. 
I think that you may have broken default app to open folders.

**Comment by qarmin** [comment]
Closing due lack of response.
I'm almost sure that something like https://unix.stackexchange.com/questions/42316/how-to-change-the-default-filemanager-of-the-cinnamon-desktop(first answer) should work fine
