### ISSUE TITLE
Option to not delete from cache outdated results

### ISSUE THREAD

**Issue by qarmin** [qarmin/czkawka#319]
This will be helpful, when e.g. scanning external drivers

**Comment by alexislefebvre** [comment]
Can it enabled by default? I think that's it's better to always keep data, using some extra space in the cache is better than pruning obsolete hashs and require to analyze files again.

**Comment by qarmin** [comment]
Not sure if it should be enabled by default, because this will create big cache files which will be slow in loading and saving when trying to scan directory with e.g. 10 objects, so manual intervention would be required(e.g. clicking at "Clean cache file from outdated results").

**Comment by alexislefebvre** [comment]
How much space would it use? How much slower would it be? A button that allow to clean the cache file, that display an alert like "Ensure that all removable drives are accessible otherwise you will have to scan them again" would be great IMHO.

**Comment by qarmin** [comment]
1000 results takes usually ~200KB, so probably a lot of people will have cache files with size max ~1/2MB which is not really a problem.
When cache have ~50000 entries, I think that on lower end computers, laptops or HDD, cache can load or save even few seconds(I can't really test it on my computer and SSD), so each scan would start very slow.
I didn't implement yet buttons for deleting outdated results.
