### ISSUE TITLE
Comparison to rmlint

### ISSUE THREAD

**Issue by phiresky** [qarmin/czkawka#328]
You have some nice comparisons in the readme, but could you also compare rmlint? rmlint is much faster than FSLint afaik (for finding exact duplicates). https://github.com/sahib/rmlint

**Comment by qarmin** [comment]
I'm quite bad at doing benchmarks, so I created issue in fclones, which author seems to do great tests.

**Comment by qarmin** [comment]
Looks that Czkawka is a little faster - https://github.com/pkolaczk/fclones#ssd-benchmark
