### ISSUE TITLE
Windows: No permission

### ISSUE THREAD

**Issue by DimoNline** [qarmin/czkawka#329]
I recieve errors on trying to delete selected files. Even when running as administrator. 
```
Failed to remove file B:\books\Gamedev\gdlib_140418\DevBooks\Game Dev Experienced\GPG Series/Game Programming Gems 2, 2001 - Samples.zip. It is possible that you already deleted it, because similar images shows all possible file doesn't exists or you don't have permissions.
Failed to remove file B:\books\Gamedev\gdlib_140418\DevBooks\Game Dev Experienced\GPG Series/Game Programming Gems 6, 2006 - Samples.zip. It is possible that you already deleted it, because similar images shows all possible file doesn't exists or you don't have permissions.
```

**Comment by qarmin** [comment]
Can you delete this files manually from file manager?
If no, then it is OS issue.
If yes, then I need to investigate why this happened

I need to fix error message, since now is broken and doesn't have any sense.

**Comment by qarmin** [comment]
In latest version, errors are more descriptive so they should print exactly cause of error
