### ISSUE TITLE
thread 'main' panicked at 'Invalid file date:

### ISSUE THREAD

**Issue by choffman** [qarmin/czkawka#33]
czkawka dies when encountering a file date that it doesn't like, but it also doesn't say which file that may be.  Running it with BACKTRACE options does not give any additional info.  

You may want to enhance the exception handling to output files that it has problems with.

Full output:

me@mymachine:~/my_huge_directory$ RUST_BACKTRACE=full ~/Downloads/czkawka_gui
thread 'main' panicked at 'Invalid file date: SystemTimeError(1132781810s)', czkawka_core/src/duplicate.rs:289:71
stack backtrace:
   0:     0x55f20392b9b5 - <unknown>
   1:     0x55f20394f79c - <unknown>
   2:     0x55f2039299b2 - <unknown>
   3:     0x55f20392e2b0 - <unknown>
   4:     0x55f20392dffc - <unknown>
   5:     0x55f20392e8f3 - <unknown>
   6:     0x55f20392e4eb - <unknown>
   7:     0x55f20394e131 - <unknown>
   8:     0x55f20394df53 - <unknown>
   9:     0x55f2038f303c - <unknown>
  10:     0x55f2038e3a16 - <unknown>
  11:     0x7f795d3b0a56 - <unknown>
  12:     0x7f795d3cfb28 - g_signal_emit_valist
  13:     0x7f795d3d00d3 - g_signal_emit
  14:     0x7f795d9c82ae - <unknown>
  15:     0x7f795d9c8318 - <unknown>
  16:     0x7f795d3b0802 - g_closure_invoke
  17:     0x7f795d3c4962 - <unknown>
  18:     0x7f795d3cfb9e - g_signal_emit_valist
  19:     0x7f795d3d00d3 - g_signal_emit
  20:     0x7f795d9c6754 - <unknown>
  21:     0x7f795dc77ae1 - <unknown>
  22:     0x7f795d3b0a56 - <unknown>
  23:     0x7f795d3cfb28 - g_signal_emit_valist
  24:     0x7f795d3d00d3 - g_signal_emit
  25:     0x7f795da8efcc - <unknown>
  26:     0x7f795d3b3c56 - g_cclosure_marshal_VOID__BOXEDv
  27:     0x7f795d3b0a56 - <unknown>
  28:     0x7f795d3cfb28 - g_signal_emit_valist
  29:     0x7f795d3d00d3 - g_signal_emit
  30:     0x7f795da8c012 - <unknown>
  31:     0x7f795da8d65b - <unknown>
  32:     0x7f795da90646 - <unknown>
  33:     0x7f795da57bb0 - gtk_event_controller_handle_event
  34:     0x7f795dc1a16d - <unknown>
  35:     0x7f795dc715ef - <unknown>
  36:     0x7f795d3b0a56 - <unknown>
  37:     0x7f795d3cedd1 - g_signal_emit_valist
  38:     0x7f795d3d00d3 - g_signal_emit
  39:     0x7f795dc1bc23 - <unknown>
  40:     0x7f795dad7128 - <unknown>
  41:     0x7f795dad93db - gtk_main_do_event
  42:     0x7f795d7c1f79 - <unknown>
  43:     0x7f795d7f5106 - <unknown>
  44:     0x7f795d2c4fbd - g_main_context_dispatch
  45:     0x7f795d2c5240 - <unknown>
  46:     0x7f795d2c5533 - g_main_loop_run
  47:     0x7f795dad837d - gtk_main
  48:     0x55f2038d2a20 - <unknown>
  49:     0x55f2038ed033 - <unknown>
  50:     0x55f20392ecc3 - <unknown>
  51:     0x55f2038d4592 - <unknown>
  52:     0x7f795d0620b3 - __libc_start_main
  53:     0x55f2038c71ae - <unknown>
  54:                0x0 - <unknown>

**Comment by qarmin** [comment]
This should be fixed by a0c99ab14bf13e337aa8dceb255912f2b75032dd.
I'm curious why file have modified time before Unit Epoch.
I was thinking that is not possible to do this, but it shows that I was wrong.

Now it should print to bottom tab path of file which has this invalid(I think) date
