### ISSUE TITLE
Suggestion: ability to select multiple error types to scan for on the gui

### ISSUE THREAD

**Issue by poisonborz** [qarmin/czkawka#332]
Firstly congrats for this awesome app! My only gripe with the GUI is that I need to select each error type one by one if I want to scan a media library for all kinds of errors. It would be awesome if instead of tabs there were checkboxes instead, so multiple could be selected at once. In the file list, there could be a "category" column to show what kind of error it is (duplicate, zeroed, etc).

**Comment by qarmin** [comment]
This won't be implemented since it would require to add complex compatibility layer between each tool.
I don't even seen one tool that would implement such thing

**Comment by poisonborz** [comment]
There is no such complexity necessary, this is just a very simple GUI shortcut. This would just mean "run the selected checks on the folder" (probably one after another) and basically show a summary screen for any items found by each checks (5 duplicate files, 9 zeroed files). When clicking on each, that list would show up.

This would make it possible to make a single scan for any problems with a media folder. Currently you need to run 5-8 checks separately. I make the wild guess a large number of users just want an overall health check, instead of checking for a specific errror.
