### ISSUE TITLE
Won't scan NFS mount point.

### ISSUE THREAD

**Issue by coreyhuinker** [qarmin/czkawka#333]
The NFSv4 mount point is `/nfs` and it has several subdirectories (when mounted).

The file selector will now acknowledge the existence of `/nfs` let alone `/nfs/foo` in the add-a-directory widget. Manually adding the directory will put it in the list of directories to be scanned, but attempting to scan that directory leads to the error

```Included Directory Warning: Provided folder path must exits, ignoring /nfs/foo```

**Comment by alexislefebvre** [comment]
Since you use snap, try this: https://github.com/qarmin/czkawka/pull/218/files

**Comment by pmetras** [comment]
> Since you use snap, try this: https://github.com/qarmin/czkawka/pull/218/files
I already had set up this permission but without success. Does it need a similar snap permission for the GTK file/directory picker?

> Or install czkawka without snap.
This did the trick using the linux GUI executable.

Thanks

**Comment by FilipDominec** [comment]
@alexislefebvre It did solve the same problem for me (also on Ubuntu 20.04, czkawka 3.2.0 installed today from snap).

**Comment by qarmin** [comment]
Closing as fixed, but if issue still exists in latest version, then error should be more descriptive

**Comment by rinaldimj** [comment]
I'm having this same issue with Czkawka v4.0.0, installed today (2022-01-26) snap package on Ubuntu 20.04.3 LTS.

Considering that my NFS drive mounted on _/media/jonas/nasdrive_, when trying to add the folder to czkawka, I get the following error:

`"Could not read the contents of nasdrive. Error opening directory '/media/jonas/nasdrive': Stale file handle"`

The command `sudo snap connect czkawka:removable-media` was already succesfully executed but does not solve the issue.

I also tried mounting my NFS drive using fstypes _nfs_ (NFS3) and _nfs4_ (NFS4) but the results are the same.

I understand that this description may not be the most detailed one but I'd like to contribute. Is it possible to run czkawka in a more _verbose_ or _debugging_ mode?
