### ISSUE TITLE
Windows resize acting strange

### ISSUE THREAD

**Issue by adripo** [qarmin/czkawka#335]
Hi, if I try to resize the application gui on windows, it changes position and flickers in a strange way. It doesn't resize correctly.

Version 3.1.0
Windows 10
Resolution 1920 x 1080

**Comment by qarmin** [comment]
This is probably GTK bug - https://gitlab.gnome.org/GNOME/gtk/-/issues/2639
Test app should be placed here https://github.com/qarmin/czkawka/actions/runs/847462148
