### ISSUE TITLE
[GUI] Add selection checkboxes.

### ISSUE THREAD

**Issue by Panchosauriooo** [qarmin/czkawka#337]
As the title says, you could add checkboxes to select multiple files, similar to dupeGuru: 

![image](https://user-images.githubusercontent.com/7199366/118066548-e1bc8380-b36c-11eb-80a6-a3b1365d5105.png)

**Comment by qarmin** [comment]
I plan to do this in next versions, because it easy to accidentally deselect all selected results now.
Sadly this will require to do some bigger changes to Gui logic, so probably I will wait for GTK 4.0 to do this all in once.

**Comment by qarmin** [comment]
Currently I'm blocked by https://discourse.gnome.org/t/how-to-get-attribute-value-from-treeviewcolumn/6921, but I got some basic screenshoot how it will look

![Screenshot from 2021-07-09 15-41-52](https://user-images.githubusercontent.com/41945903/125088275-8f2de800-e0cd-11eb-8ba3-ce3f18956d9d.png)
