### ISSUE TITLE
GTK icons and theme problems in appimage

### ISSUE THREAD

**Issue by ShrirajHegde** [qarmin/czkawka#338]
Misbehaving icons and theme [appimage]

![image](https://user-images.githubusercontent.com/66936172/118097163-f2faa400-b3ef-11eb-9d09-3ed7f1a0747a.png)

In standalone binary:

![image](https://user-images.githubusercontent.com/66936172/118097243-1291cc80-b3f0-11eb-908e-5c148ca5b279.png)

**Comment by qarmin** [comment]
This is not a bug, gtk plugin for appimage ships own theme
