### ISSUE TITLE
An even higher similarity in similar images

### ISSUE THREAD

**Issue by kabudi** [qarmin/czkawka#341]
We need an even higher similarity between images

**Comment by qarmin** [comment]
This probably can be done, but only with different type of hash(this will broke compatibility).
Probably blockhash should be proper to do that.

**Comment by Borkason** [comment]
Would it be possible to have the options to specifiy a double-precision percentage number instead of choosing betweens a set amount of options? Something like 95%, 99.0%, 99.5%, and so on?

**Comment by qarmin** [comment]
Not exactly.
I don't know which similarity algorithm used in other programs can provide such precision, but Czkawka use hamming distance which is simple integer number.

Each image produce 64bit value  and if two images will generate same value then Czkawka say that this two images are very very similar, if values differ in one bit then are very similar, if with two bits then are just similar etc.

For now only 4 or 5 bits at most can be different.

I think about allowing user to use more bits, but allowing to set values like 60% doesn't have sense for me in this case.

I suspect that some(not all of course) other programs also use similar algorithms and there is no difference between 97% and 95%.

**Comment by qarmin** [comment]
In newest version 16x16 hash size with 0 similarity level is quite good at finding near exact duplicates
Probably I will also add 32x32 hash which should have very small error tolerance, but will only allow to find very similar images
