### ISSUE TITLE
image preview on duplicates files view

### ISSUE THREAD

**Issue by bbodenmiller** [qarmin/czkawka#362]
Would be great if I could see an image preview on duplicate files view rather than having to use resource intensive similar images scan.

Situation:
- Known duplicates across multiple folders
- Same file name
- Possibly different resolutions and file sizes

**Comment by alexislefebvre** [comment]
Is it the same idea as #334?

**Comment by bbodenmiller** [comment]
Not necessarily. If the view currently shown on similar images view was also available on duplicate files view I'd be happy.
