### ISSUE TITLE
[Low Priority] Embedding Icon to Binary

### ISSUE THREAD

**Issue by ShrirajHegde** [qarmin/czkawka#365]
An embedded icon in the binary would nice instead of generic binary icon on taskbar.

![image](https://user-images.githubusercontent.com/66936172/118524347-adc1d380-b75b-11eb-8256-73c774247d7f.png)

**Comment by Darthagnon** [comment]
Windows doesn't have an icon in the EXE, either. It would be nice, indeed!

There's two icons used by this project, one in the About window in the program (beautiful brown magnifying glass), and the rather generic metro/fluent "file shredder" icon used on the website. I kinda wish the brown magnifying glass could be embedded.

For the time being, I'm using the bland shredder icons from the website (attached)
[Czkawka_icon.zip](https://github.com/qarmin/czkawka/files/6626438/Czkawka_icon.zip)

**Comment by MrJake222** [comment]
Mine About page shows (I think) system search icon.
![Screenshot_20210614_122329](https://user-images.githubusercontent.com/7581790/121877728-39069880-cd0b-11eb-8deb-13355909409e.png)

**Comment by MrJake222** [comment]
Btw you can copy the icon to `/usr/share/icons/hicolor/256x256/apps/com.github.qarmin.czkawka.png` and It worked for me (using Plasma on Arch). It fixed lanucher and toolbar icon, but not the bar icon.

@Darthagnon Are there SVG versions of the shredder icon?

**Comment by Darthagnon** [comment]
@MrJake222 After I posted the PNGs from the website, I search through the source code, and YES, there are SVG versions of the shredder icon!!

https://github.com/qarmin/czkawka/tree/master/data/icons

**Comment by Darthagnon** [comment]
Here's what the icon looks like on Win10 (not a system icon, as far as I know. Wish I could find it, as it is much better than the shredder icon). Actually looks a bit like a MacOS system icon... I wonder, since the Windows version has MacOS window controls, whether some other Mac graphics are used, too? Can't find it in the source code, though
![windows_czkawka_gui_w99JCGv8Qm](https://user-images.githubusercontent.com/20792748/121955383-ca9bf780-cd57-11eb-8984-0540069f461f.png)

**Comment by MrJake222** [comment]
Now I need info how to fix the icon on the title bar...

**Comment by qarmin** [comment]
On Linux it is not possible to embed icon into binary.
Icon is visible when installing Czkawka using Snap or Flatpak.

**Comment by qarmin** [comment]
Well icon in taskar should be available in 4.0 version.
Also in About Window icon was changed(previously was used generic icon to search)
