### ISSUE TITLE
Identical Image Detection

### ISSUE THREAD

**Issue by ImportTaste** [qarmin/czkawka#377]
Sometimes, two images are completely identical, but the files themselves are different, such as when a PNG's compression level is different.

There should be an option in the Similar Images search to find image files that are identical, not just very high similarity.

**Comment by ImportTaste** [comment]
I was thinking that maybe an even better approach would be the ability to set a percentage in an input box. The current buttons could essentially put in their respective percentage in the input box when clicked on.

**Comment by ImportTaste** [comment]
@tecome Would you be willing to add this since you're familiar with that area of the code?

**Comment by qarmin** [comment]
I don't think that finding identical images is possible to do without reading each pixel RGBA value and comparing it to each other.
Such solution would require to use some very slow comparsions.
Now only hashes 8x8 or 16x16 are compared but after changes almost every single pixel in image would be compared to each others. 
Of course not too much images have e.g. 100 first bytes equal so this should throw away a lot of images, but still using even very light image conversion(e.g. png to 100% image quality jpg) will cause that this images won't be treat as exactly same.
For me for finding identical images, the best is duplicate finder.

**Comment by qarmin** [comment]
Closing, since hash 64x64 should in 99.99999999% only shows identical images

**Comment by ImportTaste** [comment]
> Closing, since hash 64x64 should in 99.99999999% only shows identical images

I just tested it. It regards a PNG saved with a white background and a PNG saved with a transparent background as the same.

**Comment by qarmin** [comment]
Problem with error spam was fixed in https://github.com/qarmin/czkawka/pull/525
This happened due my custom algorithm of saving/loading data to cache and now I use directly Serde library.
