### ISSUE TITLE
[Feature] Implement a way to import FILES to hash and check for duplicates.

### ISSUE THREAD

**Issue by frenchiveruti** [qarmin/czkawka#379]
So, a problem I've found with Czkawka is that it checks ALL the files in my windows system and it incurs into a very long time waiting it for check for every single file hash, which, to me, makes no sense because as far as I understand, if two files don't share filesize, they can not possibly share Hashes (unless, to my understanding, they are a collision on the algorithm used).  

So, I used everything by voidtools to look for duped files by size, using the `sizedupe:` function, and I exported that list of files as a TXT, that gives me the filelist.  
Now, I have a txt files with the filepaths line by line, but I can't import them into the software!  
It would be nice to be able to check this list for duplicates.  
So, either add an option to import a text file, or allow the user to input a line by line directory to fileS to hash.

**Comment by qarmin** [comment]
Czkawka don't hash every file from provided path - https://github.com/qarmin/czkawka/blob/master/instructions/Instruction.md#duplicate-finder

**Comment by frenchiveruti** [comment]
It's way faster my way because everything already has the files paths.  
as of now, Czkawka has to check the filesizes manually one by one, that's fun for 1000 files, add an entire disk, not fun, three disks, go make a coffee and come back later (it took 45minutes to run last time on my computer with an i7-4790k and an SSD)  
Instead, just telling "HEY, CHECK THIS FILES, THANKS" would be faster as everything already indexed the duplicates by size.  

I understand it's a good chunk of rewriting, but it's a suggestion nonetheless.  
Thanks.

**Comment by frenchiveruti** [comment]
To expand on this, I have 1.5M files across my disks, takes everything sizedupe: function 3ms to return duplicates.  
Takes a good minute for Czkawka to compute the list, and then return the list.

**Comment by frenchiveruti** [comment]
But I understand what you mean, I think is fast enough to be negligible to implement.
