### ISSUE TITLE
Is there a Database record?

### ISSUE THREAD

**Issue by chchia** [qarmin/czkawka#381]
Thanks Author for the program.

first time using czkawka, but would like to confirm below:

1. I have a folder with million of files, it will be great if this program can store all the files path and the size of each files, and possible the hash or hashmb of the files, so that when i add in new files i dont have to run through the full comparison again, possible?
I am aware it have cached support for faster in next scan, however i am not sure how long this cache will be kept as cache usually means volatile.

2. it is possible to set main folder and secondary folder? to allow user to always make comparison of secondary to main folder and remove file in secondary folder if match found?

**Comment by qarmin** [comment]
1. Entry in cache exists as long as file exists and have same size, path and modification date as record from cache, entries can be easily modified/deleted here  - https://github.com/qarmin/czkawka/blob/master/instructions/Instruction.md#configcache-files
2. It is not possible. When you set parent and child folder, then Czkawka optimize it remove child folder, because during scanning parent folder also child will be this scanned. You can use after scan "Select custom" button and there select all entries from child folder

**Comment by alexislefebvre** [comment]
@qarmin I think chchia was thinking to a "reference" folder, like the idea proposed in #232.

**Comment by chchia** [comment]
`Cache should be here:

Linux - /home/username/.cache/czkawka
Mac - /Users/Username/Library/Caches/pl.Qarmin.Czkawka
Windows - C:\Users\Username\AppData\Local\Qarmin\Czkawka\cache`

i am using windows 10, i found the config directory, but i cannot find the cache directory, even i run the program as administrator....

i have 1.9 millions of file, and it had been hashmb for 2 days and completed about 40%, now it suddenly hang, and when i restart it restarting all over from 0. and i cannot find the cache file.

is there any other location where czkawka storing the cache?

**Comment by qarmin** [comment]
Hashmb doesn't allow to save data to cache(probably this should be mentioned somewhere)
Only full hash comparsion allow to save info about hash to cache, but only when scan will finish(user cannot stop it).
I suggest to scan with full hash scan a few smaller directiories, and then after that, cache will fill and later scans should be faster.

**Comment by chchia** [comment]
i see, it will be appreciate if you can let hashmb to safe cache?

otherwise it will be nightmare for someone like me having 1.8 millions of files...

**Comment by scrapix** [comment]
Agree, a database would be a charm. Also would allow:
- saving & loading search results or even all database entries
- quicker queries / filterings
