### ISSUE TITLE
Is it possible to make the Windows GUI version into an exe software?

### ISSUE THREAD

**Issue by erbanku** [qarmin/czkawka#387]
Hi there,
I am extremely like this project, and thanks a lot for your awesome works. As it said it the title **is it possible to make the Windows GUI version into an exe software?**   Doesn't including another batch of files like in the screenshot below, otherwise it looks a little messy. 
@Waiting your reply, thanks.

![image](https://user-images.githubusercontent.com/79493862/124011995-34342b00-da13-11eb-8310-4e07849d9f55.png)

**Comment by qarmin** [comment]
I don't think that this is possible to bundle all shared libraries into one exe.

It is possible to use this one exe alone, but gtk3 runtime is required - https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases

**Comment by erbanku** [comment]
OK, thanks.

**Comment by vartaxe** [comment]
It would be awesome to have an .exe or .msi installer though
