### ISSUE TITLE
Failed to load module "pk-gtk-module"

### ISSUE THREAD

**Issue by djjudas21** [qarmin/czkawka#388]
Hi, I installed czkawka on Fedora from Snap but the dependencies seem broken:

```
[jonathan@poseidon ~]$ snap list czkawka
Name     Version  Rev  Tracking       Publisher     Notes
czkawka  3.1.0    422  latest/stable  turkimlafarq  -

[jonathan@poseidon ~]$ czkawka 
Gtk-Message: 15:13:29.073: Failed to load module "pk-gtk-module"
Gtk-Message: 15:13:29.074: Failed to load module "pk-gtk-module"
^C
```

I have to ctrl+c because the gui never appears.

I don't fully understand how the snap packaging works so I also installed the deps `gtk3-devel glib2-devel` as you recommend, and also `PackageKit-gtk3-module` which provides the `pk-gtk-module`.

This used to work for me so I'm not sure what's wrong. Thanks.

**Comment by qarmin** [comment]
Snap doesn't require installing additional packages because it contains everything inside.

This messages 
```
Gtk-Message: 15:13:29.073: Failed to load module "pk-gtk-module"
```
are mostly only informational, so this shouldn't cause crashes(I'm not sure even which app require this module)

**Comment by djjudas21** [comment]
That's what I thought about the dependencies. But I only get these Gtk messages in a terminal and the GUI never appears, so the app is somehow broken and I'm not sure how to troubleshoot it. This used to work on my system when I was running Fedora 33 but seems to stop working since I upgraded to Fedora 34. Happy to provide any extra logs that will help you - thanks.

**Comment by djjudas21** [comment]
Normal functionality of the GUI is working again when I switched from `latest/stable` to `latest/edge` (revision 422 to 480). Closing this as it's no longer relevant.
