### ISSUE TITLE
czkawka with snap and home on a NTFS partition ERROR double free detected in tcache 2

### ISSUE THREAD

**Issue by geole** [qarmin/czkawka#389]
Hello
I used czkawka with the .deb package. It works great for searching over 200,000 files in a reasonable amount of time.

I now want to use it in snap format on another computer. The installation is going well. But I can't launch it. The error message is as follows:
**double free detected in tcache 2**

here is the trace`czkawka
chmod: changing permissions of '/home/a/snap/czkawka/422/.config': Permission denied
/snap/czkawka/422/snap/command-chain/desktop-launch: line 113: /home/a/snap/czkawka/422/.config/user-dirs.dirs: Permission denied
/snap/czkawka/422/snap/command-chain/desktop-launch: line 255: /home/a/snap/czkawka/422/.config/user-dirs.dirs: Permission denied
/snap/czkawka/422/snap/command-chain/desktop-launch: line 256: /home/a/.config/user-dirs.dirs: Permission denied
cp: cannot open '/home/a/.config/user-dirs.locale' for reading: Permission denied
/snap/czkawka/422/snap/command-chain/desktop-launch: line 261: /home/a/.config/user-dirs.locale: Permission denied
/snap/czkawka/422/snap/command-chain/desktop-launch: line 113: /home/a/snap/czkawka/422/.config/user-dirs.dirs: Permission denied
Can't save user-dirs.dirs
/snap/czkawka/422/snap/command-chain/desktop-launch: line 113: /home/a/snap/czkawka/422/.config/user-dirs.dirs: Permission denied
rm: cannot remove '/home/a/snap/czkawka/422/.local/share/themes': Permission denied
/snap/czkawka/422/snap/command-chain/desktop-launch: line 394: /home/a/snap/czkawka/422/.config/fontconfig/fonts.conf: Permission denied
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/themes': Permission denied
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.themes': Permission denied
rm: cannot remove '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas': Permission denied
rm: cannot remove '/home/a/snap/czkawka/common/.cache/gio-modules': Permission denied
rm: cannot remove '/home/a/snap/czkawka/common/.cache/gdk-pixbuf-loaders.cache': Permission denied
/snap/czkawka/422/snap/command-chain/desktop-launch: line 488: /home/a/snap/czkawka/common/.cache/gdk-pixbuf-loaders.cache: Permission denied
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/gio-modules/libdconfsettings.so': File exists
rm: cannot remove '/home/a/snap/czkawka/422/.local/share/icons': Permission denied
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/gio-modules/libgiognomeproxy.so': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/gio-modules/libgiognutls.so': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/gio-modules/libgiolibproxy.so': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.a11y.applications.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.a11y.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.a11y.keyboard.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.a11y.magnifier.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.a11y.mouse.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.app-folders.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.background.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.calendar.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.datetime.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.default-applications.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.enums.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.input-sources.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.interface.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.lockdown.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.media-handling.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.notifications.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.peripherals.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.privacy.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.screensaver.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.search-providers.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.session.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.sound.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.thumbnail-cache.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.thumbnailers.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.wm.keybindings.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.desktop.wm.preferences.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.system.locale.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.system.location.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gnome.system.proxy.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gtk.Settings.ColorChooser.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gtk.Settings.Debug.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gtk.Settings.EmojiChooser.gschema.xml': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml': File exists
rm: cannot remove '/home/a/snap/czkawka/422/.config/ibus/bus': Permission denied
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.local/share/glib-2.0/schemas/10_gsettings-desktop-schemas.gschema.override': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/422/.config/ibus/bus': Permission denied
Unable to open directory /home/a/snap/czkawka/common/.cache/gio-modules: Error opening directory “/home/a/snap/czkawka/common/.cache/gio-modules”: Permission denied
rm: cannot remove '/home/a/snap/czkawka/common/.cache/immodules': Permission denied
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/immodules/im-am-et.so': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/immodules/im-broadway.so': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/immodules/im-cedilla.so': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/immodules/im-cyrillic-translit.so': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/immodules/im-fcitx.so': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/immodules/im-ibus.so': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/immodules/im-inuktitut.so': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/immodules/im-ipa.so': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/immodules/im-multipress.so': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/immodules/im-thai.so': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/immodules/im-ti-er.so': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/immodules/im-ti-et.so': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/immodules/im-viqr.so': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/immodules/im-wayland.so': File exists
ln: failed to create symbolic link '/home/a/snap/czkawka/common/.cache/immodules/im-xim.so': File exists
/snap/czkawka/422/snap/command-chain/desktop-launch: line 565: /home/a/snap/czkawka/common/.cache/immodules/immodules.cache: Permission denied
/snap/czkawka/422/snap/command-chain/desktop-launch: line 573: /home/a/snap/czkawka/422/.last_revision: Permission denied

(czkawka_gui:16136): GdkPixbuf-WARNING **: 14:45:17.586: Cannot open pixbuf loader module file '/home/a/snap/czkawka/common/.cache/gdk-pixbuf-loaders.cache': Permission denied

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/a/snap/czkawka/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.

(czkawka_gui:16136): Gtk-WARNING **: 14:45:17.591: Theme parsing error: gtk.css:1566:23: 'font-feature-settings' is not a valid property name

(czkawka_gui:16136): Gtk-WARNING **: 14:45:17.602: Theme parsing error: gtk.css:3618:25: 'font-feature-settings' is not a valid property name

(czkawka_gui:16136): Gtk-WARNING **: 14:45:17.603: Theme parsing error: gtk.css:4080:23: 'font-feature-settings' is not a valid property name
free(): double free detected in tcache 2
Abandon (core dumped)  `

 **Remember**
`cat /etc/fstab | grep bind
/mnt/Windows1/Users  /home none bind
a@a:~$ `

**So** 
`cd snap
 ls -als
total 8
0 drwxrwxrwx 1 root root    0 juil.  4 13:59 .
8 drwxrwxrwx 1 root root 8192 juil.  4 14:25 ..
0 drwxrwxrwx 1 root root    0 juin  29 09:45 czkawka
0 drwxrwxrwx 1 root root    0 juil.  4 13:59 juju
0 drwxrwxrwx 1 root root    0 juin  28 13:29 snap-store

cd cz*
a@a:~/snap/czkawka$ ls -als
total 5
0 drwxrwxrwx 1 root root    0 juin  29 09:45 .
0 drwxrwxrwx 1 root root    0 juil.  4 13:59 ..
4 drwxrwxrwx 1 root root 4096 juil.  4 14:45 422
0 drwxrwxrwx 1 root root    0 juin  29 09:45 common
1 lrwxrwxrwx 1 root root    3 juin  29 09:45 current -> 422

 cd 422
 ls -ls
total 5
0 drwxrwxrwx 1 root root  0 juin  29 09:45 Bureau
1 lrwxrwxrwx 1 root root 33 juin  30 10:01 Cu1KPy0q -> /snap/czkawka/422/data-dir/themes
1 lrwxrwxrwx 1 root root 33 juin  29 09:51 Cu2m6eBn -> /snap/czkawka/422/data-dir/themes
1 lrwxrwxrwx 1 root root 33 juin  29 09:46 Cu933kpe -> /snap/czkawka/422/data-dir/themes
1 lrwxrwxrwx 1 root root 33 juin  29 09:55 CuaMKSPJ -> /snap/czkawka/422/data-dir/themes
1 lrwxrwxrwx 1 root root 33 juin  29 09:46 CuBLuVPf -> /snap/czkawka/422/data-dir/themes
1 lrwxrwxrwx 1 root root 33 juil.  4 14:45 CuE5gaFv -> /snap/czkawka/422/data-dir/themes
1 lrwxrwxrwx 1 root root 33 juil.  4 13:39 CuNIoyNb -> /snap/czkawka/422/data-dir/themes
1 lrwxrwxrwx 1 root root 33 juil.  4 13:33 CuOVf0km -> /snap/czkawka/422/data-dir/themes
1 lrwxrwxrwx 1 root root 33 juil.  4 13:12 CuVvzMaY -> /snap/czkawka/422/data-dir/themes
1 lrwxrwxrwx 1 root root 33 juil.  4 13:30 Cuwu2g71 -> /snap/czkawka/422/data-dir/themes
0 drwxrwxrwx 1 root root  0 juin  29 09:45 Documents
0 drwxrwxrwx 1 root root  0 juin  29 09:45 Images
0 drwxrwxrwx 1 root root  0 juin  29 09:45 Modèles
0 drwxrwxrwx 1 root root  0 juin  29 09:45 Musique
0 drwxrwxrwx 1 root root  0 juin  29 09:45 Public
0 drwxrwxrwx 1 root root  0 juin  29 09:45 Téléchargements
0 drwxrwxrwx 1 root root  0 juin  29 09:45 Vidéos

cd /snap/czkawka/422/data-dir/themes
ls -als
total 0
0 drwxr-xr-x 2 root root  3 mai    9 00:00 .
0 drwxr-xr-x 5 root root 56 mai    9 00:01 .. `

**Comment by qarmin** [comment]
This is probably Snap bug, not Czkawka.

I have seen a lot of times `double free detected in tcache 2` is C/C++ code but never in Rust
