### ISSUE TITLE
option for byte by byte compare

### ISSUE THREAD

**Issue by michael-ts** [qarmin/czkawka#398]
I would like to request an option to do a byte for byte comparison instead of using a hash.

The reason is that in some circumstances this can be much faster.  For instance, I've got several hundred GB of files on a fast SSD and it's pegging the CPU at 100% for a long time now when I could have already have simply read all the files into memory. (Strangely it's only using one of 16 cores even though it's advertised as multi-threading).  However, in any case, it seems that since each file has to be loaded into memory to be hashed *anyway*, all hashing does is add CPU load - simply doing a byte by byte compare would be much faster.

Additionally, this should not introduce much in the way of memory requirements since only one block of each potential copy has to be loaded into memory for comparison at a time, although an option for buffer size could be used as a larger buffer could provide some speedup for those with lots of RAM.

**Comment by qarmin** [comment]
I do not exclude the possibility of adding such an option in the future but it raises additional technical and performance issues.
Currently all the files are hashed, which allows you to save their hash to a file and then load them without having to hash them a second time.

In the case of reading data byte by byte, caching simply can not be done.

Also, nowadays there are usually as many files open as there are CPUs available. On Windows there is a limit of 512 open files.
For bit by bit comparisons you would either have to open a large number of files and read data from them, or you would have to load a large portion of them, close the files, open another one and so on and so forth which will complicate an algorithm.

Also there is a problem how to compare 1MB part of e.g. 5 files?
It is possible that from 5 files with same size, 2 are same and other 2 are also same (e.g. with content `v`, `e`, `v`, `e`,`b`). So to compare if files are same then each file must be compared with other one so this give case at most 10 comparisons(even more if there is more files).
