### ISSUE TITLE
Clarify matching syntax (globbing, regex, etc)

### ISSUE THREAD

**Issue by brianredbeard** [qarmin/czkawka#399]
First, wonderful work!

I started looking through the code at the new-ish features added in #117.  I noticed that much of the matching is being executed here:

https://github.com/qarmin/czkawka/blob/cc0dcc2714205d9a39ede764e9f723f2dc5c5ef0/czkawka_core/src/common.rs#L54-L108

My familiarity with Rust is definitely lacking, but it seems as if the function is just performing a basic pattern match/[globbing][glob] with the only available wildcard being the `*` (asterisk), which it uses as a string delimiter.  It does not _appear_ to support other globbing wildcards (`?` & `[]`) or [regular expressions][regex].  

Is that assessment correct?

[glob]: https://en.wikipedia.org/wiki/Glob_%28programming%29
[regex]: https://en.wikipedia.org/wiki/Regular_expression

**Comment by qarmin** [comment]
For now it only support `*` which means any character or string.
It is possible to add full support for regular expressions, but I wouldn't use it often enough so I didn't implement it before
