### ISSUE TITLE
Results background color inconsistent while searching duplicates and similar images

### ISSUE THREAD

**Issue by juozaspo** [qarmin/czkawka#401]
While searching for duplicates & similar images the background of search results is inconsistent. In checkbox column where is no checkbox there is white background everywhere else is like in dark theme and remaining background remains white. Screenshot:
![Czkawka 2021-07-31 14:51:16](https://user-images.githubusercontent.com/6626242/127739348-23decd01-c48f-42bc-84f0-6c29efd5559e.png)

**Czkawka version:** 3.1.0 (da76f75e1154d283c39df25cb74d7f2c20cd7848), compiled from source.
**OS:** Ubuntu Linux 20.04 LTS
**Desktop environment:** Xfce 4 with Greybird light theme
**Rust compiler verion:** 1.54.0 (a178d0322 2021-07-26)
**Cargo version:** 1.54.0 (5ae8d74b3 2021-06-22)
**Development libs packages:**
- **libasound2-dev:** 1.2.2-2.1ubuntu2.4
- **libgtk-3-dev:** 3.24.20-0ubuntu1

**Comment by qarmin** [comment]
White theme is not fully supported because I don't know exactly how to add different color to header rows in list store.
I don't want to use tree store since it is less performant.

**Comment by siodor** [comment]
@qarmin 
How about using the white space for a checkbox which (un)selects the whole group of files?

**Comment by qarmin** [comment]
In https://github.com/qarmin/czkawka/pull/450 I filled this empty space, but for now new button don't do anthing
