### ISSUE TITLE
Duplicate search between, but not within, two distinct directories?

### ISSUE THREAD

**Issue by felciano** [qarmin/czkawka#402]
I'm trying to figure out how to configure `czkawka` to perform a duplicate search across two directories, but ignoring duplicates within the same directory tree.

The use case is a `source` folder of images that have previously been processed by scripts to rename them and sort them into a `destination` directory structure (e.g. by year and month, or by other EXIF metadata). Then we come across a new folder of images, some of which may have been processed previous.

1.  We'd like to know if any of those images already exist in the `destination` directory, presumably based on file contents.
2. The `source` folder may have duplicates in it, i.e. identical photos with different names. These are not of interest to be found (i.e. would like to ignore these duplicate matches).
3. It's possible that the `destination` folder also has duplicates in it, for example if you are storing multiple copies of a phone, one under a directory tree using a date-based organization, and one under a directory tree using EXIF-based organization (e.g. camera models). These duplicates may be real or soft/hard links. Either way, duplicates within the `destination` directory should be ignored.

So the only duplicates we're looking for are files in `source` that show up somewhere under `destination`.

Is this use case supported by `czkawka`?

**Comment by qarmin** [comment]
Custom selecting/unselecting should work fine(just in `path` or `path + name` write name of source/destination folder).

**Comment by felciano** [comment]
Thanks @qarmin but I don't think that will catch situations like the one below:
```
destination/
  2021/
    January/
      A.jpg

source/
  A1.jpg <-- copy of destination/2021/January/A.jpg (also same as A2.jpg)
  A2.jpg <-- copy of destination/2021/January/A.jpg (also same as A1.jpg)  
  B1.jpg <-- same as B2.jpg
  B2.jpg <-- same as B1.jpg

```
I want to identify `A1.jpg` and `A2.jpg` as duplicates of `A.jpg` in `destination`, and thus safe for removal. However `B1.jpg` and `B2.jpg` are also duplicates, but shouldn't be deleted because they don't match anything in `destination1`.

Have I missed something?

**Comment by geraldew** [comment]
I mention something along this line in [issue #440](https://github.com/qarmin/czkawka/issues/440)
