### ISSUE TITLE
scan usb drive

### ISSUE THREAD

**Issue by stloc** [qarmin/czkawka#403]
Hello,
I have the error "Cannot open dir /media/[user]/[usb]/...."

**Comment by qarmin** [comment]
This should work fine(it works on my computer and pendrive with fat32).
I think that there is problem with permissions of user to that file/drive

**Comment by stloc** [comment]
Hi,
What permissions ?

![image](https://user-images.githubusercontent.com/4832070/128630515-a8005cb2-861a-4a02-9530-3b92858b3f2b.png)

![github](https://user-images.githubusercontent.com/4832070/128630699-d240a285-4017-4049-8732-c2a23316c394.jpg)

**Comment by strelniece** [comment]
Have exactly the same issue.

**Comment by alexislefebvre** [comment]
How did you installed czkawka? If you use the snap package, try this: https://github.com/qarmin/czkawka/issues/217#issuecomment-761580221

**Comment by FilipDominec** [comment]
@alexislefebvre This solved my problem, thanks. I suggest such a message should be printed whenever czkawka reports the trouble! Like this:

    "Cannot open dir ABCDEFG, make sure you gave it the permission using sudo snap connect czkawka:removable-media

**Comment by qarmin** [comment]
In latest version I extended error which should print exactly what failed(e.g. permissions, non existent files etc.).
So if anyone have still this issue, then would be very helpful to post here error from the newest version of app
