### ISSUE TITLE
Consider ahash64 as default(or optional) hasher

### ISSUE THREAD

**Issue by qarmin** [qarmin/czkawka#404]
Looks that ahash can be faster than blake or xxhash due to not needing to be cryptographic secure

**Comment by alexislefebvre** [comment]
> aHash is not intended for network use or in applications which persist hashed values

[Source](https://github.com/tkaitchuck/aHash#goals-and-non-goals)

Hashed values are persisted in the cache, so that would be an issue for czkawka?

**Comment by qarmin** [comment]
Yeah,
As alternative they recommend HighwayHash which is only a little faster in some benchmarks than XXhash(used already as option)
