### ISSUE TITLE
Selecting multiple files for hardlinking?

### ISSUE THREAD

**Issue by pairofcrocs** [qarmin/czkawka#424]
![czkawka](https://user-images.githubusercontent.com/34723037/129914212-c645ff79-9c72-43c2-938a-f97902998ba8.PNG)

If I were to select multiple files, and click the hardlink button, will this link each pair of files, of all that are selected?

Thanks!

**Comment by qarmin** [comment]
Each group of files is independent so hardlinking in this situation(selected 8 files in 4 groups) will create 4 hardlinks and 4 files won't be changed in any way.

For me hard/sym linking between groups doesn't have too much sense

**Comment by pairofcrocs** [comment]
> 
> 
> Each group of files is independent so hardlinking in this situation(selected 8 files in 4 groups) will create 4 hardlinks and 4 files won't be changed in any way.
> 
> For me hard/sym linking between groups doesn't have too much sense

Perfect!

I agree, that wouldn't make any sense to me either.

Keep up the awesome work :)
