### ISSUE TITLE
Hang at the end of a scan

### ISSUE THREAD

**Issue by jasontitus** [qarmin/czkawka#428]
With current HEAD I am seeing a hang after a multi-hour scan on two different machines (both Ubuntu 21.10).  It gets to 100% (but the two numbers are not yet the same '494286/494336' for example).   Even if I hit 'Stop', it never does.  It is just sitting there using 3-4% CPU and never shows the list.  If I stop it sooner (before it gets to 100%, it shows the found duplicates.

If I do an 'lsof' on the process, there are no images open and an 'strace' shows a bunch of 'Resource temporarily unavailable' but it doesn't seem to be an image that is unavailable.  

Example strace output -
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}], 2, 0) = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="5\30\4\0m\354\342\3,1\340\3\372\1\202\0\213\4\6\0n\354\342\3m\354\342\3*\0\0\0"..., iov_len=9432}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 9432
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}], 2, -1) = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\241 \n\200,1\340\3\22\2\0\0`\"\4\0\0\0\0\0.\212\246\377\22\0\0\0\0\0\0\0"..., iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 64
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}], 2, -1) = 1 ([{fd=4, revents=POLLIN}])
read(4, "\1\0\0\0\0\0\0\0", 16)         = 8
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}], 2, 0) = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="5\30\4\0o\354\342\3,1\340\3\372\1\202\0\213\4\6\0p\354\342\3o\354\342\3*\0\0\0"..., iov_len=9432}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 9432
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}], 2, -1) = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\241  \200,1\340\3\22\2\0\0d\"\4\0\0\0\0\0\306\251\251\377\22\0\0\0\0\0\0\0"..., iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 64
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}], 2, -1) = 1 ([{fd=4, revents=POLLIN}])
read(4, "\1\0\0\0\0\0\0\0", 16)         = 8
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}], 2, 0) = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="5\30\4\0q\354\342\3,1\340\3\372\1\202\0\213\4\6\0r\354\342\3q\354\342\3*\0\0\0"..., iov_len=9432}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 9

**Comment by qarmin** [comment]
Can you run in terminal app with this`RUST_BACKTRACE` variable set?
e.g. `RUST_BACKTRACE=full czkawka_gui`

I'm almost sure that app crashes, due internal crash inside image-rs library.
When parsing invalid file, library may panic.

I reported recently two crashes:
- https://github.com/image-rs/image/issues/1535
- https://github.com/image-rs/image/issues/1526
so maybe after in next version will this be fixed.

I think that would be good to find which exactly image cause crashes, to report issue about it in `image-rs` library.
The best way is to split scan into multiple parts to see which file cause crash(cache should fill all the time)

**Comment by jasontitus** [comment]
Any way to just run image-rs on all the images to find the crash?  Doing a split when runs take 12 hours+ is kind of a pain.

**Comment by qarmin** [comment]
https://github.com/qarmin/ImageOpening
needs to be compiled and run with path as argument
```
git clone https://github.com/qarmin/ImageOpening.git
cd ImageOpening
cargo build --release
target/release/image_opening /path/to/folder/with/images
```

**Comment by jasontitus** [comment]
Should I expect it to crash on the bad one or do I need to closely watch the logs for errors (i.e. - does it try and catch errors and move on)?

**Comment by qarmin** [comment]
It should show which exactly image cause crash.
Output should look in this way
```
LLL - Failed to open file files/Untitled46.exr - reason The file extension `."exr"` was not recognized as an image format
OOO - Trying to open files/Untitled90.pbm
TTT - Opening file 'files/Untitled90.pbm' (0 Kilobytes) took '0' took miliseconds
OOO - Trying to open files/Untitled92.pbm
TTT - Opening file 'files/Untitled92.pbm' (0 Kilobytes) took '0' took miliseconds
OOO - Trying to open files/Untitled37.ico
memory allocation of 122406551552 bytes failed
```
log shows that when trying to open `Untitled37.ico`, crash happened

**Comment by jasontitus** [comment]
Unfortunately, it looks like image_opening does not bother opening images that end in uppercase extensions like '.JPG'.  It is running now, but that could very well make it miss the broken ones.

**Comment by jasontitus** [comment]
OK, I edited the code to open '.JPG' (my first time touching Rust code!) and will run it again.  We'll see in 12 hours.

**Comment by jasontitus** [comment]
I found at least one that lists as failing but doesn't core dump the image_open process.  Putting it in a directory with some other images and running czkawka on it doesn't hang though.  I will keep looking for worse corruptions that somehow kill the process.

```
OOO - Trying to open test/band661.jpg
LLL - Failed to open file test/band661.jpg - reason Format error decoding Jpeg: invalid JPEG format: failed to decode huffman code
OOO - Trying to open test/IMG_2788-5.JPG

```

**Comment by jasontitus** [comment]
So it is hung at 100% again after running all night.  Do I just cntrl-c on the console to get the backtrace?  Or is it not going to catch it since it didn't crash?

**Comment by jasontitus** [comment]
Here is the backtrace - 
```
thread '<unnamed>' panicked at 'range start index 255 out of range for slice of length 225', /home/jasontitus/.cargo/registry/src/github.com-1ecc6299db9ec823/gif-0.11.2/src/reader/decoder.rs:251:28
stack backtrace:
   0:     0x55c9a81ab7dc - std::backtrace_rs::backtrace::libunwind::trace::h7f0f727c679b121e
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55c9a81ab7dc - std::backtrace_rs::backtrace::trace_unsynchronized::h27b8207adc787597
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55c9a81ab7dc - std::sys_common::backtrace::_print_fmt::h18c4a15687f3f453
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55c9a81ab7dc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7077f94cc0b2a619
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55c9a81e925f - core::fmt::write::hd1fcbdc89ccede50
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/core/src/fmt/mod.rs:1096:17
   5:     0x55c9a81aae76 - std::io::Write::write_fmt::h3030f95a96ab63e0
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/io/mod.rs:1568:15
   6:     0x55c9a81c0b65 - std::sys_common::backtrace::_print::hce920b6e4ede72f2
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55c9a81c0b65 - std::sys_common::backtrace::print::h63694f3a744810f6
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55c9a81c0b65 - std::panicking::default_hook::{{closure}}::h2f22ad38e825d5e1
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:208:50
   9:     0x55c9a81c0733 - std::panicking::default_hook::hc0998dccd7f968a3
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:225:9
  10:     0x55c9a81c1195 - std::panicking::rust_panic_with_hook::h618d5ded1dbe5ea3
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:591:17
  11:     0x55c9a81abff7 - std::panicking::begin_panic_handler::{{closure}}::h64f3a351a9df3931
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:497:13
  12:     0x55c9a81ab93c - std::sys_common::backtrace::__rust_end_short_backtrace::hf7a8c7450479e920
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55c9a81c0d42 - rust_begin_unwind
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:493:5
  14:     0x55c9a81e8fd1 - core::panicking::panic_fmt::hac8d59bba791921f
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/core/src/panicking.rs:92:14
  15:     0x55c9a81dee12 - core::slice::index::slice_start_index_len_fail::hcd29d73775430f29
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/core/src/slice/index.rs:34:5
  16:     0x55c9a812adcb - gif::reader::decoder::StreamingDecoder::update::h3dd8c89c0eea8594
  17:     0x55c9a80c6db1 - gif::reader::ReadDecoder<R>::decode_next::h3434f19f0a85ab23
  18:     0x55c9a80c5fe0 - gif::reader::Decoder<R>::fill_buffer::h8aa9179829609658
  19:     0x55c9a80c6b1f - gif::reader::Decoder<R>::read_into_buffer::hb6b153a4fdca6237
  20:     0x55c9a80802e8 - <image::codecs::gif::GifDecoder<R> as image::image::ImageDecoder>::read_image::h988a0a2afa24c466
  21:     0x55c9a808bfed - image::image::decoder_to_vec::he23c97b93a438a9f
  22:     0x55c9a80e917e - image::dynimage::DynamicImage::from_decoder::h81a6facfd9603128
  23:     0x55c9a808f806 - image::io::free_functions::open_impl::h8ef7be7b15c30b31
  24:     0x55c9a7fbfb1e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h72d46c3c656e42ee
  25:     0x55c9a800d817 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h875eccc89b9e335f
  26:     0x55c9a800e4fd - <rayon::iter::while_some::WhileSomeFolder<C> as rayon::iter::plumbing::Folder<core::option::Option<T>>>::consume_iter::hcb1f19371b89d069
  27:     0x55c9a8012e6f - rayon::iter::plumbing::bridge_producer_consumer::helper::h207771b135f99976
  28:     0x55c9a7f7fc3b - std::panicking::try::h377b2147b640ce7d
  29:     0x55c9a7fa29ec - rayon_core::registry::in_worker::h6245da2b4b4e1a1b
  30:     0x55c9a80131aa - rayon::iter::plumbing::bridge_producer_consumer::helper::h207771b135f99976
  31:     0x55c9a7f7fc3b - std::panicking::try::h377b2147b640ce7d
  32:     0x55c9a7fa29ec - rayon_core::registry::in_worker::h6245da2b4b4e1a1b
  33:     0x55c9a80131aa - rayon::iter::plumbing::bridge_producer_consumer::helper::h207771b135f99976
  34:     0x55c9a7f7fc3b - std::panicking::try::h377b2147b640ce7d
  35:     0x55c9a7fa29ec - rayon_core::registry::in_worker::h6245da2b4b4e1a1b
  36:     0x55c9a80131aa - rayon::iter::plumbing::bridge_producer_consumer::helper::h207771b135f99976
  37:     0x55c9a7f896a9 - rayon_core::job::StackJob<L,F,R>::run_inline::h934c8f594253de17
  38:     0x55c9a7fa2a68 - rayon_core::registry::in_worker::h6245da2b4b4e1a1b
  39:     0x55c9a80131aa - rayon::iter::plumbing::bridge_producer_consumer::helper::h207771b135f99976
  40:     0x55c9a7f7fc3b - std::panicking::try::h377b2147b640ce7d
  41:     0x55c9a7fa29ec - rayon_core::registry::in_worker::h6245da2b4b4e1a1b
  42:     0x55c9a80131aa - rayon::iter::plumbing::bridge_producer_consumer::helper::h207771b135f99976
  43:     0x55c9a7f807ce - std::panicking::try::hf458d9d011196ef1
  44:     0x55c9a7f8d0e7 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h81da8f2faaf5f6cb
  45:     0x55c9a818d601 - rayon_core::registry::WorkerThread::wait_until_cold::hae65df3e497d57bc
  46:     0x55c9a7fa2aad - rayon_core::registry::in_worker::h6245da2b4b4e1a1b
  47:     0x55c9a80131aa - rayon::iter::plumbing::bridge_producer_consumer::helper::h207771b135f99976
  48:     0x55c9a7f7fc3b - std::panicking::try::h377b2147b640ce7d
  49:     0x55c9a7fa29ec - rayon_core::registry::in_worker::h6245da2b4b4e1a1b
  50:     0x55c9a80131aa - rayon::iter::plumbing::bridge_producer_consumer::helper::h207771b135f99976
  51:     0x55c9a7fd15ad - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hfd58224cc83ba946
  52:     0x55c9a7f7ff05 - std::panicking::try::h5e5b92cfff4bea5c
  53:     0x55c9a7f8cccf - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h6e10f38e91eeaadf
  54:     0x55c9a818d601 - rayon_core::registry::WorkerThread::wait_until_cold::hae65df3e497d57bc
  55:     0x55c9a818c06a - rayon_core::registry::ThreadBuilder::run::hfc16ca62eb3ccc65
  56:     0x55c9a81909e5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1bda46a0dd8eeb8d
  57:     0x55c9a8190f63 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h677a66686edc3122
  58:     0x55c9a81c8098 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfb8a107190e7a33a
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/alloc/src/boxed.rs:1521:9
  59:     0x55c9a81c8098 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hbeb28ee4851e1c4b
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/alloc/src/boxed.rs:1521:9
  60:     0x55c9a81c8098 - std::sys::unix::thread::Thread::new::thread_start::hed3421e00834bfe5
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/sys/unix/thread.rs:71:17
  61:     0x7f0f45d2e450 - start_thread
  62:     0x7f0f45af9d53 - clone
  63:                0x0 - <unknown>
```

**Comment by qarmin** [comment]
Thanks, looks that gif file caused this crash.
I fuzzed some images test gifs, found invalid one and I reported it to https://github.com/image-rs/image/issues/1551

**Comment by jasontitus** [comment]
Could the app be made resilient to format parsing crashes?  Run them in a separate process or something and log the errors?

**Comment by MildPanda** [comment]
I've encountered this issue too. Heading to sleep so I'll read what info you've asked from OP and copy. React to let me know if you want me to do that or let me know if you want something else. 
![czkawka_gui_6nPAP0FOrv](https://user-images.githubusercontent.com/5686244/132121557-e04608bb-b4b8-4b42-bca4-2cc9594e7653.png)

**Comment by MildPanda** [comment]
Hey @qarmin hope all is well over there. Looks like they may have fixed the crash issue https://github.com/image-rs/image-gif/issues/106 unsure if fix has been released yet but regardless they've got it fixed.

**Comment by Erothas** [comment]
So, @MildPanda indicated that the problem has been fixed. But it has been well over a month by now and the issue still persists for me. Is there anything I can do about it?

**Comment by qarmin** [comment]
Problem was fixed, but still isn't available in `image-rs` crate, because there is no new version in crates.io.
Temporary fix is to disable checking for gif files (`*.gif` in excluded items should work)

**Comment by Erothas** [comment]
> Problem was fixed, but fixed version still isn't available in `image-rs` crate. Temporary fix is to disable checking for gif files (`*.gif` in excluded items should work)

Damn, until now? That sure is taking a long time. Is there any ETA on the release?
Also, thank you for the temporary solution! At least it will get me by until the fix is out.

**Comment by qarmin** [comment]
For now I disabled globally `.gif`, `.ico`, and `.bmp` files .
Updated binaries can be downloaded here - https://github.com/qarmin/czkawka/actions

Image-rs authors wants to pack at most as possible features for 0.24 so this is why they don't publish new release since February and I don't have an idea when they finally release it.

**Comment by qarmin** [comment]
This is already "fixed" in latest branch.
When image 0.24.0 will be released and all other crates will be able to support it, I will re-enable blocked expensions
