### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` 

### ISSUE THREAD

**Issue by syss** [qarmin/czkawka#43]
When doing a recursive search over my home directory the GUI crashes with the following:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "H\xE2\xDE\xECuX\xAE\xF2\xC0\xDC2Xpsf\xD0~L(\u{1}"', czkawka_core/src/duplicate.rs:256:92
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I cloned from github on the 2020-10-06T16:45
Program was started with `cargo run --bin czkawka_gu`

is this enough or do you need more debug info?

**Comment by qarmin** [comment]
Should be fixed by 3b63798751d17cdec276f96ff32cd469cdcb7460
