### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by RasmusMathiesen** [qarmin/czkawka#437]
On an M1 Macbook Air after following the installation instructions and starting the program gives this error:

```
./mac_czkawka_gui 
dyld: Library not loaded: /usr/local/opt/glib/lib/libgobject-2.0.0.dylib
  Referenced from: /Users/rasmus/Downloads/./mac_czkawka_gui
  Reason: image not found
zsh: abort      ./mac_czkawka_gui
```
The cli app works fine.
Is there a simple fix or how can I provide more info?

**Comment by willbprog127** [comment]
> Provided packages are only usable for x86_64 mac machines

Thanks.  Can you fix the Intel Mac package so it doesn't give the libgobject errror message? :+1:

**Comment by qarmin** [comment]
The error comes from GTK library, not this app, so I can't do anything with it.
I added info to installation instruction and this is only thing that I can do
