### ISSUE TITLE
Fails to start czkawka

### ISSUE THREAD

**Issue by TitoRifle** [qarmin/czkawka#442]
When I first downloaded it the program worked flawlessly for a couple of days and then yesterday I came to open it but it just wont load. Its icon flashes for a second in the taskbar and the disappears. I tried running as administrator, redownloading and restarting the laptop but nothing works. A quick note though is that the laptop I am running it on is an old laptop I have with windows 10 i3 4005u and 4gb ddr3 ram. The disk usage is almost always at 100% and the ram usage is like 84%. I don't know if that will affect its loading but I thought I'd mention it.

**Comment by qarmin** [comment]
Probably running app from command line should print info why it crashes

**Comment by qarmin** [comment]
Closing due lack of response(without any error I can't do anything)
