### ISSUE TITLE
clean up deleted files

### ISSUE THREAD

**Issue by seb-1204** [qarmin/czkawka#455]
Hello and thank you for making this software!

I used czkawka to clean up my images/photos.

I noticed that I have a 80GB large snap folder of czkawka.
`/home/me7/snap/czkawka/533/.local/share/Trash/files` 

I could not find any option to clean up or delete them in the software. I assume this is some form of trash? 

How do I know if I can delete/clean up these folders?

**Comment by qarmin** [comment]
There is an option in settings to enable storing deleted files in trash, but is disabled by default(must be disabled to be able to remove files permanently)
![Screenshot from 2021-11-21 10-23-18](https://user-images.githubusercontent.com/41945903/142756585-a403d1a6-7ef6-47ec-a6de-b25ab7195792.png)

I think that snap trash files should be visible in main trash folder but I'm not sure about it.
For now if files are not visible in trash, probably the only option is to go into snap trash folder and remove it manually.

**Comment by seb-1204** [comment]
My bin/trash has only 150MB in it so I will go and delete these files manually.
Thank you for the comment/explanation.
