### ISSUE TITLE
Documentation says prebuilt binary doesn't work on M1 mac

### ISSUE THREAD

**Issue by northnose** [qarmin/czkawka#475]
The [installation instructions](https://qarmin.github.io/czkawka/instructions/Installation.html) state:

>  If you use want to use app on ARM machine e.g. Mac M1, you can’t use prebuilt binaries, because they were compiled for x86_64 architecture. You need to compile Czkawka manually to get proper binaries.

It does actually work though (I just tried). You just have to be sure the x86_64 dependencies are installed:

```
$ arch -x86_64 /usr/local/bin/brew install gtk+3 adwaita-icon-theme ffmpeg librsvg
```

**Comment by qarmin** [comment]
Changed information about it in https://github.com/qarmin/czkawka/commit/fce8ba8ddfc10c545e15ecd4f0d1f18fb3993fff
