### ISSUE TITLE
Is there a way to not scan for duplicates inside each respective folder that I added. 

### ISSUE THREAD

**Issue by tvvoty** [qarmin/czkawka#492]
Sorry, if it's not appropriate to ask this in the issues.
I have a folder with files recovered from a hard drive that I accidentally wiped out and which I want to back up. And I also have a folder where I back up things. I want to check what I have already backed up that is present in the recovered folder in order not to waste space. Is there a way to do it? So like, I want czkawka to search for duplicates that are present in the folders A and B, but I don't want it to search if there are duplicates in the folder B itself.

**Comment by willhubs** [comment]
In that case you want to add both folders, then search both folders for duplicates, then in the selection you will select custom and select folder A using wild-cards.
Then you just have to make sure that you don't have any that have all selected within a group.  Which would be made infinitely easier if they choose to implement https://github.com/qarmin/czkawka/issues/444

**Comment by willhubs** [comment]
Add both folders, search for duplicates.
Then use select, select custom and use wildcards to only select duplicates that are in folder A.
