### ISSUE TITLE
Odmowa dostępu przy próbie usunięcia zbędnych plików

### ISSUE THREAD

**Issue by streambase-project** [qarmin/czkawka#537]
Pomimo otwarcia programu jako administrator program przy próbie usunięcia przeze mnie zbędnych wyników, wyświetla komunikat "Failed to remove, you don't have permissions" lub "Odmowa dostępu" i temu podobne. Jak to rozwiązać?

**Comment by qarmin** [comment]
Windows nie pozwala usuwać niektórych plików, nawet gdy program jest uruchomiony z uprawnieniami administratora.
Tyczy się to plików systemowych czy chociażby takich które są otwarte w innym programie.
Oprócz tych dwóch przypadków, nic innego mi do głowy nie wpada co byłoby przyczyną takiego zachowania.
