### ISSUE TITLE
Compare images mode

### ISSUE THREAD

**Issue by qarmin** [qarmin/czkawka#543]
I think about adding dialog, which would allow to compare images and later select/unselect them.
Requirements:
- images only can be selected/unselected - deleting/moving etc. is forbidden - selection of image should result in selecting it in treeview of current mode (same as unselecting)
- images should be resizable - for now I don't know how to do this in GTK - https://discourse.gnome.org/t/how-to-resize-image-in-gtk-rust/5032/3 may help
- images from current group(and also maybe groups +1 and -1) should be cached in memory to be able to move fast between images, without needing each time load them from disk(like this is done in image preview)
- feature should be available only in similar images tool

I already started to create GUI for it basic on this advanced image, but I'm not exactly sure about exact place of every button etc.:

![RRRR](https://user-images.githubusercontent.com/41945903/147920146-5359c9b7-a4de-4eaf-8885-fcfe407ca801.png)

I based on this images
![Awesome-Duplicate-Photo-Finder](https://user-images.githubusercontent.com/41945903/147920384-c573a8ef-db05-41fe-957c-5164759ea245.jpg)
![Guiffy-Image-Diff-best-image-comparison-software-interface](https://user-images.githubusercontent.com/41945903/147920400-73a19aa4-5a06-4897-9983-d0f598b1009b.png)
![3931913_1](https://user-images.githubusercontent.com/41945903/147920417-38a19ef8-9a04-44d6-ba41-c83ed46badef.png)

**Comment by chchia** [comment]
could also consider to add a button "Not Similar", which will mark that two images as none similar so we dont have to compare it again in future.

**Comment by qarmin** [comment]
Implemented by #568

Removing from showing not similar images with similar hash, needs to be implemented by adding feature to core of app, because compare images tool is only wrapper to show current data.
