### ISSUE TITLE
markdown table seems not rendered correctly in the compilation guide

### ISSUE THREAD

**Issue by ZhangChaoWN** [qarmin/czkawka#565]
table format is broken: 
```| Program | Min | What for | |———|——|——————————————————————————-| | Rust | 1.53 | Czkawka, aims to support the latest available version of Rust on Ubuntu 20.04 | | GTK | 3.24 | Only for the GTK backend |"```
seems markdown table was not rendered

**Comment by alexislefebvre** [comment]
I see the table here: https://github.com/qarmin/czkawka/blob/277bb8b39a28140c5ac226e86a8b0a5982d1f9e8/instructions/Compilation.md#requirements
