### ISSUE TITLE
Cannot open dir /home/butch/.ssh, reason Permission denied (os error 13)

### ISSUE THREAD

**Issue by bigbutch** [qarmin/czkawka#569]
Can you tell me what I need to do it looks like I don't have sudo permission. What do I need to do to be able to scan all dirs?

**Comment by bigbutch** [comment]
I am running Ubuntu 20.04 and I downloaded Czkawka from software center.

**Comment by bigbutch** [comment]
Just to let you know I think program is great. I downloaded thru app Magik but I didn't get icon. How can I get icon for this program. I am running Ubuntu 20.04. Everything else seems to be great just can't figure how to get icon to run  software

**Comment by bigbutch** [comment]
If you could help me I would greatly appreciate it

**Comment by qarmin** [comment]
Icon in taskbar will be visible in 4.0 version - https://github.com/qarmin/czkawka/commit/c6d246c02e44c4cc68fd4db37dec2699cdf17a06#diff-d28797f72578ffadd627ab69c64f90cb33c8c9529221dc2d9a905d4e74a27b29 (I plan to release it in this or next month)

Binaries cannot have bundled icons, so the only way is to use desktop icons - https://amljs.medium.com/how-to-create-a-desktop-icon-on-ubuntu-or-debian-based-systems-333c82464683
Desktop file - https://github.com/qarmin/czkawka/blob/master/data/com.github.qarmin.czkawka.desktop
Icons - https://github.com/qarmin/czkawka/tree/master/data/icons
