### ISSUE TITLE
Similar videos function not showing

### ISSUE THREAD

**Issue by slyguy65** [qarmin/czkawka#570]
Downloaded the windows .zip version and similar videos isn't there.
I put ffmpeg and probe and play into the main folder with all the .dll files and exe file, still nothing.
Where do I put ffmpeg or where can I direct the program to look for ffmpeg and use it?

**Comment by qarmin** [comment]
Similar Videos feature will be available in 4.0 version which is not released yet.
Nightly builds can be downloaded from action tab.

Example build to download (at the bottom) - https://github.com/qarmin/czkawka/actions/runs/1674980092
