### ISSUE TITLE
Files and folders reported as empty can they be safely deleted.

### ISSUE THREAD

**Issue by bigbutch** [qarmin/czkawka#584]

**Comment by bigbutch** [comment]
Files and folders reported as empty can they be safely deleted?

**Comment by bigbutch** [comment]
Files and folders reported as empty can they be safely deleted?

**Comment by qarmin** [comment]
It depends,
I don't recommend to remove empty folders and files in system directories like `/` `/var` `C:\Windows` etc. and app directories like `C:\Users\user\Appdata`, `C:\Program Files` or `~/user/.config`, `/usr/`
I suggest to use this tools to remove data only from your folders with data e.g. pendrive with random photos and files or home directory.

**Comment by bigbutch** [comment]
Hello and thank you for your advice. I really like your program and again thanks for your time and such a nice program. I am anxiously waiting on version 4.0. I am hoping for an icon because I installed thru appimage which didn't install a icon. I am wondering if when 4.0 comes out should I install it in Linux Ubuntu 20.04 a different way?

Butch Owens

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by bigbutch** [comment]
Hello and thank you for your advice. I really like your program and again thanks for your time and such a nice program. I am anxiously waiting on version 4.0. I am hoping for an icon because I installed thru appimage which didn't install a icon. I am wondering if when 4.0 comes out should I install it in Linux Ubuntu 20.04 a different way?

Butch Owens
