### ISSUE TITLE
symbol lookup error for 4.0 in GNU/Linux

### ISSUE THREAD

**Issue by penyuan** [qarmin/czkawka#595]
I've used previous versions successfully under RHEL GNU/Linux 8.5 with no problems. But the latest `linux_czkawka_gui` 4.0.0 binary release (non-Appimage) gives me this error and fails to start: 

```
./linux_czkawka_gui: symbol lookup error: ./czkawka_gui: undefined symbol: gtk_event_controller_key_new
```

How do I troubleshoot this? Thanks!

**Comment by qarmin** [comment]
Since version 4.0.0, GTK 3.24 is required(event controller is not available in GTK 3.22).
This change was required because I wanted to simplify possible conversion to GTK 4(which only allows to handle key events with event controller)
