### ISSUE TITLE
I installed through appimage 3.3.1 

### ISSUE THREAD

**Issue by bigbutch** [qarmin/czkawka#599]
I am anxiously waiting on version 4.0. I am hoping for an icon because I installed thru appimage which didn't install a icon. I am wondering if when 4.0 comes out should I install it in Linux Ubuntu 20.04 a different way?
How would be best way for me to update to 4.0. As you can tell I am new at this and just want to do it right.

Butch Owens

**Comment by bigbutch** [comment]
Hello qarmin ,  I went ahead and removed 3.3.1 and reinstalled 4.0. I still do not have icon if you know how I can get one after installing 4.0 in appimage I would definitely would appreciate some instructions?

**Comment by qarmin** [comment]
Already in CI there is set icon file, but I have no idea why it not works

https://github.com/qarmin/czkawka/blob/37b61b0c4c5418e16c0e443e1dd4731afeca40a9/.github/workflows/linux.yml#L233

**Comment by bigbutch** [comment]
Hello and thank you.I have that icon, my problem is getting it in my favorites. I will continue opening from file manager. Again thank you for you help and patients with me.

Butch

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by newhinton** [comment]
@qarmin I have the same issue with the alternative appimage. I assume that one bundles gtk4? The "normal" apk does show an app-icon in the explorer, but the alternate does not. (Also, and more importantly: It also does not show an appicon on the taskbar.)

I am using Kubuntu 22.04.

**Comment by bigbutch** [comment]
Hello all, I am running 22.04 and I installed it thru Snap. And so far it seems to be running ok.

Thanks
​Butch Owens

Sent from Proton Mail mobile

-------- Original Message --------
