### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by qarmin** [qarmin/czkawka#6]
It will be really great if Czkawka will be available in Debian and Ubuntu repository.
Maybe someday.

**Comment by Baltix** [comment]
I can help with creating debian/ubuntu packages - I think it would be nice to cooperate with https://linuxuprising.com team - they already noticed Czkawka - https://www.linuxuprising.com/2021/03/find-and-remove-duplicate-files-similar.html and have repository for Ubuntu packages (PPA), see https://launchpad.net/~linuxuprising/+archive/ubuntu/apps

**Comment by qarmin** [comment]
It is already available in PPA - https://launchpad.net/~xtradeb/+archive/ubuntu/apps/
