### ISSUE TITLE
czkawka doesn't delete/move/symlink duplicate files after pressing buttons since 3.2 release

### ISSUE THREAD

**Issue by Baltix** [qarmin/czkawka#606]
czkawka doesn't Delete/Move/Symlink duplicate files after pressing buttons since 3.2 release - latest 4.0 release also has this issue.
Delete/Move/Symlink buttons doesn't work - nothing happens after pressing these buttons in Duplicate files section - see screenshot 
![czkawka-find-duplicates-doesnt-delete-move](https://user-images.githubusercontent.com/1792089/150663936-20487650-7048-4795-9ba1-9116029d045b.png)

I have this issue on all Ubuntu Linux 20.04 computers I've tested.

Latest release without this issue is 3.1 - https://github.com/qarmin/czkawka/releases/tag/3.1.0

I have some experience in developing software, but no experience with Rust, but I can try to help to debug (or something) if you tell me how ;)

Thanks for nice tool,
Mantas Kriaučiūnas
Technologijų Tinklas - tinklas.eu

**Comment by chchia** [comment]
you need to select file that you want to delete?

![image](https://user-images.githubusercontent.com/1291771/150717749-47c8b8a1-4be4-4aef-857c-1d0e1c5ebf42.png)

**Comment by qarmin** [comment]
Yes, this issue is caused by changes in selecting method in one of older Czkawka versions

**Comment by fromSmolsoft** [comment]
What was the fix ?  
I tired Flatpack version on Linux Mint and Czkawka just "pretends" to delete or move files but no actual change happens in file system. In other words it's good for finding dupes but can't delete them.

**Comment by kattivius** [comment]
I have the same situation in vesion 6.1.0
I am spending all the afternoon to clean up the USB drive.
It finds duplicates but dont delete the files when requested.
Tested:
created a folder called Duplicates.
Find duplicates and move duplicates in Duplicates folder. Files are copied, not moved. When I look for the same file, is in both or more location.
Search for duplicates again. It seems it only find the original and the duplicate in the Duplicate folder.
But I do find the duplicate also in the older location/path. 
So I ask for Delete duplicates in the Duplicate folder (selecting the newer created files). The correct duplicates are selected. I request Delete selected files. But the file are not deleted.
Any suggestion?

**Comment by djpeter84** [comment]
encountered this issue today. i have to manually go the the parent folder of each to actally delete the files. Has Dev responded?
