### ISSUE TITLE
Windows video search opens a new window for every video file

### ISSUE THREAD

**Issue by SMylk** [qarmin/czkawka#608]
When I use similar search from GUI it opens a new console window for every file, is it possible to hide these or do everything in 1 window.
So there is no constant popup when a job is running making the system unusable.

**Comment by qarmin** [comment]
This is problem with ffmpeg, because on Windows it opens every time new console window when executing command(on Linux and probably also MacOS this problem doesn't exists).

**Comment by Farmadupe** [comment]
I have updated crate ffmpeg_cmdline_utils to fix this issue and push it to crates.io (v0.1.1) The issue should be resolved if Czkawka is rebuilt using latest version of this crate.
