### ISSUE TITLE
Installation of Czkawka

### ISSUE THREAD

**Issue by bigbutch** [qarmin/czkawka#609]
Hello Garmin, I have Czkawka 4.0 installed in Ubuntu 20.04 with appimage. With appimage I can't install icon in my favorites do to how appimage works. My question is would I be better off deleteing from appimage and reinstalling with flatpak? I guess what I am asking which would be better to install and run Czkawka with? If I understand you correctly flatpak with all necessary files is running correctly all tools?

Butch

**Comment by willhubs** [comment]
I prefer installing from the xtradeb PPA
https://xtradeb.net/

sudo add-apt-repository ppa:xtradeb/apps
sudo apt-get install czkawka

**Comment by alexislefebvre** [comment]
You can also download `linux_czkawka_gui` from [releases](https://github.com/qarmin/czkawka/releases), then launch it.

**Comment by bigbutch** [comment]
Hello, thank you for your responce. About 4 days ago I changed from appimage to flatpak. So far it seems to be working OK I am now able to put icon in favorites and also update thru flatpak. Better than what I could do with appimage. Again thanks so much for your help very much appreciated.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by bigbutch** [comment]
Hello, thank you for your responce. About 4 days ago I changed from appimage to flatpak. So far it seems to be working OK I am now able to put icon in favorites and also update thru flatpak. Better than what I could do with appimage. Again thanks so much for your help very much appreciated
