### ISSUE TITLE
Add searching for similar pictures

### ISSUE THREAD

**Issue by qarmin** [qarmin/czkawka#61]
This is implemented in dupeguru

**Comment by Syfaro** [comment]
Some thoughts about doing this, coming from a person that runs a similar image matching service with 10s of millions of images.

* You can use perceptual image hashing to generate hashes to compare
  - There's the [img_hash](https://crates.io/crates/img_hash) crate to do this in Rust 
  - Perceptual hashes are very resistant to compression and resizing, but are completely incapable of handling cropping
* Hashes can be compared with hamming distance 
  - If there's few enough images, you could compare each hash against every other hash, but this scales _very_ poorly
  - You can use a [bk-tree](https://crates.io/crates/bk-tree) to index all of the hashes and very quickly find similar images
  - Indexing 23,543,939 images with 64-bit hashes is using 3.4GB of RAM for my service
* I personally find that with 64-bit hashes a hamming distance of up to 3 indicates a high probability of it being the same image

**Comment by qarmin** [comment]
Implemented by #69, but for me it is still a little too slow
