### ISSUE TITLE
Big files option - add image only, video only, audio only options

### ISSUE THREAD

**Issue by RDKRACZ** [qarmin/czkawka#629]
I'm not sure where these options should be in the UI but I would like to request a feature that allows looking for the biggest images or videos.
As for now, Czkawka will show the largest files - it doesn't take into account I would like to see the heaviest images, not videos.

Also, the name of this functionality shouldn't be Biggest files (instead Big files?)

**Comment by RDKRACZ** [comment]
Or you can just make it separate like for the similar files option - Big images and Big videos instead of Big files.

**Comment by alexislefebvre** [comment]
[Baobab](https://en.wikipedia.org/wiki/Disk_Usage_Analyzer) on Linux or [WinDirStat](https://windirstat.net/) on Windows can be used to do this.

**Comment by RDKRACZ** [comment]
I haven't used baobab for some time but I don't remember having that (showing only images or videos) functionality and I believe it can't do this. I quickly tested k4dirstat and filelight and they too lack this option.

**Comment by qarmin** [comment]
There are special macros in Items Configuration tab, that allows to use VIDEOS, IMAGES etc. which will use specific set of extensions in scan
