### ISSUE TITLE
Faster Size+Hash search for duplicates

### ISSUE THREAD

**Issue by x2es** [qarmin/czkawka#640]
I am sorting large dataset with czkawka and see similar picture.

When I am searching duplicates by **Size** it returns, for say 2000 duplicates and respond with result very fast.
By **Hash** search on the same dataset czkawka scans about 9000 files on "partial hash" stage and 5000 files on "full hash" stage.

Why not limit scan by dataset which may be found by **Size**?

**Comment by qarmin** [comment]
Scan is already optimized in such way.

30 000 files to check -> 20 000 files with same size -> 15 000 with same prehash -> 10 000 with same full hash 

Each step use only data available in previous step.

If there is written in GUI - "Found 40 000 duplicates in 20 000 groups", then 60 000 of files with same size was found(40 000 only means duplicates, another 20 000(one from each group) are threaten as originals)

So number visible in partial hash is just a number of all results, in opposite to number of duplicates shown in GUI label

Images:

![Screenshot from 2022-04-11 19-24-02](https://user-images.githubusercontent.com/41945903/162795684-0121a346-5ce2-4ade-9726-d656dec780d0.png)

![Screenshot from 2022-04-11 19-21-40](https://user-images.githubusercontent.com/41945903/162795667-d5e391f1-6feb-48c5-acd0-4d186b571ec7.png)
