### ISSUE TITLE
Allow zoom on image comparison or escale image to window when resized

### ISSUE THREAD

**Issue by Laesx** [qarmin/czkawka#646]
I think you should be able to at least zoom the image in the comparison window or that it would escale to the maximum available bounds when you resize the comparison window, because it looks way too small to tell apart small details as you can see here.
![imagen](https://user-images.githubusercontent.com/51269470/157699671-3af9f828-d823-4e0a-9af1-a5f0396286db.png)

**Comment by phhowe17** [comment]
Upvote for this.  Also would be nice to be able to toggle between images as a flip comparison for very similar images.

**Comment by alexislefebvre** [comment]
@phhowe17 It looks like a feature request, I think you should create another issue.
