### ISSUE TITLE
Select checkbox doesn't seem to work on some paths

### ISSUE THREAD

**Issue by zecamigo** [qarmin/czkawka#650]
Hi there,

I'm using the GUI version 4.0.0 on Debian.

It seems it is not possible to select files on certain paths?

e.g. /media/user/disk/... ; /media/user/disk2

Although selection is possible in the computer's internal disk /home/user/directory

From what I see it seems to affect external USB drives. In case this might be related, external USB unit's format is NTFS and FAT32.
Internal disk is a Linux LVM.

Thanks, hope this helps develop your wonderful project.

**Comment by alexislefebvre** [comment]
How did you install czkawka? If you used snap, see [this note](https://github.com/qarmin/czkawka/blob/4.0.1/instructions/Installation.md#snap).

**Comment by zecamigo** [comment]
@alexislefebvre 

Sorry, forgot to mention, it's from flathub via gnome software centre. Yes now I notice it's sandboxed.

**Comment by zecamigo** [comment]
What would be the recommended installation method?

**Comment by alexislefebvre** [comment]
You can download the binary, make it executable then run it (this is not the recommended installation, only one of the several ways):

```bash
curl --location --remote-name https://github.com/qarmin/czkawka/releases/download/4.0.0/linux_czkawka_gui
chmod +x ./linux_czkawka_gui
./linux_czkawka_gui
```

**Comment by zecamigo** [comment]
I apologize this is probably not a bug, but a feature, quite literally. 

I think Items from reference folders can not be selected by design, I'm guessing?

Solving out. And thank you for your time.
