### ISSUE TITLE
[Feature Request] Broken Files - Add option to rename files with incorrect file extension

### ISSUE THREAD

**Issue by dnutan** [qarmin/czkawka#651]
I think it would be a nice feature to be able to correct the file extension on those Broken Files where the file extension does not match the file header signature / magic number (not 100% accurate due to some file formats using container formats).
This could work for images, .CHK files, etc. either applying a suggested file extension to all selected files or with a custom file extension (on GUI an extra editable column with suggested extension).

**About File Signatures**
* https://en.wikipedia.org/wiki/List_of_file_signatures
* https://www.garykessler.net/library/file_sigs.html
* https://www.nationalarchives.gov.uk/PRONOM/Default.aspx
* https://filesignatures.net/index.php?page=all  (webpage with unsecure certificate warning)

**Some programs that can detect file signatures**
* [TrID](https://mark0.net/soft-trid-e.html)
* `file` command (based on libmagic library) (GNU/Linux)
* `exiftool` (for images, can also extract metadata useful to rename filename by date or other fields)
* [DROID](https://github.com/digital-preservation/droid)
* Windows PowerShell  (`Get-FileMetaData -Signature`)
* File Carving and File Recovery software 

- https://tika.apache.org/2.3.0/detection.html

---
Feature Request slightly related to #309

**Comment by qarmin** [comment]
Most tools are written in C/C++ and similar, so integration can be problematic.

From Rust side, probably something like https://crates.io/crates/mime_guess can be used

**Comment by dnutan** [comment]
For Rust, maybe something like [mime2ext](https://crates.io/crates/mime2ext), [infer](https://crates.io/crates/infer) (or [tree_magic](https://crates.io/crates/tree_magic) or [tree_magic_mini](https://crates.io/crates/tree_magic_mini)) would help doing the job.
Regards.
