### ISSUE TITLE
No icons for the windows GUI.

### ISSUE THREAD

**Issue by Zorbatron** [qarmin/czkawka#670]
After extracting the ZIP and running Czkawka, none of the buttons have their proper icon and are instead replaced by ![Screenshot 2022-04-09 201014](https://user-images.githubusercontent.com/46525467/162595785-fcbf98fe-bb50-4a72-81b0-53cd02b68550.png). I believe this issue may be related: https://github.com/qarmin/czkawka/issues/588

**Comment by qarmin** [comment]
I forgot to close this issue, because should be fixed by https://github.com/qarmin/czkawka/pull/659

I have no idea why on some(probably most) computers with windows, there were available all icons, but on some(I tested it on 2 different windows 10 machines) there are unavailable.
