### ISSUE TITLE
windows symlink right problem ends in deleting duplicate files

### ISSUE THREAD

**Issue by eTernal1911** [qarmin/czkawka#688]
Tryed the symlink feature, got this error message:

Failed to delete file ⁨F:\temp\2021.PNG⁩, reason ⁨Dem Client fehlt ein erforderliches Recht. (os error 1314)⁩

every duplicate file gets deleted not symlinked.

**Comment by qarmin** [comment]
Should be fixed in master

**Comment by AndroYD84** [comment]
I had encountered this error message "**Failed to delete file X, reason A required privilege is not held by the client. (os error 1314)**" with the latest **7.0.0 release** ( windows_czkawka_gui_gtk_46.zip ) under Windows 11, I'm not sure what causes this error as processing a small number of files didn't cause this, but processing a huge amount of duplicates did (>20k).
It also deleted every duplicate files it found while preserving the first file in the group as it's the one meant to get symlinked, luckly I saved the list as a JSON after the scan ("results_duplicates_pretty.json") so I created a python script where you can feed this JSON file and it will generate all the missing symlinks it finds.

```
import os
import json

# Load JSON data from a file with explicit UTF-8 encoding
with open('duplicates.json', 'r', encoding='utf-8') as file:
    data = json.load(file)

# Dictionary to store errors
errors = {
    "missing_first_file": {},
    "symlink_error": {}
}

def create_symlink(target, link_name):
    try:
        os.makedirs(os.path.dirname(link_name), exist_ok=True)
        os.symlink(target, link_name)
        print(f'Symlink created: {link_name} -> {target}')
    except FileExistsError:
        print(f'Symlink already exists: {link_name} -> {target}')
    except Exception as e:
        print(f'Failed to create symlink {link_name} -> {target}: {e}')
        error_type = type(e).__name__
        if error_type not in errors["symlink_error"]:
            errors["symlink_error"][error_type] = []
        errors["symlink_error"][error_type].append({
            "target": target,
            "link_name": link_name,
            "error": str(e)
        })

# Iterate through the JSON data
for size, duplicates in data.items():
    for group in duplicates:
        if not group:
            continue

        # First file in the group
        first_file = group[0]['path']
        
        # Check if the first file exists
        if not os.path.exists(first_file):
            print(f'First file does not exist: {first_file}')
            if size not in errors["missing_first_file"]:
                errors["missing_first_file"][size] = []
            errors["missing_first_file"][size].append(first_file)
            continue

        # Create symlinks for the rest of the files in the group
        for file_info in group[1:]:
            duplicate_file = file_info['path']
            
            if not os.path.exists(duplicate_file):
                create_symlink(first_file, duplicate_file)
            else:
                print(f'File already exists: {duplicate_file}')

# Save errors to a JSON file
with open('symlink_errors.json', 'w', encoding='utf-8') as error_file:
    json.dump(errors, error_file, indent=4)

# Note: Ensure to have the necessary permissions to create symlinks and run this script with appropriate privileges.
```

This helped me repair all the files that were supposed to get symlinked successfully.
The script starts by loading a file called "duplicates.json", it's basically "results_duplicates_pretty.json" where I removed folders I'm not interested in checking, but you can load it as is, it's non destructive). For each group, the script looks at the first file listed and tries to see if the other files in the group are still there. If a file is missing, the script creates a symlink that points to the first file in the group. Before creating a symlink, the script checks to make sure the first file in the group isn't missing. If it is, the script skips creating symlinks for that group. The script also makes sure there's a folder to put these symlinks in, and if the folder doesn't exist, it creates it. After the script finishes, if there were any problems during the process, it saves a report called "symlink_errors.json" to tell you what went wrong. Hope this helps anyone who needs it.
