### ISSUE TITLE
Music Duplicates search gets stuck on "Reading Tags" phase

### ISSUE THREAD

**Issue by sleepwakecycle** [qarmin/czkawka#699]
I'm doing an Approximate Comparison search by Title, Artist, and Length. Each time, a few seconds after starting the search, it gets stuck at 98% through while reading the tags. I've let it run for upwards of 30 minutes with no change. The "Stop" button doesn't work, I have to end it through task manager. I've tried this several times, with the same result.

**Comment by qarmin** [comment]
I think that app crashes in one thread when reading tags from file.
Can you check which exactly files causes this?

**Comment by sleepwakecycle** [comment]
How do I check what file causes the crash? I've narrowed it down to one folder, but the folder contains 1,831 files, so I'm not sure which one it is.

**Comment by qarmin** [comment]
The fastest way is copying half of checked folders to another and checking if this one causes problems.

**Comment by sleepwakecycle** [comment]
Ok, I found the 2 files that were causing the crash. Is there a way I can fix the files, so they can be read by Czkawka without crashing?

**Comment by qarmin** [comment]
The only thing that you can do is to ignore this files, by avoiding scanning them or just directly pointing at them in Excluced Items field
Can you post this files here, to be able to check what the problem is?

**Comment by sleepwakecycle** [comment]
I can't post them, they're M4As and GitHub's giving me the error message "We don't support that file type." I'll just manually exclude them. Thank you!

**Comment by qarmin** [comment]
File can be zipped and then send via github.

With example file I could fix this bug, so excluding items won't be needed anymore

**Comment by sleepwakecycle** [comment]
Ok, here are the files. Thanks again

[Czkawka glitch files.zip](https://github.com/qarmin/czkawka/files/8592423/Czkawka.glitch.files.zip)
