### ISSUE TITLE
Similar images preview does not work for uppercase JPG

### ISSUE THREAD

**Issue by timohuovinen** [qarmin/czkawka#703]
The similar images function is amazing and very useful, though it's inconvenient that the image preview works for `.jpg` files but not `.JPG` files (and the same applies to .PNG .GIF .BMP, .JPEG)

**Comment by qarmin** [comment]
This was already fixed by https://github.com/qarmin/czkawka/pull/694

Nightly version of app can be downloaded from actions - https://github.com/qarmin/czkawka/actions

**Comment by timohuovinen** [comment]
Sorry for the beginner question, but how do you download an app from actions?

**Comment by qarmin** [comment]
To download latest version from repository is required to choose binaries from branch `master`(at the bottom of image) for any available OS
![Screenshot from 2022-04-29 17-30-33](https://user-images.githubusercontent.com/41945903/165976616-dae9cf0d-e3dc-4a01-9873-30368e29001f.png)
At the bottom are prepared compiled binaries packed in zip files
![Screenshot from 2022-04-29 17-30-34](https://user-images.githubusercontent.com/41945903/165976694-b9416885-3302-4e2d-bd60-ab70609a8642.png)
