### ISSUE TITLE
doesn't find duplicates within a single hierarchy

### ISSUE THREAD

**Issue by rramstad833** [qarmin/czkawka#712]
Hi there, I have one 10 TB drive with music files on it, and I have multiple copies of the same material on it in different directories.

I know that there are duplicates because of the way files were migrated to it -- and I can use "diff -r -s" to see many identical files.

I loaded up Czkawka hoping that it would be a lot faster than manual diffs particularly as diffs with both directories on the same filesystem are super slow because of the way the disk is accessed.

For the life of me I can't get Czkawka to display a single duplicate of any kind.  It's really odd.

I have one included folder H: with the recursive box checked.

When I click on Duplicate Files and do Search, it has pretty extensive scanning details and the scans take a long time -- the first time it took overnight, now it takes maybe 30 minutes -- but no results appear in the GUI.

I am using the GUI on Windows 10 and the latest version 4.1.0 from the ZIP.

Any suggestions as to things to try most welcome.  I am wondering if maybe I just have a degenerate case?  I removed the default location setting of searching the Czkawka directory -- as I don't need to analyze that directory -- and added the one hard drive that I know contains many duplicates, and I get nothing at all for results.

**Comment by rramstad833** [comment]
Strange.  I just restarted Czkawka for the third time, and tried scanning for what is probably the fifth or sixth time, and I now seem to have results.  I have no idea what is going on!  Sorry to bother you.

**Comment by Cantello** [comment]
Same here, after restarting several times I got results. I have the same setup, one folder with probably many duplicate photos. Thanks for the suggestion with regards to restarting the app. Using GUI on Windows 11 and latest czkawka version.
