### ISSUE TITLE
Visible dupes not getting detected

### ISSUE THREAD

**Issue by Dullitwin** [qarmin/czkawka#714]
I found some files, which couldn't be detected no matter the setting even though they are clearly visible dupes. It's thousands of files, which are like this. Potential bug?

I uploaded some of those random pictures to a file sharing service so it's not changed by github, maybe you guys can take a look for yourself - very intriguing!

https://easyupload.io/m/d6x8ox
pw = admin123

**Comment by qarmin** [comment]
The problem in that pictures is caused by using rotate property in exif data(one in group).

GTK/Image-rs seems to not care about exif data, so looks that I will need to check for this property manually

**Comment by dariox86** [comment]
This seems a duplicate of issue #675. Another important missing feature: in addition to rotated images, **flipped images are not detected**.
