### ISSUE TITLE
can't delete empty directory if there is only one item

### ISSUE THREAD

**Issue by loneghost161** [qarmin/czkawka#716]
if there is only one item in empty dir you can't delete it. if there are multiple item you can't delete the first item only, you can delete the first item if you delete it with the other item but the sum of the chosen item is n-1 in the confirmation dialog

**Comment by GregLeonhardt** [comment]
"if there is only one item in empty dir you can't delete it."  Not sure about the other stuff loneghost161 is talking about.

When "Empty Directories" is selected and there is only a single directory listed in the output screen.  I am able to select it (check mark in the box) but the "Delete" button does nothing.  If a second empty directory is created and the scan restarted; both directories can then be deleted.
