### ISSUE TITLE
Does not recognize .wepb image files

### ISSUE THREAD

**Issue by phhowe17** [qarmin/czkawka#717]
Scanning for similar images czkawka does not scan .webp formatted images.  see https://developers.google.com/speed/webp/gallery1 for example images.

**Comment by alexislefebvre** [comment]
What version are you using?

The support of webp was added in version [3.2.0](https://github.com/qarmin/czkawka/blob/642a6369f3daa77de7b72235d35a0cb32aa9470b/Changelog.md#version-320---07082021r), see #396.

**Comment by qarmin** [comment]
It was disabled in one of previous versions due really bad support in image-rs library(0.23.0)
Looks that in 0.24 version it may be usable enough to reenable due this PR's:
- https://github.com/image-rs/image/pull/1685
- https://github.com/image-rs/image/pull/1624

**Comment by phhowe17** [comment]
Currently using 4.1.0

**Comment by qarmin** [comment]
The biggest problem is that GTK doesn't support webp - https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/103
Out of tree webp loader is not supported in most of distros, so I can't also use it - https://github.com/aruiz/webp-pixbuf-loader

**Comment by alexislefebvre** [comment]
> It was disabled in one of previous versions due really bad support in image-rs library(0.23.0) Looks that in 0.24 version it may be usable enough to reenable due this PR's:

My bad, I didn't see that it was disabled in [3.3.0](https://github.com/qarmin/czkawka/blob/642a6369f3daa77de7b72235d35a0cb32aa9470b/Changelog.md#version-330---20112021r). :bow:
