### ISSUE TITLE
FFmpeg opens a bunch of windows, not running in background

### ISSUE THREAD

**Issue by MidnightDesigns** [qarmin/czkawka#729]
I tried running the "similar video" search earlier and it spammed my desktop with a bunch of separate windows, instead of running in the background. The ffmpeg and ffprobe are launching windows in the foreground, not the background. I'm running Czkawka version 4.0.0 and FFmpeg 5.0.1 

I don't know how to do it, but a friend of mine said there should be a flag you can set so they don't pop up in the foreground.

**Comment by qarmin** [comment]
This is fixed in 4.1.0
