### ISSUE TITLE
[BUG] czkawka_gui claims that supplied path doesn't exist and fails to find duplicates

### ISSUE THREAD

**Issue by zetok** [qarmin/czkawka#74]
Possibly related to #44 and #45. Or maybe not, since I'm quite sure that the path in question does contain valid unicode.

Path characters scrambled with: `sed 's/\(.\)/\1\n/g' | sort | awk -v ORS='' '{ print } END { print "\n" }'`:

```
      ',.///////?aaAdeeeeeegGhhhHiiikkmmmMnnnnnoooooooooPrrrrsssttttttuuwWxyYz
```

---

OS: Gentoo Linux amd64
`czkawka_gui` version: d2c7398bdd5a84c2e057ed629e50641f6a9fbd60

**Comment by qarmin** [comment]
I updated #45, because seems that #59 fixed this.
Path which I used to search
```
/home/rafal/Pulpit/      ',.?aaAdeeeeeegGhhhHiiikkmmmMnnnnnoooooooooPrrrrsssttttttuuwWxyYz
```
is invalid due using comma which is used in internally code to get multiple path from string
in error message it is clear, that this path was divided into two.
```
Included Directory Warning: Provided folder path must exits, ignoring /home/rafal/Pulpit/      '
Included Directory Warning: Relative path are not supported, ignoring .?aaAdeeeeeegGhhhHiiikkmmmMnnnnnoooooooooPrrrrsssttttttuuwWxyYz
```
