### ISSUE TITLE
Some questions, mostly about hash and scanning

### ISSUE THREAD

**Issue by a84r7a3rga76fg** [qarmin/czkawka#753]
I have two folders, Download and Archive. Can I use this program to scan Archive and save the hashes in a reference file, and then scan Download and use the reference file to delete any file in Download if it has the same hash as the files in the reference file?

**Comment by qarmin** [comment]
No,
You must scan both folders at once to be able to find and delete duplicates

**Comment by a84r7a3rga76fg** [comment]
I'll make a separate issue for a feature request
