### ISSUE TITLE
is Fast Compare no longer working?

### ISSUE THREAD

**Issue by chchia** [qarmin/czkawka#761]
I clone the latest source and compiled, finding Similar Images with Fast Compare option on, yet still it comparing hash very slowly compared to previous version.

![image](https://user-images.githubusercontent.com/1291771/174521944-ce398ffb-8fbc-435e-968a-99aa5b25c1d6.png)

comparing speed is about 200 images per second....

**Comment by chchia** [comment]
![image](https://user-images.githubusercontent.com/1291771/174523870-7a8fa107-17bf-4070-938e-138c4bc59081.png)
also, clicked stop and it show Stop requested, yet is still continue to run

**Comment by qarmin** [comment]
Fast compare option has not changed since previous version

Also stop window works exactly same, but not when user click at button, there is shown message.

Currently only rarely code checks if user stopped search, because otherwise this will cause even lower check performance

**Comment by qarmin** [comment]
Message is not clear enough

Comparing `x/y` image hash means that up to this moment `x` comparisons have been made of all `y`.

So having 1 million files not means that there will be 1 million comparisons(usually it is a lot of more).
Number of comparisons depends on number of group of images with same hash.
