### ISSUE TITLE
Cannot use the "Delete" function when using Czkawka

### ISSUE THREAD

**Issue by Hammit** [qarmin/czkawka#763]
The Delete button doesn't work when Czkawka is installed from snap store.
I think it may be because Czkawka isn't installed in classic mode which allows it to delete files outside of the sandbox.
Can you please provide the classic installation option for the snap?

**Comment by qarmin** [comment]
Classic option is not simple on/off options.

Each app which wants to have access to entire filesystem, needs to pass special checking procedure. 

Also, the Ubuntu team is not very enthusiastic about giving such options to applications that do not need it(Czkawka main usecase is to work on files which user created/downloaded like movies, photos, music which almost always are available in  sandboxed environment.

**Comment by Hammit** [comment]
It might be helpful to leave a note/message for the snap on the snap store that not all functions of the app are available.
If people used the app to find duplicates in their home directory and click the delete button and it doesn't work, that may confuse them.

**Comment by Hammit** [comment]
Actually, I think I am wrong about it being a snap problem. I just downloaded the linux_czkawka_gui binary and ran it and the Delete button doesn't work in it either. I think this is a bug.

**Comment by Hammit** [comment]
Re-installed the OS (Ubuntu MATE) and tried Czkawka again and delete worked this time. Doesn't look like a Czkawka problem.
