### ISSUE TITLE
linux_czkawka_gui.AppImage v.4.1.0 | libraries, cache and modules involved

### ISSUE THREAD

**Issue by Ricky-Tigg** [qarmin/czkawka#771]
**General information**
```
$ cat /etc/redhat-release
Fedora release 36 (Thirty Six)
$ uname -ro
5.18.9-200.fc36.x86_64 GNU/Linux
```
**Installed components**
```
$ dnf --installed list 'gtk?' | sed 1d
gtk2.x86_64                   2.24.33-8.fc36                    @updates-testing
gtk3.x86_64                   3.24.34-1.fc36                    @updates        
gtk4.x86_64                   4.6.5-1.fc36                      @updates
```
**Application file properties**
```
$ file -b linux_czkawka_gui.AppImage
ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=970d7fd8e9fbabf3cbe0a2b050cf3837416e4fd3, stripped
```
Hello. Here are the illustrations of the messages, that might be indicating an issue.
- While requesting above reported program interpreter
```
$ /lib64/ld-linux-x86-64.so.2 linux_czkawka_gui.AppImage
linux_czkawka_gui.AppImage: error while loading shared libraries: linux_czkawka_gui.AppImage: cannot open shared object file
```
I could not figure out by myself a work-around for that issue

- When the application is launched for the very first time in the currently running terminal emulator, be it inside or outside a sandbox program –  `firejail` for instance, e.g. via `firejail --appimage --private --noprofile ./<AppImage>`, assuming the support of AppImage is enabled, which can be checked against `firejail --version` – then the message `(AppRun.wrapped:<PID>): Gtk-WARNING **: 16:43:23.364: cache version is different 2 != 1` is reported. However itt won't be reported in the following executions of that command.
```
$ ./linux_czkawka_gui.AppImage
Gtk-Message: 16:43:23.146: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:43:23.146: Failed to load module "pk-gtk-module"
Gtk-Message: 16:43:23.148: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:43:23.148: Failed to load module "pk-gtk-module"

(AppRun.wrapped:11533): Gtk-WARNING **: 16:43:23.364: cache version is different 2 != 1
```
Nevertheless the presence in my system of the modules reported can be attested as follows:
```
$ locate *-gtk-module.so
/usr/lib64/gtk-2.0/modules/libcanberra-gtk-module.so
/usr/lib64/gtk-3.0/modules/libcanberra-gtk-module.so
/usr/lib64/gtk-3.0/modules/libpk-gtk-module.so
```
Therefore the production of those Gtk-messages shall be avoided by applying the following instruction, which then acts as a temporary work-around.

`$ LD_LIBRARY_PATH=/usr/lib64/gtk-3.0/modules/:$LD_LIBRARY_PATH ./linux_czkawka_gui.AppImage`

**Comment by dpward** [comment]
> Therefore the production of those Gtk-messages shall be avoided by applying the following instruction, which then acts as a temporary work-around.
> 
> `$ LD_LIBRARY_PATH=/usr/lib64/gtk-3.0/modules/:$LD_LIBRARY_PATH ./linux_czkawka_gui.AppImage`

@Ricky-Tigg GTK3 has its own mechanism to search for libraries. The command above should never be used.

If you are interested, you can learn more here (see the section describing `GTK_PATH`): https://docs.gtk.org/gtk3/running.html

In general the messages you mention can be safely ignored.

**Comment by dpward** [comment]
Your other issue would seem to be AppImage/AppImageSpec#15.

**Comment by Ricky-Tigg** [comment]
Reported as AppImage/AppImageKit/issues/1199 as well.

**Comment by Ricky-Tigg** [comment]
Reported as AppImage/AppImageKit/issues/1199 as well. "_messages about failing to loading those GTK modules can be safely ignored_" | Thus no issue left to handle here.
