### ISSUE TITLE
Strange sentence on CLI “may speed up will cause”

### ISSUE THREAD

**Issue by alexislefebvre** [qarmin/czkawka#773]
> assigning bigger value may speed up will cause that lower amount of files

It's written here: https://github.com/qarmin/czkawka/blob/e3cea6763453516d251ada0013a32ef41dadc2e8/czkawka_cli/src/commands.rs#L25

I would open a PR but I'm not sure to understand the meaning of this part.

**Comment by qarmin** [comment]
Probably this was something like:
bigger value, slower loading of cache but faster scan
smaller value, faster loading of cache but some files will need to be hashed again

loading < 1million cache entries should take probably on most machines < 1s

**Comment by chchia** [comment]
Maybe means

"Minimum size of cached files in bytes, setting to bigger value for faster scanning, or smaller value for faster loading yet some files may required to be re-hash again."
