### ISSUE TITLE
Feature request PNG preview in similar images compare

### ISSUE THREAD

**Issue by astandarduser** [qarmin/czkawka#778]
It would be nice to have a PNG preview in similar images compare, all jpg's have one

**Comment by qarmin** [comment]
All image files should have preview(maybe except .exr and other exotic extensions).
Which exactly images have no preview?

**Comment by kurumushi** [comment]
I've noticed that at least on linux, if a file ends in .PNG instead of .png, the file will not show in previews, so maybe it's a case sensitivity issue.

**Comment by qarmin** [comment]
So looks that this is duplicate of https://github.com/qarmin/czkawka/issues/723 and is already fixed in master
