### ISSUE TITLE
Scanning images is stuck

### ISSUE THREAD

**Issue by xplosionmind** [qarmin/czkawka#779]
Hello, I am a newbie and I am trying to scan a folder with many images. The scanning process is stuck, though.

I am using Ubuntu 22.04 and Czawka 4.1.0

![Screenshot from 2022-07-17 12-07-51](https://user-images.githubusercontent.com/42862428/179393462-511dfd8e-947e-4dc4-b53f-960e872e8cc0.png)

**Comment by qarmin** [comment]
Can you run app from terminal and post here log?
If there is any crash, backtrace should be printed to output

**Comment by xplosionmind** [comment]
> Can you run app from terminal and post here log?

I cannot, because if I run `czkawka`, the app that opens does not allow me to enter `/media` (operation not permitted). Nevertheless, if I run `sudo czkawka` I get the following error

```
tommi@linuxplosion:~$ sudo czkawka
mkdir: cannot create directory '/run/user/0': Permission denied
Authorization required, but no authorization protocol specified

(czkawka_gui:381191): Gtk-WARNING **: 17:34:01.360: cannot open display: :0
```

**Comment by qarmin** [comment]
`Manual add` button allows to write path by hand without needing to add it via file manager
I have no idea what can be broken, so without more details I'm unable to fix it

**Comment by xplosionmind** [comment]
Hello @qarmin, thanks a lot for your help.

I managed to find a workaround so, for now, it is not necessary to investigate further.
