### ISSUE TITLE
Version 5.0 AppImage doesn't work under Ubuntu 20.04 

### ISSUE THREAD

**Issue by Sadi58** [qarmin/czkawka#788]
Apart from (alternative) naming error in the latest 2 AppImage files, running it from terminal throws the following error messages many times, and then fails to start. I think it's related with Ubuntu 20.04 although I use the latest KDE neon. 
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found

**Comment by qarmin** [comment]
This is expected, 
Ubuntu 20.04 not have GTK 4, so to compile app Ubuntu 22.04 was used.
Ubuntu 22.04 also use newer GLIBC library, so this why this error is shown

**Comment by Sadi58** [comment]
@qarmin Thanks. I was expecting something like this actually but I just wanted to be sure. I'll close this then, but it might be a good idea to add this info somewhere.
