### ISSUE TITLE
Version 5.0.0 crash on startup, GTK4 is missing?

### ISSUE THREAD

**Issue by alexislefebvre** [qarmin/czkawka#789]
I use Ubuntu 20.04.4.

I downloaded the `5.0.0` release but a dependency is missing:

```bash
cd /tmp/
curl --location https://github.com/qarmin/czkawka/releases/download/5.0.0/linux_czkawka_gui -o /tmp/linux_czkawka_gui
chmod +x ./linux_czkawka_gui
./linux_czkawka_gui
[…]
linux_czkawka_gui: error while loading shared libraries: libgtk-4.so.1: cannot open shared object file: No such file or directory
```

I tried to install the [dependencies](https://github.com/qarmin/czkawka/blob/master/instructions/Installation.md#ubuntudebianlinux-mint) but it didn't work:

```bash
sudo apt install libgtk-4-dev ffmpeg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libgtk-4-dev
```

It looks like `libgtk-4-dev` only exists on Ubuntu 21.10+: https://packages.ubuntu.com/search?keywords=libgtk-4-dev

So people which use Ubuntu 21.10+ can use czkawka `5.0.0`, the others have to use `4.1.0`.

**Comment by qarmin** [comment]
Yes, this is expected,
As workaround to use 5.0.0 version, flatpak build is required which allows to install app on older OS(not released yet)

**Comment by alexislefebvre** [comment]
Thanks for your answer, we should add a note about the versions here: https://github.com/qarmin/czkawka/blob/master/instructions/Installation.md#precompiled-binaries

**Comment by alexislefebvre** [comment]
Thanks for updating the README. Upgrade from Ubuntu LTS 20.04 to 22.04 will be proposed next week, when Ubuntu 22.04.1 will be released. So most users should be able to upgrade and get GTK4.
