### ISSUE TITLE
Cannot Scan Drive Root - Windows

### ISSUE THREAD

**Issue by YenLegion** [qarmin/czkawka#794]
Hi, I am using this on Windows 10 and it does not allow me to add a drive root as a scan location. It did let me add it manually by typing the drive name, but it did not scan it. I have several disk drives which have accumulated junk over time and I wanted to scan the whole drive. I am probably missing something. Thanks.

**Comment by qarmin** [comment]
This is fixed by  - https://github.com/qarmin/czkawka/commit/97563a7b2a70fb5fcf6463f28069e6ea3b0ff5c2
Fixed binaries are available here - https://github.com/qarmin/czkawka/actions/runs/2762234116
