### ISSUE TITLE
Unable to include second drive in new update

### ISSUE THREAD

**Issue by cyberlionx** [qarmin/czkawka#804]
`Directories: Relative path are not supported, ignoring ⁨Z:⁩`

On Windows 10

When clicking 'add' I cannot select my other partition, only folders in it. When adding manually, I get the error above. This worked as expected in previous versions

Edit: Actually, it applies to the C drive as well. We can no longer include an entire drive/partition.

Edit: wildcards to not resolve the problem

```
Directories: Wildcards in path are not supported, ignoring ⁨Z:\*⁩
Directories: Wildcards in path are not supported, ignoring ⁨D:\*⁩
```

**Comment by qarmin** [comment]
This is already fixed in master branch.
Windows binaries directly from git version - https://github.com/qarmin/czkawka/actions/runs/2783479257
