### ISSUE TITLE
Error while loading shared libraries: libheif.so.1

### ISSUE THREAD

**Issue by daniporr** [qarmin/czkawka#810]
I am trying to run `linux_czkawka_cli` on Linux, but I get the following error:

```
./linux_czkawka_cli: error while loading shared libraries: libheif.so.1: cannot open shared object file: No such file or directory
```

Do you know what I need to run it?

---

In the documentation there is written:

> You don't need to have any additional libraries for CLI Czkawka.

But this seems to be false.

And the funniest part is that I do not even need to run it on images!
(I only need the "Empty Directories" functionality and probably the "Duplicate Finder" one)

**Comment by qarmin** [comment]
Looks heif that library is dynamically loaded from OS(I expected that it will be built into binary, but I was wrong ¯\\\_(ツ)\_/¯)

The problem only happens with prebuilt binaries which use `heif` feature
https://github.com/qarmin/czkawka/blob/e20f30c66f3bde1659f6eaf20511e497825e0c5d/.github/workflows/linux.yml#L45

App manually compiled without this option should work fine only with GTK 4 libraries installed

**Comment by daniporr** [comment]
> Looks heif that library is dynamically loaded from OS(I expected that it will be built into binary, but I was wrong ¯\_(ツ)_/¯)
> 
> The problem only happens with prebuilt binaries which use `heif` feature
> 
> https://github.com/qarmin/czkawka/blob/e20f30c66f3bde1659f6eaf20511e497825e0c5d/.github/workflows/linux.yml#L45
> 
> App manually compiled without this option should work fine only with GTK 4 libraries installed

Does this mean that everyone who wants to run it on Linux must have that library installed (btw, which one exactly?), or manually build it?

However, I do not have the Rust building tools installed on my machine, so I cannot build it (and I believe many users will be in the same situation), so probably binaries that can be executed without any dependencies should be provided as well.

Moreover, I discovered that the same problem happens with the GUI. Therefore, you cannot run Czkawka at all if you do not have that library or do not manually build it.

**Comment by qarmin** [comment]
You can download from actions binary without heif support - https://github.com/qarmin/czkawka/actions/runs/2883469684 (czkawka_gui-Linux-1.60.0  and czkawka_cli-Linux-1.60.0 )
On Ubuntu 22.04 this are required libraries to be able to run app
https://github.com/qarmin/czkawka/blob/d3e7c2d77720997d3ee729c1afc8ef7215cbe196/.github/workflows/linux.yml#L35

**Comment by daniporr** [comment]
Thank you for your suggestion.

I downloaded, extracted and tried to run the cli (`czkawka_cli-Linux-1.60.0.zip`).
Unfortunately, I got the following errors:

```log
./czkawka_cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./czkawka_cli)
./czkawka_cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./czkawka_cli)
./czkawka_cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./czkawka_cli)
```

I have updated my OS (and all the packages) to their latest versions, but I still get that same error.

Any other suggestions?

**Comment by qarmin** [comment]
Czkawka require glibc which is available on Ubuntu 22.04 or similar, so for me looks that this error is completely normal.
With 5.0.2 version, official binary not require heif library anymore.

**Comment by rossgardt** [comment]
I experience the same issue when using macOS:
```
dyld[78651]: Library not loaded: '/usr/local/opt/libheif/lib/libheif.1.dylib'
  Referenced from: '/Users/I501899/Downloads/mac_czkawka_cli'
  Reason: tried: '/usr/local/opt/libheif/lib/libheif.1.dylib' (no such file), '/usr/local/lib/libheif.1.dylib' (no such file), '/usr/lib/libheif.1.dylib' (no such file)
zsh: abort      ./mac_czkawka_cli
```

libheif is installed:
```
brew info libheif
==> libheif: stable 1.13.0 (bottled)
ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
https://www.libde265.org/
/opt/homebrew/Cellar/libheif/1.13.0 (25 files, 2.8MB) *
  Poured from bottle on 2022-09-14 at 15:44:08
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libheif.rb
```

Looks like the CLI binary is looking in a different folder than where it is installed.

**Comment by marmolak** [comment]
Hello.
It seems like rabbit hole is way more deeper than libheif on macOS.

`dyld_info ./mac_czkawka_gui`

returns:

```
/usr/local/opt/libheif/lib/libheif.1.dylib
/usr/local/opt/glib/lib/libgobject-2.0.0.dylib
/usr/local/opt/gtk4/lib/libgtk-4.1.dylib
/usr/local/opt/pango/lib/libpangocairo-1.0.0.dylib
/usr/local/opt/pango/lib/libpango-1.0.0.dylib
/usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib
/usr/local/opt/gdk-pixbuf/lib/libgdk_pixbuf-2.0.0.dylib
/usr/local/opt/cairo/lib/libcairo-gobject.2.dylib
/usr/local/opt/cairo/lib/libcairo.2.dylib
/usr/local/opt/graphene/lib/libgraphene-1.0.0.dylib
/usr/local/opt/glib/lib/libgio-2.0.0.dylib
/usr/local/opt/glib/lib/libglib-2.0.0.dylib
/usr/local/opt/gettext/lib/libintl.8.dylib
```

There should be workaround with `install_name_tool`.

I believe, there can be 2 solutions:
1) Link binary with by using `@loader_path/` or `@rpath/` - ideally bundle libs and provide installable pkg file.
2) Provide static binary build (which can be impossible or final binary would be too big).

**Comment by marmolak** [comment]
Fast workaround should be:

`install_name_tool -change /usr/local/opt/libheif/lib/libheif.1.dylib /opt/local/lib/libheif.1.dylib ./mac_czkawka_cli`

in my case.

Before change:
```
% dyld_info ./mac_czkawka_cli | grep libheif
                       /usr/local/opt/libheif/lib/libheif.1.dylib
```

After change:
```
% dyld_info ./mac_czkawka_cli | grep libheif
                       /opt/local/lib/libheif.1.dylib
```
