### ISSUE TITLE
Sorting by date crashes Czkawka 5.0.1

### ISSUE THREAD

**Issue by kayvax** [qarmin/czkawka#813]
Czkawka seems to be suffering from GTK bug:
[https://gitlab.gnome.org/GNOME/gtk/-/issues/4708](https://gitlab.gnome.org/GNOME/gtk/-/issues/4708)

When trying to add a folder from file selection dialog one uses sort by date (in my case twice to get newest frist) czkawka_gui breaks with error:

`(czkawka_gui:625099):` Gtk-CRITICAL **: 20:28:23.185: _gtk_tree_path_new_from_rbtree: assertion 'node != NULL' failed

(czkawka_gui:625099): Gtk-CRITICAL **: 20:28:23.185: gtk_tree_model_get_iter: assertion 'path->depth > 0' failed

(czkawka_gui:625099): Gtk-CRITICAL **: 20:28:23.185: gtk_tree_model_get_iter: assertion 'path->depth > 0' failed
zsh: segmentation fault (core dumped)  czkawka_gui .`

Seems to be known GTK problem. IDK if you can implement any workaround.

**Comment by dpward** [comment]
That issue was fixed with https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4885 and is staged for GTK 4.6.7 (not yet released).

**Comment by qarmin** [comment]
GTK 4.6.9 version is available now, which contains fix for this problem
