### ISSUE TITLE
Make xxxhash3 the default algorithm, rather than blake3

### ISSUE THREAD

**Issue by t3dium** [qarmin/czkawka#825]
The program indicates its performance is "very similar", but after having used it several times it calculates hashes at a much faster rate. So having it as the default option in czkawka would be nice.

**Comment by gabefair** [comment]
I'm not sure if this is caused by your processor specifically. Some processors have [application-specific integrated circuits](https://en.wikipedia.org/wiki/Application-specific_integrated_circuit) for some hash, and video algorithms.
