### ISSUE TITLE
Sorting by clicking on column name don't work

### ISSUE THREAD

**Issue by liam-maps** [qarmin/czkawka#866]
Hi!
I'm impressed with the progress of this amazing piece of software.
I'm using v5.0.2 on Windows 10 22H2.
When I hover over the column name, it highlights in blue, but clicking does nothing.
I expected it to sort the results based on the column header I click.
Don't know if a bug or still not implemented.
Thank you.

**Comment by qu4ntumrush** [comment]
Yes, I definitely request advanced sorting and filtering features to focus on specific groups. It's the only real flaw with the program.
