### ISSUE TITLE
"Cannot start search, when all directories are set as reference folders" | version 5.0.2

### ISSUE THREAD

**Issue by raleighlittles** [qarmin/czkawka#873]
# System info

* Ubuntu 22.04.1 LTS x86_64
* Kernel: 5.15.0-53-generic

# Version

* Czkawka 5.0.2, via AppImage `linux_czkawka_gui.AppImage`

# Issue description

I'm attempting to use the application to find similar (not exact duplicates) images in a given directory. When I choose the folder I want to search in, and click "Search", I get this error:

```
############### MESSAGES(2) ###############
Properly loaded 8379 cache entries.
Properly saved to file 8379 cache entries.
```

Here's a screenshot of the issue:

![image](https://user-images.githubusercontent.com/2137201/204362304-d938fab8-fb2d-4ff3-9366-1cc9e170a7d0.png)

What is going wrong here?

**Comment by qarmin** [comment]
This is expected,
Referenced folders are treated like originals which cannot be deleted, so you need at least one "normal" folder to be able to compare files with original from "reference" folders.

To "fix" this, uncheck at the top "/mnt/shares..."

**Comment by TimB87** [comment]
![image](https://user-images.githubusercontent.com/7693498/211819407-8c37d05f-6288-4a31-8291-d2aaa34fa0ca.png)
On a windows system the placement of the checkbox can be a little bit deceiving
