### ISSUE TITLE
Update clap from 3 to 4 version

### ISSUE THREAD

**Issue by qarmin** [qarmin/czkawka#877]
I tried but looks that this is not so trivial(but should not be so hard either)

Example commits from other repos:
- https://github.com/clearloop/leetcode-cli/commit/d5228d98168a9472cadfb3044a782a6f773f6b04
- https://github.com/tkellogg/dura/commit/dd29bc82340aad8a3fce4a4805bf2e582595e22c
- https://github.com/dottorblaster/pacnews/commit/a3eec5cefbc7b06a426041341bb1c05002f3dff0
- https://github.com/BfBBModdingTools/xbld/commit/0082102bb39b899603f4c8413d150969f28fc48f
- https://github.com/galenelias/AdventOfCode_2022/commit/3d8115d1c1caab10b8c8ee60ad9033a9bb67530d

**Comment by devgony** [comment]
Let me try this issue!

**Comment by Serial-ATA** [comment]
Oh sorry @devgony, I finished this yesterday before seeing your comment.
