### ISSUE TITLE
NAS Issue?: Failed to delete file

### ISSUE THREAD

**Issue by KreepyKelly** [qarmin/czkawka#907]
Using in Windows 10, 64-bit,  connecting to a Synology NAS, scanning Music files, and am receiving the following error when I try to delete any file:

Failed to delete file ⁨D:\folder\folder\artistfolder\trackname.mp3⁩, reason ⁨Error during a `trash` operation: Unknown { description: "windows error: The system cannot find the file specified.\r\n" }⁩

Any help appreciated. Thanks!

**Comment by alexislefebvre** [comment]
In the settings (button on top right), did you check the option to put deleted files in the trash bin? Can you try without this option?

**Comment by KreepyKelly** [comment]
That worked! Thank you so much for responding! Everything is working now.

**Comment by KreepyKelly** [comment]
Issue resolved

**Comment by alexislefebvre** [comment]
You're welcome.

So it means that the trash feature doesn't work on Windows.
