### ISSUE TITLE
new Check method: "Name AND Size"

### ISSUE THREAD

**Issue by Die4Ever** [qarmin/czkawka#908]
right now you can use either the Name or the Size method, but I would like a method that does both, so a file is only considered a duplicate if the name and the size are both the same!

also another idea would be a method for "Name or Size", but I don't have a use for that right now lol

btw I'm loving this program, thank you!

**Comment by gimdh** [comment]
I had similar thoughts and made #937. Please check if my proposal meets your requirements.
