### ISSUE TITLE
how to install czkawka_cli

### ISSUE THREAD

**Issue by tykayn** [qarmin/czkawka#940]
hi, i wanted to use the same features than fslint to remove duplicate files, but i do not find a way to get czkawka_cli installed on Debian / Ubuntu.
cargo install does not find it, snap too.

did i miss some documentation?

thanks for this great program btw

**Comment by alexislefebvre** [comment]
Try this:

```shell
# download
curl --location https://github.com/qarmin/czkawka/releases/download/5.1.0/linux_czkawka_cli \
--output ~/.local/bin/linux_czkawka_cli
# mark as executable
chmod +x ~/.local/bin/linux_czkawka_cli
# run
linux_czkawka_cli
```

This URL is available on the releases page: https://github.com/qarmin/czkawka/releases
