### ISSUE TITLE
Update GNOME version to 43

### ISSUE THREAD

**Issue by Kazevic** [qarmin/czkawka#952]
As [GNOME 42 has reached end of life with the GNOME 42.10 release](https://discourse.gnome.org/t/gnome-42-10-released/14592), the upgrade to GNOME 43 should be done as soon as possible.

**Comment by StephGbzh** [comment]
And accordingly, `flatpak update` prints this log now:

Info: runtime org.gnome.Platform branch 42 is end-of-life, with reason:
   The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   com.github.qarmin.czkawka

**Comment by TotallyMonica** [comment]
Can confirm this is still the case for Flatpak.
```
Info: runtime org.gnome.Platform branch 42 is end-of-life, with reason:
   The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   com.github.qarmin.czkawka
```

**Comment by qarmin** [comment]
Fixed by https://github.com/flathub/com.github.qarmin.czkawka/pull/18, update probably will be available soon(1/2 days)
