### ISSUE TITLE
Cannot build 5.1.0 with cargo: error[E0599]: no function or associated item named `from_data_with_options` found for struct `File` in the current scope

### ISSUE THREAD

**Issue by gcflymoto** [qarmin/czkawka#966]
cargo install czkawka_cli
Updating crates.io index
....
error[E0599]: no function or associated item named `from_data_with_options` found for struct `File` in the current scope
   --> /nfs/site/disks/xpg_dmrhub_0140/gczajkow/rust_crt/.cargo/registry/src/github.com-1ecc6299db9ec823/czkawka_core-5.1.0/src/broken_files.rs:531:66
    |
531 | ...                   if let Err(e) = pdf::file::File::from_data_with_options(content, parser_options) {
    |                                                        ^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `File<_, _, _>`

details ...

  Downloaded czkawka_cli v5.1.0
  Downloaded 1 crate (26.0 KB) in 0.47s
  Installing czkawka_cli v5.1.0
  Downloaded adler32 v1.2.0
  Downloaded find-crate v0.6.3
  Downloaded hamming v0.1.3
  Downloaded locale_config v0.3.0
  Downloaded lebe v0.5.2
  Downloaded num-complex v0.3.1
  Downloaded humansize v2.1.3
  Downloaded pkg-config v0.3.26
  Downloaded intl-memoizer v0.5.1
  Downloaded mime_guess v2.0.4
  Downloaded pbkdf2 v0.11.0
  Downloaded miniz_oxide v0.7.1
  Downloaded unicode-bidi v0.3.13
  Downloaded unicode-normalization v0.1.22
  Downloaded rust-embed-utils v7.5.0
  Downloaded state v0.5.3
  Downloaded qoi v0.4.1
  Downloaded symphonia-core v0.5.2
  Downloaded zip v0.6.4
  Downloaded zune-inflate v0.2.53
  Downloaded time-core v0.1.0
  Downloaded simd-adler32 v0.3.5
  Downloaded type-map v0.4.0
  Downloaded snafu v0.7.4
  Downloaded unicase v2.6.0
  Downloaded yaml-rust v0.4.5
  Downloaded unic-langid-impl v0.9.1
  Downloaded unic-langid v0.9.1
  Downloaded tiff v0.8.1
  Downloaded rust-embed v6.6.1
  Downloaded pdf_derive v0.1.22
  Downloaded ogg_pager v0.5.0
  Downloaded ffmpeg_cmdline_utils v0.1.2
  Downloaded rustdct v0.7.1
  Downloaded rustdct v0.6.0
  Downloaded triple_accel v0.3.4
  Downloaded lofty_attr v0.6.0
  Downloaded symphonia-codec-alac v0.5.2
  Downloaded symphonia-codec-adpcm v0.5.2
  Downloaded symphonia-format-ogg v0.5.2
  Downloaded symphonia-format-mkv v0.5.2
  Downloaded symphonia-codec-aac v0.5.2
  Downloaded symphonia-codec-vorbis v0.5.2
  Downloaded symphonia-utils-xiph v0.5.2
  Downloaded symphonia-format-wav v0.5.2
  Downloaded bk-tree v0.4.0
  Downloaded fax v0.2.0
  Downloaded symphonia-bundle-flac v0.5.2
  Downloaded lofty v0.11.0
  Downloaded symphonia-codec-pcm v0.5.2
  Downloaded transpose v0.2.2
  Downloaded fluent v0.16.0
  Downloaded deflate v1.0.0
  Downloaded constant_time_eq v0.1.5
  Downloaded symphonia-format-isomp4 v0.5.2
  Downloaded base64ct v1.6.0
  Downloaded multicache v0.6.1
  Downloaded flume v0.10.14
  Downloaded fluent-syntax v0.11.0
  Downloaded dirs-sys-next v0.1.2
  Downloaded doc-comment v0.3.3
  Downloaded displaydoc v0.2.3
  Downloaded futures v0.3.28
  Downloaded flate2 v1.0.25
  Downloaded cipher v0.3.0
  Downloaded futures-io v0.3.28
  Downloaded bytemuck v1.13.1
  Downloaded futures-task v0.3.28
  Downloaded fdeflate v0.3.0
  Downloaded bzip2-sys v0.1.11+1.0.8
  Downloaded futures-util v0.3.28
  Downloaded intl_pluralrules v7.0.2
  Downloaded jpeg-decoder v0.3.0
  Downloaded inout v0.1.3
  Downloaded half v2.2.1
  Downloaded libm v0.2.6
  Downloaded czkawka_core v5.1.0
  Downloaded rustfft v6.1.0
  Downloaded md5 v0.7.0
  Downloaded rawloader v0.37.1
  Downloaded glob v0.3.1
  Downloaded opaque-debug v0.3.0
  Downloaded rustfft v5.1.1
  Downloaded pdf v0.8.1
  Downloaded num-rational v0.4.1
  Downloaded futures-core v0.3.28
  Downloaded linked-hash-map v0.5.6
  Downloaded futures-macro v0.3.28
  Downloaded vid_dup_finder_lib v0.1.1
  Downloaded futures-executor v0.3.28
  Downloaded image v0.24.6
  Downloaded futures-sink v0.3.28
  Downloaded futures-channel v0.3.28
  Downloaded fluent-langneg v0.13.0
  Downloaded fluent-bundle v0.15.2
  Downloaded arc-swap v1.6.0
  Downloaded cfb v0.7.3
  Downloaded datasize v0.2.14
  Downloaded infer v0.12.0
  Downloaded audio_checker v0.1.0
  Downloaded hmac v0.12.1
  Downloaded globalcache v0.2.0
  Downloaded imagepipe v0.5.0
  Downloaded tinystr v0.7.1
  Downloaded time v0.3.20
  Downloaded i18n-embed-fl v0.6.6
  Downloaded stringprep v0.1.2
  Downloaded istring v0.3.3
  Downloaded tempfile v3.5.0
  Downloaded serde_yaml v0.8.26
  Downloaded semver v1.0.17
  Downloaded fax_derive v0.1.0
  Downloaded png v0.17.8
  Downloaded enumn v0.1.8
  Downloaded snafu-derive v0.7.4
  Downloaded self_cell v0.10.2
  Downloaded sha1 v0.10.5
  Downloaded primal-check v0.3.3
  Downloaded datasize_derive v0.2.14
  Downloaded symphonia-metadata v0.5.2
  Downloaded strength_reduce v0.2.4
  Downloaded rustc-hash v1.1.0
  Downloaded rustc_version v0.4.0
  Downloaded exr v1.6.3
  Downloaded weezl v0.1.7
  Downloaded symphonia-bundle-mp3 v0.5.2
  Downloaded symphonia v0.5.2
  Downloaded proc-macro-error v1.0.4
  Downloaded image_hasher v1.1.2
  Downloaded proc-macro-error-attr v1.0.4
  Downloaded nanorand v0.7.0
  Downloaded base64 v0.21.0
  Downloaded base64 v0.13.1
  Downloaded spin v0.9.8
  Downloaded bzip2 v0.4.4
  Downloaded rust-embed-impl v6.5.0
  Downloaded async-trait v0.1.68
  Downloaded aes v0.8.2
  Downloaded directories-next v2.0.0
  Downloaded cbc v0.1.2
  Downloaded tinyvec_macros v0.1.1
  Downloaded tinyvec v1.6.0
  Downloaded slab v0.4.8
  Downloaded paste v1.0.12
  Downloaded num-complex v0.4.3
  Downloaded miniz_oxide v0.6.2
  Downloaded cipher v0.4.4
  Downloaded block-padding v0.3.3
  Downloaded password-hash v0.4.2
  Downloaded i18n-config v0.4.3
  Downloaded i18n-embed-impl v0.8.0
  Downloaded pin-project-lite v0.2.9
  Downloaded parking_lot v0.12.1
  Downloaded mime v0.3.17
  Downloaded color_quant v1.1.0
  Downloaded bit_field v0.10.2
  Downloaded aes v0.7.5
  Downloaded fastrand v1.9.0
  Downloaded inflate v0.4.5
  Downloaded i18n-embed v0.13.8
  Downloaded gif v0.12.0
  Downloaded adler v1.0.2
  Downloaded 162 crates (12.4 MB) in 6.42s (largest was `vid_dup_finder_lib` at 2.4 MB)
   Compiling proc-macro2 v1.0.56
   Compiling unicode-ident v1.0.8
   Compiling quote v1.0.26
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling version_check v0.9.4
   Compiling syn v1.0.109
   Compiling libc v0.2.141
   Compiling serde_derive v1.0.160
   Compiling serde v1.0.160
   Compiling syn v2.0.15
   Compiling typenum v1.16.0
   Compiling generic-array v0.14.7
   Compiling bitflags v1.3.2
   Compiling log v0.4.17
   Compiling bytemuck v1.13.1
   Compiling lazy_static v1.4.0
   Compiling scopeguard v1.1.0
   Compiling lock_api v0.4.9
   Compiling arrayvec v0.7.2
   Compiling num-traits v0.2.15
   Compiling crossbeam-utils v0.8.15
   Compiling thiserror v1.0.40
   Compiling memoffset v0.8.0
   Compiling memchr v2.5.0
   Compiling thiserror-impl v1.0.40
   Compiling symphonia-core v0.5.2
   Compiling crypto-common v0.1.6
   Compiling displaydoc v0.2.3
   Compiling crossbeam-epoch v0.9.14
   Compiling getrandom v0.2.9
   Compiling num-integer v0.1.45
   Compiling futures-core v0.3.28
   Compiling rayon-core v1.11.0
   Compiling subtle v2.4.1
   Compiling adler v1.0.2
   Compiling crossbeam-deque v0.8.3
   Compiling tinystr v0.7.1
   Compiling crossbeam-channel v0.5.8
   Compiling block-buffer v0.10.4
   Compiling num_cpus v1.15.0
   Compiling crc32fast v1.3.2
   Compiling digest v0.10.6
   Compiling unic-langid-impl v0.9.1
   Compiling miniz_oxide v0.6.2
   Compiling encoding_rs v0.8.32
   Compiling futures-sink v0.3.28
   Compiling byteorder v1.4.3
   Compiling either v1.8.1
   Compiling smallvec v1.10.0
   Compiling unic-langid v0.9.1
   Compiling toml v0.5.11
   Compiling symphonia-metadata v0.5.2
   Compiling cpufeatures v0.2.6
   Compiling simd-adler32 v0.3.5
   Compiling parking_lot_core v0.9.7
   Compiling flate2 v1.0.25
   Compiling rayon v1.7.0
   Compiling cc v1.0.79
   Compiling pin-project-internal v1.0.12
   Compiling weezl v0.1.7
   Compiling same-file v1.0.6
   Compiling io-lifetimes v1.0.10
   Compiling sha2 v0.10.6
   Compiling walkdir v2.3.3
   Compiling pin-project v1.0.12
   Compiling jpeg-decoder v0.3.0
   Compiling symphonia-utils-xiph v0.5.2
   Compiling spin v0.9.8
   Compiling nanorand v0.7.0
   Compiling unicase v2.6.0
   Compiling num-rational v0.4.1
   Compiling semver v1.0.17
   Compiling rustix v0.37.12
   Compiling strength_reduce v0.2.4
   Compiling transpose v0.2.2
   Compiling flume v0.10.14
   Compiling rust-embed-utils v7.5.0
   Compiling miniz_oxide v0.7.1
   Compiling fdeflate v0.3.0
   Compiling zune-inflate v0.2.53
   Compiling primal-check v0.3.3
   Compiling rand_core v0.6.4
   Compiling half v2.2.1
   Compiling rustc-hash v1.1.0
   Compiling linux-raw-sys v0.3.2
   Compiling bit_field v0.10.2
   Compiling color_quant v1.1.0
   Compiling lebe v0.5.2
   Compiling type-map v0.4.0
   Compiling exr v1.6.3
   Compiling gif v0.12.0
   Compiling png v0.17.8
   Compiling rust-embed-impl v6.5.0
   Compiling tiff v0.8.1
   Compiling block-padding v0.3.3
   Compiling qoi v0.4.1
   Compiling slab v0.4.8
   Compiling ryu v1.0.13
   Compiling heck v0.4.1
   Compiling futures-task v0.3.28
   Compiling pkg-config v0.3.26
   Compiling futures-channel v0.3.28
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling image v0.24.6
   Compiling inout v0.1.3
   Compiling rustc_version v0.4.0
   Compiling aho-corasick v0.7.20
   Compiling i18n-config v0.4.3
   Compiling intl-memoizer v0.5.1
   Compiling fluent-syntax v0.11.0
   Compiling find-crate v0.6.3
   Compiling fluent-langneg v0.13.0
   Compiling intl_pluralrules v7.0.2
   Compiling rustfft v6.1.0
   Compiling proc-macro-error-attr v1.0.4
   Compiling indexmap v1.9.3
   Compiling self_cell v0.10.2
   Compiling glob v0.3.1
   Compiling regex-syntax v0.6.29
   Compiling serde_json v1.0.96
   Compiling tinyvec_macros v0.1.1
   Compiling async-trait v0.1.68
   Compiling doc-comment v0.3.3
   Compiling futures-util v0.3.28
   Compiling linked-hash-map v0.5.6
   Compiling tinyvec v1.6.0
   Compiling rawloader v0.37.1
   Compiling regex v1.7.3
   Compiling fluent-bundle v0.15.2
   Compiling i18n-embed-impl v0.8.0
   Compiling cipher v0.4.4
   Compiling blake3 v1.3.3
   Compiling datasize_derive v0.2.14
   Compiling num-complex v0.4.3
   Compiling num-complex v0.3.1
   Compiling futures-macro v0.3.28
   Compiling proc-macro-error v1.0.4
   Compiling base64ct v1.6.0
   Compiling itoa v1.0.6
   Compiling adler32 v1.2.0
   Compiling utf8parse v0.2.1
   Compiling libm v0.2.6
   Compiling futures-io v0.3.28
   Compiling pin-utils v0.1.0
   Compiling once_cell v1.17.1
   Compiling fnv v1.0.7
   Compiling paste v1.0.12
   Compiling ppv-lite86 v0.2.17
   Compiling pin-project-lite v0.2.9
   Compiling hashbrown v0.12.3
   Compiling rand_chacha v0.3.1
   Compiling locale_config v0.3.0
   Compiling anstyle-parse v0.2.0
   Compiling password-hash v0.4.2
   Compiling rustfft v5.1.1
   Compiling datasize v0.2.14
   Compiling mime_guess v2.0.4
   Compiling fluent v0.16.0
   Compiling unicode-normalization v0.1.22
   Compiling yaml-rust v0.4.5
   Compiling parking_lot v0.12.1
   Compiling snafu-derive v0.7.4
   Compiling rust-embed v6.6.1
   Compiling is-terminal v0.4.7
   Compiling symphonia-format-mkv v0.5.2
   Compiling symphonia-format-ogg v0.5.2
   Compiling symphonia-bundle-flac v0.5.2
   Compiling symphonia-codec-vorbis v0.5.2
   Compiling symphonia-format-isomp4 v0.5.2
   Compiling symphonia-format-wav v0.5.2
   Compiling symphonia-bundle-mp3 v0.5.2
   Compiling hmac v0.12.1
   Compiling symphonia-codec-alac v0.5.2
   Compiling symphonia-codec-aac v0.5.2
   Compiling symphonia-codec-pcm v0.5.2
   Compiling symphonia-codec-adpcm v0.5.2
   Compiling fax_derive v0.1.0
   Compiling enumn v0.1.8
   Compiling cipher v0.3.0
   Compiling unicode-bidi v0.3.13
   Compiling opaque-debug v0.3.0
   Compiling arrayref v0.3.7
   Compiling anstyle v1.0.0
   Compiling time-core v0.1.0
   Compiling constant_time_eq v0.2.5
   Compiling colorchoice v1.0.0
   Compiling arc-swap v1.6.0
   Compiling anstyle-query v1.0.0
   Compiling uuid v1.3.1
   Compiling anstream v0.3.0
   Compiling cfb v0.7.3
   Compiling dashmap v5.4.0
   Compiling i18n-embed v0.13.8
   Compiling time v0.3.20
   Compiling stringprep v0.1.2
   Compiling aes v0.7.5
   Compiling fax v0.2.0
   Compiling symphonia v0.5.2
   Compiling pbkdf2 v0.11.0
   Compiling snafu v0.7.4
   Compiling globalcache v0.2.0
   Compiling serde_yaml v0.8.26
   Compiling bzip2 v0.4.4
   Compiling rustdct v0.7.1
   Compiling rustdct v0.6.0
   Compiling istring v0.3.3
   Compiling ffmpeg_cmdline_utils v0.1.2
   Compiling futures-executor v0.3.28
   Compiling rand v0.8.5
   Compiling inflate v0.4.5
   Compiling deflate v1.0.0
   Compiling cbc v0.1.2
   Compiling aes v0.8.2
   Compiling multicache v0.6.1
   Compiling sha1 v0.10.5
   Compiling itertools v0.10.5
   Compiling ogg_pager v0.5.0
   Compiling bincode v1.3.3
   Compiling lofty_attr v0.6.0
   Compiling pdf_derive v0.1.22
   Compiling dirs-sys-next v0.1.2
   Compiling mime v0.3.17
   Compiling fastrand v1.9.0
   Compiling strsim v0.10.0
   Compiling base64 v0.21.0
   Compiling base64 v0.13.1
   Compiling constant_time_eq v0.1.5
   Compiling clap_lex v0.4.1
   Compiling triple_accel v0.3.4
   Compiling md5 v0.7.0
   Compiling pdf v0.8.1
   Compiling bk-tree v0.4.0
   Compiling clap_builder v4.2.3
   Compiling zip v0.6.4
   Compiling image_hasher v1.1.2
   Compiling lofty v0.11.0
   Compiling i18n-embed-fl v0.6.6
   Compiling tempfile v3.5.0
   Compiling directories-next v2.0.0
   Compiling imagepipe v0.5.0
   Compiling vid_dup_finder_lib v0.1.1
   Compiling futures v0.3.28
   Compiling humansize v2.1.3
   Compiling audio_checker v0.1.0
   Compiling infer v0.12.0
   Compiling clap_derive v4.2.0
   Compiling xxhash-rust v0.8.6
   Compiling hamming v0.1.3
   Compiling state v0.5.3
   Compiling czkawka_core v5.1.0
error[E0599]: no function or associated item named `from_data_with_options` found for struct `File` in the current scope
   --> /nfs/site/disks/xpg_dmrhub_0140/gczajkow/rust_crt/.cargo/registry/src/github.com-1ecc6299db9ec823/czkawka_core-5.1.0/src/broken_files.rs:531:66
    |
531 | ...                   if let Err(e) = pdf::file::File::from_data_with_options(content, parser_options) {
    |                                                        ^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `File<_, _, _>`

**Comment by jyoung15** [comment]
Looks like the pdf crate broke [SemVer compatibility](https://doc.rust-lang.org/cargo/reference/resolver.html#semver-compatibility) in https://github.com/pdf-rs/pdf/commit/13938b8d5dbe4b888ad4e97cbbe381bf9ea6ef25.  

As a short-term fix, this works for me.  It references the commit prior to the breaking change:
```
cargo install czkawka_cli --config "patch.crates-io.pdf.git = 'https://github.com/pdf-rs/pdf.git'" --config "patch.crates-io.pdf.rev = '7e4e9974'"
```

**Comment by gcflymoto** [comment]
Thanks for the workaround!
