### ISSUE TITLE
Malformed video blocks similar-video search

### ISSUE THREAD

**Issue by Franco67** [qarmin/czkawka#975]
Hi.
The presence of a malformed file in the search path causes Czkawka to stop after the hash generation: the dialog with the percentages remains in place, all progresses to 100% but no reaction, not even to the cancel button.
The terminal shows that:

thread '<unnamed>' panicked at 'ffprobe failure. Got unexpected rotation. src_path: <filename>.mp4, rotation: Some(-9223372036854775808)', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ffmpeg_cmdline_utils-0.1.1/src/ffmpeg_stats.rs:165:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I hope this might help you to identify this minor bug.
Franco.

**Comment by Farmadupe** [comment]
I have fixed the error in underlying library "ffmpeg_cmdline_utils". Root cause was unnecessary explicit panic, which I have converted into an error instead.

I have published ffmpeg_cmdline_utils v0.1.3 on crates.io with this fix. I have not tested the change. But it should be OK.
