### ISSUE TITLE
Version 6.0.0 won't run on Windows

### ISSUE THREAD

**Issue by vivadavid** [qarmin/czkawka#989]
Hi,

I've just downloaded version 6.0.0. for Windows, I click on _czkawka_gui.exe_, as usual, to run it, but nothing happens.

I'm on Windows 11 (22H2), build 22621.1778.

**Comment by qarmin** [comment]
Strange, because I tested this on Windows 10 and everything worked fine

https://github.com/qarmin/czkawka/assets/41945903/5593a736-15e4-42ba-9c72-b2bcf9656130

Can you download and run in powershell - https://github.com/qarmin/czkawka/releases/download/6.0.0/windows_czkawka_gui_debug_console.zip and paste here what is shown in console?

**Comment by vivadavid** [comment]
Sorry, could you give me more details as to what to do? I've run Powershell and I'm now on the folder where I've extracted the zip file.  What next?

I've tried typing _czkawka_cli.exe_ and then _czkawka_gui.exe_, but I've got the same message: it's not recognized. I'm not familiar with Powershell and I'm using as if it were Command Prompt.

**Comment by qarmin** [comment]
Probably `./czkawka_gui.exe` should work

**Comment by vivadavid** [comment]
I've typed exactly that and nothing happens.

![czkawka_01](https://github.com/qarmin/czkawka/assets/9334287/26084761-239c-4217-9be1-d90a07b0aa32)

**Comment by qarmin** [comment]
Are you really sure, that you are running exe from `windows_czkawka_gui_debug_console.zip`, not from `windows_czkawka_gui.zip`

Builds without debug console by default not printing anything.


https://github.com/qarmin/czkawka/assets/41945903/c124232b-7167-4f22-9ad1-27de2e2058ed

**Comment by ghostebony** [comment]
I tried, nothing showing up
![image](https://github.com/qarmin/czkawka/assets/47510020/e0f32f1c-0702-436b-a134-6b30ade768e2)

**Comment by ghostebony** [comment]
![image](https://github.com/qarmin/czkawka/assets/47510020/b4363043-467a-4810-8d29-22813b020d4f)

**Comment by ghostebony** [comment]
![image](https://github.com/qarmin/czkawka/assets/47510020/5d1824b0-d3dc-4be6-8b7c-76c6ad09a2d0)

**Comment by vivadavid** [comment]
This is what I've done:

1. I've unzipped windows_czkawka_gui_debug_console.zip.
2. In File Explorer, on the unzipped folder, I've right-clicked to open the Terminal.
3. On a Windows PowerShell tab, I've typed: ./czkawka_gui.exe
4. Nothing happens.

**Comment by qarmin** [comment]
Can you try to use this build https://github.com/qarmin/czkawka/suites/13518521756/artifacts/743145474 ?

I reverted GTK 4.10 update

**Comment by ghostebony** [comment]
> Can you try to use this build https://github.com/qarmin/czkawka/suites/13518521756/artifacts/743145474 ?
> 
> I reverted GTK 4.10 update

exactly the same here

**Comment by vivadavid** [comment]
> Can you try to use this build https://github.com/qarmin/czkawka/suites/13518521756/artifacts/743145474 ?
> 
> I reverted GTK 4.10 update

Still nothing happens.

**Comment by qarmin** [comment]
New build - https://github.com/qarmin/czkawka/suites/13518789880/artifacts/743165518 - this reverts GTK to version 4.6 which is used in Czkawka 5.1

`./czkawka_cli.exe` print something to console?

```
$Env:GSK_RENDERER = "help"
./czkawka_gui.exe
```

should print all available renderers, for me this is:
```
Supported arguments for GSK_RENDERER environment variable:
   cairo - Use the Cairo fallback renderer
  opengl - Use the OpenGL renderer
      gl - Use the OpenGL renderer
```
can you try to use all of them:
```
$Env:GSK_RENDERER = "cairo"
./czkawka_gui.exe

$Env:GSK_RENDERER = "opengl"
./czkawka_gui.exe

$Env:GSK_RENDERER = "gl"
./czkawka_gui.exe
```

If this does not help, I have no idea what could be causing this error

**Comment by vivadavid** [comment]
This time I got something:

![czkawka_02](https://github.com/qarmin/czkawka/assets/9334287/adcc1632-51c7-4d3f-b70a-1bfd9ae05031)

**Comment by victornavorskie** [comment]
![image](https://github.com/qarmin/czkawka/assets/101263764/8f9ca2ab-7e35-468e-95ca-0fd42d110d9e)

**Comment by victornavorskie** [comment]
The czkawka_gui.exe displays both the command-line interface (CLI) and the graphical user interface (GUI) simultaneously, but it is still functional and operational.

**Comment by qarmin** [comment]
Console window is expected, because this was build with debug console.

I updated windows files in release page - https://github.com/qarmin/czkawka/releases/tag/6.0.0

Thanks for your cooperation
