### ISSUE TITLE
Version 6.0.0 fails to load .webp images for preview

### ISSUE THREAD

**Issue by Andy-2732** [qarmin/czkawka#995]
After updating from version 5.0.2 to version 6.0.0  .webp images fail to load for preview.

1. Put two identical images in a folder and use 'Similar Images' tool
2. In version 5 clicking one of the results loads an image preview
3. In version 6 clicking one of the results does not load a preview. Message: Failed to open image ⁨*PATH*.webp⁩, reason ⁨Couldn’t recognize the image file format for file *PATH*.webp⁩

**Comment by qarmin** [comment]
Version 6.0 use now native preview loader which should be faster than previous solution.

`webp-pixbuf-loader` is new required package for both linux and mac (https://repology.org/project/webp-pixbuf-loader/versions)

In Windows I tested that this also worked fine, but looks that i forgot to pack it into zip folder

**Comment by Andy-2732** [comment]
This makes sense - thank you!
